### ISSUE TITLE
Separate the dev and production outputs

### ISSUE THREAD

**Issue by avi12** [wxt-dev/wxt#1010]
### Feature Request
Whether if I execute `wxt` or `wxt --build`, the output will be `chrome-mv3`
This poses an issue:
If I wish to simultaneously test on Chrome desktop and a Chromium browser on Android (such as Kiwi), it makes the development cycle quite cumbersome, especially since `web-ext` does not support yet setting up a dev server for `chrome-android`

#### Is your feature request related to a bug?
N/A

### What are the alternatives?
Every time I make a modification I need to run `wxt` to test on Chrome desktop, and every time I need to run it on Android I need to run `wxt --build`, zip, and push `[ext-name]-[version].zip` to the device
If I could have separate `chrome-dev-mv3` and `chrome-prod-mv3`, I could zip the latter directory and push it to the device flawlessly

### Additional context
A potential solution is to let the developer specify a custom tag, e.g. `wxt --build --tag prod` → `chrome-prod-mv3`

**Comment by 1natsu172** [comment]
@avi12 WXT already provide the way with reusable-module, but there is another problem and it is a blocker for use cases. See https://github.com/wxt-dev/wxt/issues/939 .

**Comment by avi12** [comment]
Regardless of this separation, I see it as a necessity to let the developer build the extension with a custom tag, e.g. for A/B testing

**Comment by avi12** [comment]
@aklinker1 Sorry for pinging, do you have a projection of when this feature will be available? I believe the implementation could involve adding to the `wxt.config.ts` a field `outputDirTemplate`

**Comment by aklinker1** [comment]
I work on WXT in my free time, so no, I will never have estimates for when I can work on things.

**Comment by aklinker1** [comment]
Closing this in favor of https://github.com/wxt-dev/wxt/issues/1069

**Comment by aklinker1** [comment]
Released `outDirTemplate` in [`v0.19.12`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.12)

**Comment by aklinker1** [comment]
In v0.20, the default for `outDirTemplate` is changing to support this use-case by default. See https://github.com/wxt-dev/wxt/pull/1086 for details.

**Comment by aklinker1** [comment]
Released in [v0.20.0](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.20.0)
