### ISSUE TITLE
Pass CLI flag to force zip source creation

### ISSUE THREAD

**Issue by avi12** [wxt-dev/wxt#1012]
### Feature Request
While it's great that `wxt --build -b firefox` results in creating a source zip, other browsers like Opera require it as well
If I'm developing a closed source extension, especially with a framework like WXT, I must upload the source zip to a storage service like Google Drive/OneDrive. make the folder public and link it in the second text box
![Screenshot from the Opera dashboard](https://github.com/user-attachments/assets/cb960eac-1369-49b5-ba0e-dddb5217fdcb)

#### Is your feature request related to a bug?
N/A

### What are the alternatives?
Using packages like [zip-self](https://npm.im/zip-self)

### Additional context
It would be cool if I could just do `wxt --build --with-sources` and it worked

**Comment by aklinker1** [comment]
We can add a flag so that `wxt zip --sources` zips sources. When `-b firefox` or `-b opera`, it should default to true. Should be false otherwise.

**Comment by aklinker1** [comment]
For now, `wxt zip -b firefox` will create a ZIP for opera.

**Comment by Timeraa** [comment]
Taking this
