### ISSUE TITLE
`.gitignore` should affect source zip production

### ISSUE THREAD

**Issue by avi12** [wxt-dev/wxt#1013]
### Describe the bug

The sources zip contained some files listed in `.gitignore`

### Reproduction

Look below

### Steps to reproduce

1. Create `secrets.env`
2. Add it to `.gitignore`
3. `wxt --build -b firefox`
4. The source zip contains `secrets.env`

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 Intel(R) Core(TM) i7-6950X CPU @ 3.00GHz
    Memory: 37.10 GB / 63.91 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    wxt: ^0.19.10 => 0.19.10
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Timeraa** [comment]
I don't think `wxt zip` should ignore based on the `.gitignore` because a lot of the times you have tmp files downloaded / compiled whatever that you do not want pushed to git but want in your finished product.

**Comment by avi12** [comment]
I get what you're saying, but there will be a middle-ground
I deploy my projects using my [web-ext-deploy](https://npm.im/web-ext-deploy) using the Gitignored env variables and imagine if I use WXT to create the source zip and all of a sudden the Mozilla reviewer has access to my client IDs and secrets

**Comment by avi12** [comment]
@aklinker1 Sorry for the ping, I'd appreciate it if you could prioritize tackling this issue as it's a crucial part of maintaining my extensions

**Comment by aklinker1** [comment]
I'm not planning to implement this. Some gitignored files are required in sources zip by WXT in some cases, specifically when downloading packages that require authentication.

Instead, just add gitignored patterns to the `excludeSources` option yourself:

```ts
// wxt.config.ts
import { readFile } from 'node:fs';

// You'll probably have to filter out comments as well, see https://www.npmjs.com/package/parse-gitignore for a complete solution
const gitignorePatterns = readFile(".gitignore", "utf8").split("\n");

export default defineConfig({
  zip: {
    excludeSources: gitignorePatterns,
  },
});
```
