### ISSUE TITLE
Add runtime tags

### ISSUE THREAD

**Issue by avi12** [wxt-dev/wxt#1024]
### Feature Request
I like the tags feature by [Plasmo](https://docs.plasmo.com/framework/workflows/build#with-a-custom-tag), and this framework could focus on the general use case

#### Is your feature request related to a bug?
N/A

### What are the alternatives?
```bash
set VITE_TAG=test && wxt
```
```toml
# .env.test
VITE_IMPORTANT_ENV="foobar"
```
I'm not sure as for the output directory

### Additional context
```shell
wxt --tag test
```
this would affect:
1. ```ts
   process.env.VITE_TAG === "test"
   ```
2. Values in`.env.test` would be populated in `import.meta.env`
3. The build output will be `chrome-test-mv3/`

**Comment by aklinker1** [comment]
This already exists in Vite, it's code "modes", and is already supported by WXT

```ts
pnpm wxt build --mode=test
```

It will load the `.env.test` file as well. Read more about it in Vite's docs: https://vite.dev/guide/env-and-mode.html

**Comment by aklinker1** [comment]
There was discussion around adding browser to .env file resolution on discord as well. So you could do something like `.env.firefox.production`: https://discord.com/channels/1212416027611365476/1224505556346212515/1296857455661420606

**Comment by avi12** [comment]
Sounds good
So far I attempted to get around it with
```ts
import dotenv from "dotenv";

export default defineConfig({
  hooks: {
    ready(wxt) {      
      const pathEnvs: Record<string, string> = {
        production: ".env.production",
        development: ".env.local",
        test: ".env.test"
      };
      dotenv.config({ path: pathEnvs[wxt.config.mode] });
    }
  }
});
```
