### ISSUE TITLE
Different framework apis/composables

### ISSUE THREAD

**Issue by ultimateshadsform** [wxt-dev/wxt#1039]
### Feature Request

It would be nice to have different packages that are reactive like Vue 3. Example
```ts
import { useBrowserStorage } from 'wxt/vue';

const storage = useBrowserStorage('mykey', someDefaultValue, 'local');

storage.value = 1 + 1;
```

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

There is a local storage but it's not using browser extension storage and is using window local storage. In VueUse.
https://vueuse.org/core/useStorage/#usestorage
https://github.com/vueuse/vueuse/blob/main/packages/core/useStorage/index.ts

### Additional context

Would be nice to have!

**Comment by aklinker1** [comment]
I don't think this needs to be released a first-party package maintained by WXT, I have my hands full as is lol. I've already written an example composable for reactive storage in vue:

https://github.com/wxt-dev/examples/blob/main/examples/vue-storage-composable/composables/useStoredValue.ts

If someone wants to contribute an add-on package to vueuse or any other utilities package, feel free.

I don't plan on adding anything specific to individual fronted frameworks beyond build support.

**Comment by aklinker1** [comment]
Though, maybe it makes sense to provide runtime utils in `@wxt-dev/module-vue`. Something like

```ts
export { useExtensionStorage } from '@wxt-dev/module-vue/client';
```

Hmm, for now, I'm gonna leave this closed.

**Comment by ultimateshadsform** [comment]
Yeah that would be cool!
