### ISSUE TITLE
change output folder's name

### ISSUE THREAD

**Issue by xckevin** [wxt-dev/wxt#1064]
### Feature Request

By default, wxt build output is `.output` which is considered a hidden folder. So we cannot choose file in browser
![image](https://github.com/user-attachments/assets/b1680944-804f-4458-b818-5768f2ab2eee)

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

change name to 'output', and add it into `.gitignore`

**Comment by aiktb** [comment]
Just press `cmd`+`shift`+`.`

**Comment by breadgrocery** [comment]
The directory  `.output` is not recognized by `actions/upload-artifact@v4` in the GitHub workflow either.
It says:
```
No files were found with the provided path: .output/*.zip
```
But the files do exist:
```
Run ls -al .output
total 1548
drwxr-xr-x  3 runner docker   4096 Oct 14 01:20 .
drwxr-xr-x 16 runner docker   4096 Oct 14 01:19 ..
drwxr-xr-x  7 runner docker   4096 Oct 14 01:20 chrome-mv3
-rw-r--r--  1 runner docker 750782 Oct 14 01:20 download-manager-chrome.zip
```

**Comment by aklinker1** [comment]
> With actions/upload-artifact@v4 v4.4 and later, hidden files are excluded by default.

This was a very controversial change that broke a lot of things, including WXT projects. Seemed to be a quick reaction to a potential security issue that got merged too quickly.

Can confirm that `include-hidden-files` works.

**Comment by aklinker1** [comment]
And yes, you can already change the output folder's name: https://wxt.dev/api/reference/wxt/interfaces/InlineConfig.html#outdir
