### ISSUE TITLE
organizing modules order

### ISSUE THREAD

**Issue by breadgrocery** [wxt-dev/wxt#1065]
### Feature Request

Provide an approach to organize the module order (either **official** or **custom** modules).

#### Is your feature request related to a bug?

For example, the module `@wxt-dev/i18n` requires access to the value of `wxt.config.manifest.default_locale`. 
However, I do not plan to define this value within the `defineConfig` function of `wxt.config.ts` for some reason. 
Instead, I intend for one of my custom modules to produce the entire manifest object (Retrieving `mode` and `browser` from wxt to generate a browser-specific manifest etc.).

```js
const module$1 = modules.defineWxtModule({
  name: "@wxt-dev/i18n",
  imports: [{ from: "#i18n", name: "i18n" }],
  setup(wxt) {
    if (wxt.config.manifest.default_locale == null) {
      wxt.logger.warn(
        `[i18n] manifest.default_locale not set, \`@wxt-dev/i18n\` disabled.`
      );
      return; 
    }
......
```

However, the generated `userModules` have the following order, causing the `@wxt-dev/i18n` module to fail due to missing configuration property.

```json
"userModules": [
  {
    "name": "@wxt-dev/module-vue",
    "configKey": "vue",
    "type": "node_module",
    "id": "@wxt-dev/module-vue"
  },
  {
    "name": "@wxt-dev/i18n",
    "imports": [{ "from": "#i18n", "name": "i18n" }],
    "type": "node_module",
    "id": "@wxt-dev/i18n/module"
  },
  { "name": "manifest.ts", "type": "local", "id": "D:/dm/modules/manifest.ts" },
  { "name": "offscreen.ts", "type": "local", "id": "D:/dm/modules/offscreen.ts" }
]

```

### What are the alternatives?

Provide an **optional configuration** property within `WxtModule` and `WxtModuleSetup` to control the module execution order.

Either by `priority` (numerical order) or by `before`&&`after` (module-name based order), and sort modules before execution.

**Comment by aklinker1** [comment]
Will need to think about the right way to do this, but I agree we need something.

For now, any modules that need to run in specific orders, you can put in the `modules` directory and prefix them with a number:

```
modules/
  0.manifest.ts
  1.i18n.ts
```

```ts
// modules/i18n.ts
import i18n from '@wxt-dev/i18n/module';

export default i18n;
```

I think that should do it? If not, I can add sorting as a quick fix.

That said, it also appears hooks from the wxt.config.ts file have a lower priority than modules, which I didn't intend. 

https://github.com/wxt-dev/wxt/blob/8e527dc96b65a4eb4f6c6da5c42d236f46c9eb2a/packages/wxt/src/core/wxt.ts#L56-L69

I'll update that so your config's hooks run before any module hooks.

**Comment by breadgrocery** [comment]
I didn't figure out this method. 
I imported the official modules by configuring the `modules` property, and then added the custom modules through the module automatic scanning as the [document](https://wxt.dev/guide/go-further/reusable-modules.html) says. 

> ```ts
> // modules/i18n.ts
> import i18n from '@wxt-dev/i18n/module';
> 
> export default i18n;
> ```

This method solved my problem, and it seems to be a relatively simple and common way. 
But at least a section on organizing the order of modules can be added to the document for those who also want to organize the order of modules.
