### ISSUE TITLE
Add `entrypoints:beforeResolve` hook

### ISSUE THREAD

**Issue by breadgrocery** [wxt-dev/wxt#1072]
#### Is your feature request related to a bug?

The current configuration property `filterEntrypoints` lacks flexibility. It requires **explicitly listing all entrypoints** that need to be built, which becomes cumbersome when you only need to **exclude specific entrypoints** in certain scenarios.

For example, I want to exclude the offscreen entrypoint when the browser is firefox. 
The only solution I've found is as follows. Other approaches either fail to retrieve all entrypoint names for exclusion or fail to configure.

```js
import { defineWxtModule } from "wxt/modules";

const entrypoints = {
  common: ["background", "options", "popup"],
  chrome: ["offscreen"],
  firefox: []
};

export default defineWxtModule(wxt => {
  const { browser } = wxt.config;
  const filterEntrypoints = [...entrypoints.common, ...entrypoints[browser]].filter(Boolean);
  wxt.config.filterEntrypoints = new Set(filterEntrypoints);
});
```

The `skipped` and `exclude` properties in Entrypoint have no effect because the filtering logic is applied before the `entrypoints:resolved` hook is triggered. 
```js
import { defineWxtModule } from "wxt/modules";

export default defineWxtModule(wxt => {
  const { browser } = wxt.config;
  wxt.hooks.hook("entrypoints:resolved", (wxt, entrypoints) => {
    if (browser === "firefox") {
      for (const entrypoint of entrypoints) {
        if (entrypoint.name === "offscreen") {
          entrypoint.skipped = true;
          entrypoint.options.exclude = ["firefox"];
        }
      }
    }
  });
});

```

### What are the alternatives?

Introduce an `entrypoints:beforeResolve` hook.

Although `HookResult` returns void or Promise<void>,  modifications to the `skipped` or `exclude` properties can achieve the goal.

**Comment by aklinker1** [comment]
> ```ts
> const entrypoints = {
>   common: ["background", "options", "popup"],
>   chrome: ["offscreen"],
>   firefox: []
> };
> 
> export default defineWxtModule(wxt => {
>   const { browser } = wxt.config;
>   const filterEntrypoints = [...entrypoints.common, ...entrypoints[browser]].filter(Boolean);
>   wxt.config.filterEntrypoints = new Set(filterEntrypoints);
> });
> ```

Interesting, I guess that's works... But it's not the intentional way of filtering entrypoints. Use `include`/`exclude` in your entrypoints instead, then you don't have to list everything. Those fields are what generates `wxt.config.filterEntrypoints`.

https://wxt.dev/guide/essentials/target-different-browsers.html#filtering-entrypoints

Regardless, I can add this hook, would definitely be useful!

**Comment by breadgrocery** [comment]
Thanks for the tip. I am not familiar with how to define the attributes of entrypoints of type html.
This works for me.
```html
<meta name="manifest.include" content="['chrome']" />
```


> Regardless, I can add this hook, would definitely be useful!

Yeah. Coding offers more flexibility than configuration.

**Comment by abhigyantrips** [comment]
@aklinker1 this needs to be closed btw

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.23
