### ISSUE TITLE
Scripting.RegisteredContentScript in main world

### ISSUE THREAD

**Issue by salmin89** [wxt-dev/wxt#1073]
### Describe the bug

I have a use case where I need to dynamically register content scripts in the MAIN-world, for certain URLs. 
The webextension-polyfill and chrome.scripting.RegisterContentScript seem to have a miss-match.

chrome:
```typescript

interface RegisteredContentScript {
        id: string;
        allFrames?: boolean;
        matchOriginAsFallback?: boolean;
        css?: string[];
        excludeMatches?: string[];
        js?: string[];
        matches?: string[];
        persistAcrossSessions?: boolean;
        runAt?: "document_start" | "document_end" | "document_idle";
        world?: ExecutionWorld;
    }
```

But in webext.. world is not a known property.

Question: is this due to limitations in firefox or just an oversight?
 

### Reproduction

```typescript
export default defineBackground(async () => {
  const res = await browser.scripting.registerContentScripts([
    {
      id: 'content',
      matches: ['*://*/*'],
      js: ['injected.js'],
      runAt: 'document_start',
      // @ts-ignore
      world: 'MAIN' // ts-error
    }
  ])
});
```

### System Info

```shell
System:
    OS: macOS 14.7
    CPU: (12) arm64 Apple M2 Pro
    Memory: 450.42 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.0 - ~/.nvm/versions/node/v18.20.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v18.20.0/bin/npm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 129.1.70.126
    Chrome: 130.0.6723.59
    Chrome Canary: 132.0.6781.0
    Edge: 129.0.2792.89
    Safari: 18.0.1
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Just an issue with the polyfill's types. In the next major version,  WXT will be removing the polyfill - I'd recommend you disable it now to get newer types:

https://github.com/wxt-dev/wxt/issues/868

**Comment by salmin89** [comment]
thanks for the fast response! I'll close this issue.

Just a related question - do you have any idea on how I can import a contentScript from another package, to be used in registerContentScript?

**Comment by aklinker1** [comment]
You can use WXT modules to programmatically add entrypoints into your project from NPM packages. Unfortunately, there aren't many good examples of this yet.

You'll want to use the [`addEntrypoint` helper](https://wxt.dev/api/reference/wxt/modules/functions/addEntrypoint.html)
