### ISSUE TITLE
[auto-icons] Allow any image than .png

### ISSUE THREAD

**Issue by ultimateshadsform** [wxt-dev/wxt#1089]
### Feature Request

Would be nice to allow any .jpeg, .bmp etc.

So I don't have to have duplicate images in different formats.

I think sharp has a toFormat function that can output .png no matter what input is used.

And add some input file option or a glob for icon path search.

**Comment by aklinker1** [comment]
JPEG's can't have transparent pixels, so if you use one you're probably breaking Chrome's guidelines if you use one: https://developer.chrome.com/docs/webstore/images#icon-size

> I think sharp has a toFormat function that can output .png no matter what input is used.

Doesn't `sharp(path).png()` already do this? Did you try setting a custom [`baseIconPath`](https://github.com/wxt-dev/wxt/blob/842c158f96b1e469f50efdca385f9909e35811f0/packages/auto-icons/src/index.ts#L91)?

> And add some input file option or a glob for icon path search.

WXT already automatically discovers icons without the auto-icons module. Why add support for this in auto-icons? What's your use-case?

**Comment by ultimateshadsform** [comment]
I mean if I have a base icon of .jpg. or any other. Then convert it to .png using the toFile function:
```ts
sharp(input)
  .toFile('output.png', (err, info) => { ... });
```

**Comment by ultimateshadsform** [comment]
Your code only scans for .png files and not .jpg or .bmp.

What I mean is if there IS any .bpm or ,jpg or .jpeg you CONVERT them into a .png using the .toFormat function so I can keep using .jpg inside my app without having 2 files 1 for icon and 1 for using in the extension.

**Comment by aklinker1** [comment]
> I would suggest having a name like `icon.*` to support any .jpg, .bmp, jpeg, jpg etc. then you use the .toFormat function to convert them into a VALID .png file. For only use with icons.

OK, so you just want to add glob support to `baseIconPath`. Sure, I'm on board with that. You wanna open a PR?

**Comment by ultimateshadsform** [comment]
Yeah sure I can do it!

I wanna add support for JPEG (.jpg, .jpeg, .jpe, .jfif)
PNG (.png)
GIF (.gif)
TIFF (.tiff, .tif)
BMP (.bmp)
HEIF (.heif, .heic)
AVIF (.avif)
WebP (.webp) etc.

But really in the end you convert them into a .png.

I'll make a pr. 👍

**Comment by ultimateshadsform** [comment]
It's true that transparency will not work if trying to use with .jpg etc. Then you will have to use a .png from the start. But this is just for images that do not use transparency because that doesn't make sense to use jpg if you need transparency etc..

**Comment by aklinker1** [comment]
> It's true that transparency will not work if trying to use with .jpg etc. Then you will have to use a .png from the start. But this is just for images that do not use transparency because that doesn't make sense to use jpg if you need transparency etc..

Yeah, but that goes against chrome's guidelines for normalizing extension icons: 

<img width="449" alt="Screenshot 2024-10-19 at 2 31 41 PM" src="https://github.com/user-attachments/assets/e043bda0-cdd8-4d67-978a-3558405d7242">
There's nothing preventing you from doing it, but it will look bad in the end. 

But I'm fine with using `assets/icon.*` and supporting JPEG. As long as PNG and other formats that support transparency are prioritized when there are multiple matches, that's fine.

**Comment by ultimateshadsform** [comment]
True. But yeah it's nice with options.

**Comment by breadgrocery** [comment]
My solution is overwirte the module as a new module `module-auto-icons.ts` under `modules` directory
```js
import module from "@wxt-dev/auto-icons";
import { resolve } from "node:path";
import { defineWxtModule } from "wxt/modules";

export default defineWxtModule({
  ...module,
  setup: (wxt, options) => {
    module.setup?.(wxt, {
      baseIconPath: resolve(wxt.config.publicDir, "images/icon.svg"),
      grayscaleOnDevelopment: false,
      sizes: [256, 128, 96, 48, 32, 16],
      ...options
    });
  }
});
```

**Comment by aklinker1** [comment]
@breadgrocery as long as you extend `.wxt/tsconfig.json` in your projects tsconfig, WXT automatically adds type references like that so you shouldn't have to manually add that export.

**Comment by breadgrocery** [comment]
> @breadgrocery as long as you extend `.wxt/tsconfig.json` in your projects tsconfig, WXT automatically adds type references like that so you shouldn't have to manually add that import.

No, it didn't. I even explicitly specify in the `types` in tsconfig.json and still don't get the typings prompt. I don't know what happened.

**Comment by aklinker1** [comment]
Hmm, interesting, works for me. Was using it earlier today 🤔. If you've got a reproduction I'd appreciate you opening a separate issue.

**Comment by breadgrocery** [comment]
> Hmm, interesting, works for me. Was using it earlier today 🤔. If you've got a reproduction I'd appreciate you opening a separate issue.

My `srcRoot` is **src** instead of workspace root.  And it works when `srcRoot`  is workspace root.
This is my tsconfig.json.
```json
{
  "extends": "./src/.wxt/tsconfig.json",
  "compilerOptions": {
    "types": ["naive-ui/volar", "unplugin-icons/types/vue", "@types/chrome"]
  }
}
```
And I find out that I must configure both `include` and `types` to get it work.
I'm not very familiar with TypeScript. Is there any other way?
```json
{
  "extends": "./src/.wxt/tsconfig.json",
  "include": ["./wxt.config.ts"],
  "compilerOptions": {
    "types": ["naive-ui/volar", "unplugin-icons/types/vue", "@types/chrome", "@wxt-dev/auto-icons"]
  }
}
```
