### ISSUE TITLE
Svelte 5 Support

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#1099]
### Feature Request

Svelte 5 is out, need to update `@wxt-dev/module-svelte`'s peer dependencies to support v4 of the vite plugin.

Should also update the template to use svelte v5.

Tested in an example project, basic template works just fine with small changes.

[wxt-svelte-5.zip](https://github.com/user-attachments/files/17464556/wxt-svelte-5.zip)

Alternatively, to upgrade to Svelte 5, you'll need to add an overrides to force the `@svelte/vite-plugin-svelte` version to v4.

**Comment by Anivone** [comment]
+ 1
 Need this
