### ISSUE TITLE
[submit] REST Publish API v1.1 support for Microsoft Edge Add-ons

### ISSUE THREAD

**Issue by breadgrocery** [wxt-dev/wxt#1127]
### Feature Request

> As of September 6, 2024, both v1.1 and v1 of this Update REST API are supported. Later, v1 will no longer be supported. The date for ending v1 support is not yet finalized.

As a witness, Microsoft partner center has stopped providing the `ACCESS_TOKEN_URL` required for the v1 version of the API to newly registered users. Since v1 support is nearing its end, Microsoft is gradually phasing it out.
See: https://github.com/wdzeng/edge-addon/issues/8#issuecomment-2394799789

#### Is your feature request related to a bug?
N/A

### What are the alternatives?

Since v1 will inevitably be deprecated, it’s best to upgrade to v1.1 as soon as possible.

Reference: [Publish API](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1)

Edit: I realized that it’s actually your other project [publish-browser-extension](https://github.com/aklinker1/publish-browser-extension), that implements this. It seems I may have made this request in the wrong place lol.

**Comment by aklinker1** [comment]
Yeah, this should go in the other repo. I'll transfer it for you!
