### ISSUE TITLE
React Devtool doesn't show on popup/html

### ISSUE THREAD

**Issue by ducan-ne** [wxt-dev/wxt#1144]
### Describe the bug

React Devtool doesn't show up on devtool panels:
![CleanShot 2024-11-06 at 22 56 12@2x](https://github.com/user-attachments/assets/8c2c220e-3afd-46f0-a8c0-4b7df3f96c4f)

Tried to fix, even with https://github.com/facebook/react/tree/main/packages/react-devtools#the-react-tab-doesnt-show-up but it still does not work

### Reproduction

It doesn't work with a new project init with "pnpm dlx wxt@latest init"

### Steps to reproduce

- pnpm dlx wxt@latest init
- pnpm install
- pnpm dev

### System Info

```shell
node v20.13.1
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aiktb** [comment]
> If your app is inside an iframe, a Chrome extension, React Native, or in another unusual environment, try [the standalone version instead](https://github.com/facebook/react/tree/main/packages/react-devtools). Chrome apps are currently not inspectable.

This problem has nothing to do with wxt. According to the above description, I tried to install react-devtools and relax the required CSP of port 8097, and introduced `<script src="http://localhost:8097"></script>` from index.html.

But this didn't make react-devtools work properly, just a black screen and I have no idea why.
![image](https://github.com/user-attachments/assets/1909b611-a011-4d75-8ba0-0bda271bee2e)

Maybe you should ask the maintainers of react-devtools, I didn't find a working solution on google and stackoverflow.

**Comment by 1natsu172** [comment]
It seems to work with a few settings. I'll post a reference (haven't tested it with the `wxt init` project).
https://github.com/facebook/react-devtools/issues/91
https://stackoverflow.com/questions/67651633/how-to-add-react-devtools-for-chrome-extension-development
