### ISSUE TITLE
Allow reaching outside of package directory for assets

### ISSUE THREAD

**Issue by Nantris** [wxt-dev/wxt#1151]
### Feature Request

I'd like to share assets in a monorepo but it's not currently possible. The assets (eg icon) files will not be found. It seems like even if you define an absolute path, it forcibly searches a relative one. On Linux at least, it removes the leading `/`

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

Duplicate our assets, which is no fun.

**Comment by aklinker1** [comment]
hmm, I would say this is more of a big than a feature. I would think Vote already supports this, but it could be an issue with how WXT rewrites asset URLs. 

Could you provide a small reproduction of this error?

**Comment by Nantris** [comment]
Thanks for your reply @aklinker1. I ended up symlinking since I'm on Linux. Unfortunately I won't have time to make a repro. Apologies.

**Comment by Nantris** [comment]
If this is a bug, why not leave it open? Symlinks are not tenable on all platforms, but your call of course.

**Comment by aklinker1** [comment]
Unless a bug has a reproduction, I close it. I've updated the labels

**Comment by st3h3n** [comment]
I had the same problem. I fixed it by using `DynamicPublicDirectory` from the vite plugin [vite-multiple-assets](https://github.com/nguyenbatranvan/vite-multiple-assets).

It also allows removing the parent directory from the path which you will have when using a monorepo. So normally `'../src/assets/**'` would produce `output/src/assets`, but the plugin allows you to do `'../src/{\x01,assets}/**'` which produces `output/assets`
