### ISSUE TITLE
Auto icons are grayscaled

### ISSUE THREAD

**Issue by Nantris** [wxt-dev/wxt#1152]
### Describe the bug

Including `modules: ['@wxt-dev/auto-icons']` creates our icons, but they're all grayscale.

### Reproduction

Just use the plugin it seems?

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (6) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 11.96 GB / 27.36 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.14.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 129.0.6668.100
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nantris** [comment]
This does not appear to be linked to any particular `.png` file, but rather affects all `.png` files from all sources that I've tried.

**Comment by breadgrocery** [comment]
https://github.com/wxt-dev/wxt/blob/5d991eda31cb27807d8ac0f079f2cfa03abf4d1e/packages/auto-icons/src/index.ts#L92-L96
```ts
// wxt.config.ts
export default defineConfig({
  autoIcons: {
    grayscaleOnDevelopment: false
  }
});
```

**Comment by Nantris** [comment]
Ah that's a bit confusing but that explains that. If I recall correctly I searched the docs for "gray" but maybe I only searched the issue. 

Thanks very much!
