### ISSUE TITLE
 'stopOldScripts' event is sent multiple times.

### ISSUE THREAD

**Issue by nonovv** [wxt-dev/wxt#1155]
### Describe the bug

I have multiple wxt extension .
Then the "stopOldScripts" event is sent multiple times.
Then "ctx.onInvalidated" will be called.

### Reproduction

Not required

### Steps to reproduce

Not required

### System Info

```shell
 System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1
    Memory: 103.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.1.0 - /opt/homebrew/bin/node
    npm: 10.9.0 - /opt/homebrew/bin/npm
    pnpm: 9.12.3 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 18.1
  npmPackages:
    wxt: ^0.19.13 => 0.19.13 

```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Please follow the template and provide a reproduction, in this case two WXT extensions with some logs showing that one is effecting the other? If I understand your report correctly.

Will reopen once I have a reproduction.

**Comment by aklinker1** [comment]
Oh interesting, I thought I used the `browser.runtime.id` in the event name... Woops.
