### ISSUE TITLE
running `pnpm i` in windows is causing type error after building unocss.

### ISSUE THREAD

**Issue by nishu-murmu** [wxt-dev/wxt#1157]
### Describe the bug

I was looking for contributing something to the project so I naturally followed the steps mentioned in the `CONTRIBUTING.md` file
My pnpm version is `8.5.1`

**Edit:**  *I noticed my pnpm version was quite old, updated it to `9.12.3`, it is still causing the same issue.*

![some](https://img.enacton.com/ShareX/2024/1112/Cursor_t6dAhALFOy.png)

Here are more screenshots for more reference.
![wxt](https://github.com/user-attachments/assets/931584e2-78b4-49e0-af03-bf4bf09485a7)
![wxt-2](https://github.com/user-attachments/assets/289bbf5c-d289-4f58-ab4a-919e43659c9a)

### Reproduction

1. Use windows
2. clone the repo using ssh `git@github.com:wxt-dev/wxt.git`
3. Follow CONTRIBUTING.md guidelines.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 1.36 GB / 7.84 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - C:\ProgramData\chocolatey\bin\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    wxt: workspace:* => 0.19.13
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

#1163 
This fixes it.
When merged I'll close it.

**Comment by aklinker1** [comment]
For future reference, look into installing `corepack`, it automatically downloads and uses the correct version of the project's package manager listed in the `packageManger` field.

This is mentioned in the setup section of the contributing docs: https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md#setup
