### ISSUE TITLE
injectScript cannot inject main world content script

### ISSUE THREAD

**Issue by rxliuli** [wxt-dev/wxt#1158]
### Describe the bug

I am trying to inject a main world content script into the webpage using the recommended function injectScript, but it is not working properly

```ts
// entrypoints/content.ts
export default defineContentScript({
  matches: ['<all_urls>'],
  async main() {
    console.log('Hello content.')
    await injectScript('/main-world-content.js')
  },
})
```

<img width="750" alt="image" src="https://github.com/user-attachments/assets/bdacd0eb-73b8-4e70-b93c-c36f60f1bc82">

### Reproduction

https://github.com/rxliuli/wxt-main-world-content-script-demo

### Steps to reproduce

```sh
pnpm i && pnpm dev
```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 11.12 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 9.12.3 - /usr/local/bin/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
    Watchman: 2024.10.07.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 129.1.70.126
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 17.4.1
  npmPackages:
    wxt: ^0.19.11 => 0.19.13
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nishu-murmu** [comment]
You forgot to add the specific script in web_accessible_resources.

![wxt-fix](https://github.com/user-attachments/assets/0411e37e-0510-454a-af1b-c5dbe42ceae6)

Please add that in the wxt.config.ts file, then it will work.
