### ISSUE TITLE
The `options_page` field in the wxt configuration is not working as expected.

### ISSUE THREAD

**Issue by kayanouriko** [wxt-dev/wxt#1162]
### Describe the bug

Currently, the options are always categorized under the `options_ui` field instead.
Please forgive my poor English skills, the content above was translated by ChatGPT.

### Reproduction

tried:
```
// wxt.config.ts
export default defineConfig({
  options_page: 'options.html'
});
```

### System Info

```shell
Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    wxt: ^0.19.11 => 0.19.13
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kayanouriko** [comment]
Workaround:
```ts
// wxt.config.ts
import { Manifest } from 'wxt/browser'

export default defineConfig({
    hooks: {
        'build:manifestGenerated': (_, manifest) => {
            let newValue = manifest as { options_page?: string } & Manifest.WebExtensionManifest
            if (newValue.options_page !== undefined) newValue.options_ui = undefined
            manifest = newValue
        }
    },
    manifest: {
        options_page: 'options.html'
    }
})
```

**Comment by aiktb** [comment]
> Alternatively, you can use the [options_ui](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui) key with `open_in_tab` set to true. If `options_ui` is specified, options page is ignored.

This problem doesn't seem to be important. Maybe no fix is ​​needed.

**Comment by kayanouriko** [comment]
![QQ20241113-194605](https://github.com/user-attachments/assets/d4ce584f-0646-440e-97b3-88856c8d81de)

@aiktb Thank you for your prompt reply.
I just tested it, and the fields inside options_ui are not working either.

**Comment by aklinker1** [comment]
@kayanouriko If you add the `<meta>` elements [described in the docs](https://wxt.dev/guide/essentials/entrypoints.html#options), they will be included in the `options_ui`. You shouldn't make any changes to your `manifest` in the `wxt.config.ts` file.
