### ISSUE TITLE
Opening options page from action button is not showing desired options page url.

### ISSUE THREAD

**Issue by nishu-murmu** [wxt-dev/wxt#1170]
### Describe the bug

I want to work on options page.
But when I try open the options page from action button, it is redirecting to some weird url

![wxt-4](https://github.com/user-attachments/assets/11b0c499-d84b-4a39-8145-d1203c6034c9)

**Here's my wxt.config.ts file**

```
import { defineConfig } from 'wxt';

// See https://wxt.dev/api/config.html
export default defineConfig({
  extensionApi: 'chrome',
  runner: {
    startUrls: ['chrome://extensions'],
  },
  hooks: {
    'build:manifestGenerated': (wxt, manifest) => {
      console.log('🚀 ~ wxt:', wxt, manifest);
      manifest.content_scripts ??= [];
      manifest.options_ui = {
        page: 'options.html',
        open_in_tab: false,
      };
      manifest.content_scripts.push({
        css: ['content-scripts/custom.css'],
        matches: ['<all_urls>'],
      });
    },
  },
  modules: ['@wxt-dev/module-react'],
  manifest: {
    name: 'demo',
    short_name: 'demo',
    description: 'demo desc',
    permissions: ['storage', 'tabs', 'activeTab', 'scripting', 'sidePanel'],
    options_page: 'options.html',
    action: {
      default_icon: 'icon/128.png',
    },
    web_accessible_resources: [
      {
        resources: [
          'icon/*.png',
          'images/*.png',
          'images/*.svg',
          'assets/*',
          'content-scripts/custom.css',
        ],
        matches: ['<all_urls>'],
      },
    ],
    host_permissions: ['<all_urls>'],
  },
  entrypointsDir: 'src',
  outDir: 'build',
});

```

### Reproduction

1. Setup options page configuration in extension
2. try opening options page

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 503.92 MB / 7.84 GB
  Binaries:
    Node: 22.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
If you want to open the options page as a regular tab, add a meta tag to tell it to do so:

<img width="728" alt="Screenshot 2024-11-14 at 1 43 32 AM" src="https://github.com/user-attachments/assets/e6a2dbea-8a6f-49bd-bc7e-c080be38d26d">

> From here: https://wxt.dev/guide/essentials/entrypoints.html#options

Defaults to false, and options is reached via `chrome://extensions` page, like you currently see.

**Comment by nishu-murmu** [comment]
Thanks only that much configuration was required.
I unnecessarily complicated things with adding extra values in config.
