### ISSUE TITLE
@types/webextension-polyfill breaks firefox mv3 builds

### ISSUE THREAD

**Issue by maxtheaxe** [wxt-dev/wxt#1185]
### Describe the bug

It's possible I missed this in the documentation somewhere, but I just tried to build my firefox extension for manifest v3 and realized that the built extension was still converting `browser.action` to `browser.browserAction`. Once I switched to `@types/chrome`, the built `background.js` no longer used `browserAction`, solving my issue.

If nothing else, even if this gets insta-closed, hopefully this will make it more searchable for future users.

### Reproduction

[browserAction-issue.zip](https://github.com/user-attachments/files/17800585/browserAction-issue.zip) (contains builds from both versions)

### Steps to reproduce

Run `wxt build -b firefox` while using `@types/webextension-polyfill`.

### System Info

```shell
System:
  OS: Linux 6.9 Pop!_OS 22.04 LTS
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Memory: 35.42 GB / 62.51 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
  npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
  pnpm: 9.13.2 - ~/.local/share/pnpm/pnpm
npmPackages:
  wxt: ^0.19.13 => 0.19.16
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Hmm, looking at the files you provided, both have `action` in the manifest, not `browser_action`, so the manifest looks fine.

You said there was a problem with your background... just installing some type-only packages shouldn't have any effect on the build output. Did you also switch to `extesionApi: 'chrome'`?

**Comment by maxtheaxe** [comment]
Fair point on the first part, yeah—I was thinking for some reason that WXT would translate that itself. That was my misunderstanding.

As for the second part, yeah, I was switching the `extensionApi` to match the typing library
