### ISSUE TITLE
How to add args for open chrome window

### ISSUE THREAD

**Issue by Mistsink** [wxt-dev/wxt#1186]
### Describe the bug

My MacOS is installed in AMD chips, so there is a bug when run wxt dev. If I can modify the open args, like: open -n /Applications/Google\ Chrome.app --args --disable-gpu, this issue will be resoluved. So I want to know how to make it. Thank you so much.

### Reproduction

on AMD chip

### System Info

```shell
MacOS 13, Chrome
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
See https://wxt.dev/guide/essentials/config/browser-startup.html#persist-data
