### ISSUE TITLE
[modules] Add HTML support to `addEntrypoint`

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#1190]
### Feature Request

`addEntrypoint` only works with JS/TS files. It should also support HTML and CSS files.

#### Is your feature request related to a bug?

https://discord.com/channels/1212416027611365476/1224505556346212515/1308513014277996644

### What are the alternatives?

NA

### Additional context

https://discord.com/channels/1212416027611365476/1224505556346212515/1308402108151627816

**Comment by nishu-murmu** [comment]
This seems to be working fine.

Below is the flow

*This is the demo.html file*
![demo-html](https://github.com/user-attachments/assets/b8cad87b-c059-4c87-85f8-7743ae244354)

*Here the required html file is being generated.*
![testing-html](https://github.com/user-attachments/assets/8550f68b-d98f-46b9-a939-abf464c15420)
![testing-html-code](https://img.enacton.com/ShareX/2024/1217/Code_fFHWKzQhvS.png)


Correct me if I'm missing something.
