### ISSUE TITLE
Allow enabling `dev.reloadCommand` when more than 4 shortcut keys are registered

### ISSUE THREAD

**Issue by aiktb** [wxt-dev/wxt#1202]
### Feature Request

Currently, WXT auto disable `dev.reloadCommand` when the extension registers more than 4 shortcut keys and there is no way to force it to be enabled.

This feature is useful and should be allowed if developers are aware of the risk of possible shortcut key conflicts.

Possible API for `wxt.config.ts`:
Ignore warnings to enable this feature when `dev.reloadCommand` is `true`, or change it to object type with a `forceEnable` boolean key.

https://github.com/wxt-dev/wxt/blob/5a3790a7d3595b7b44cf1824c569b379485536dd/packages/wxt/src/core/utils/manifest.ts#L85-L88

**Comment by aiktb** [comment]
> This won't work. If you're registering more than 4 commands in the wxt.config.ts. The extension's manifest itself won't load. You can view the screenshot
> 
> I'm trying to load an extension, pure vanilla extension config, not using this framework. Still it is throwing this error. [screenshot](https://img.enacton.com/ShareX/2024/1128/brave_IDF3z4LVIX.png)

https://stackoverflow.com/a/61057647/17635343
I've seen extensions with more than ten commands, and this restriction only applies to commands with a "suggested_key".

**Comment by aiktb** [comment]
So this is actually a WXT bug?
WXT should calculate the number of keys in the following way:
```js
const suggestedKeyCount = Object.values(commands).filter(command => command.suggested_key).length
if(suggestedKeyCount >= 4){
  warnings.push([ 
     "Extension already has 4 registered suggested key commands, WXT's reload command is disabled", 
   ]); 
}
```

I'll open a PR.

**Comment by nishu-murmu** [comment]
> So this is actually a WXT bug? WXT should calculate the number of keys in the following way:
> 
> ```js
> const suggestedKeyCount = Object.values(commands).filter(command => command.suggested_key).length
> if(suggestedKeyCount >= 4){
>   warnings.push([ 
>      "Extension already has 4 registered suggested key commands, WXT's reload command is disabled", 
>    ]); 
> }
> ```
> 
> I'll open a PR. (Tomorrow)

Yes, just debugged it.
This is correct.

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.18
