### ISSUE TITLE
Integrated UI does not remove appended child elements

### ISSUE THREAD

**Issue by 1natsu172** [wxt-dev/wxt#1218]
### Describe the bug

I noticed this when debugging the #1210  demo. Removing the wrapper does not GC the child elements. Therefore, when the wrapper is mounted again, the number of child elements will continue to increase.

**I will submit PR for fix.**

https://github.com/user-attachments/assets/f2b5c594-1e61-416d-8704-8cf4b7be8368

### Reproduction

[`c469da8` (#1210)](https://github.com/wxt-dev/wxt/pull/1210/commits/c469da8d61019b1cb47d108db939fc6850a3dcde)
The current demo of this commit will grow in elements.

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (14) arm64 Apple M4 Pro
    Memory: 2.19 GB / 64.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.11.0 - ~/.local/share/mise/installs/node/22.11.0/bin/node
    npm: 10.9.0 - ~/.local/share/mise/installs/node/22.11.0/bin/npm
    pnpm: 9.13.0 - ~/.local/share/mise/installs/node/22.11.0/bin/pnpm
    bun: 1.1.34 - ~/.local/share/mise/installs/bun/1.1.34/bin/bun
    Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 130.1.71.123
    Chrome: 131.0.6778.86
    Edge: 131.0.2903.70
    Safari: 18.1.1
  npmPackages:
    wxt: workspace:* => 0.19.16
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Released in [`v0.19.17`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.17)
