### ISSUE TITLE
"Error in invocation of storage.get" when running in MV2 mode

### ISSUE THREAD

**Issue by max-arias** [wxt-dev/wxt#1242]
### Describe the bug

Trying to use @wxt-dev/storage `getItem` or `getItems` fails when building the extension in MV2 (tried both in Chrome and Firefox)

### Reproduction

[mv2-repro.zip](https://github.com/user-attachments/files/17996536/mv2-repro.zip)

### Steps to reproduce

- Unzip
- Install deps
- Run `npm run dev`
- Enable Dev mode in Chrome
- Inspect background page/console
- You should see this error:

<img width="972" alt="Screenshot 2024-12-03 at 2 06 33 PM" src="https://github.com/user-attachments/assets/5208b48a-9da0-40b5-933c-2abd86434494">

(Note: this is just using the vanilla template)

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 6.30 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    Yarn: 4.5.0 - ~/.nvm/versions/node/v20.16.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    bun: 1.1.13 - ~/.bun/bin/bun
    Watchman: 2024.01.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
    Safari Technology Preview: 18.2
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Oh I see, this is ***chrome*** MV2... I could fix this, but MV2 is officially dead on chrome, are you working on a legacy enterprise extension? I think that's the only place MV2 still works on chrome.

**Comment by max-arias** [comment]
Oh weird!

I thought I had caught this originally in Firefox, but I can't repro there:

<img width="930" alt="Screenshot 2024-12-03 at 4 02 01 PM" src="https://github.com/user-attachments/assets/25108d52-8084-4e0a-9deb-73d7bfe83613">

I guess its a non-issue. I only use MV2 in Firefox

**Comment by aklinker1** [comment]
OK, yup, this issue used to happen in firefox, but that was fixed a few weeks ago: https://github.com/wxt-dev/wxt/issues/1199
