### ISSUE TITLE
Support `sidePanel` in `browser` on type level

### ISSUE THREAD

**Issue by paolostyle** [wxt-dev/wxt#1256]
### Feature Request

Currently I am not able to use `chrome.sidePanel` API from `browser`, i.e.` browser.sidePanel` is undefined. It seems like it actually still works, but the missing types is a bummer.

#### Is your feature request related to a bug?

Mentioned here: https://github.com/wxt-dev/wxt/issues/570#issuecomment-2022365906 but I think it deserves a separate issue.

### What are the alternatives?

Just use `chrome.sidePanel` or `// @ts-ignore` but that's awful

### Additional context

none

**Comment by aklinker1** [comment]
To get types for the new MV3 APIs, see: https://github.com/wxt-dev/wxt/issues/868
