### ISSUE TITLE
Svelte error: mount() not available on the server

### ISSUE THREAD

**Issue by m-krebs** [wxt-dev/wxt#1274]
### Describe the bug

When creating a wxt project with svelte, the following error occurs in console:
```
Uncaught Svelte error: lifecycle_function_unavailable
`mount(...)` is not available on the server
```

This error was discussed in #1228 and should (as of my understanding) be fixed by using `@wxt-dev/module-svelte@2.0.1`.

### Reproduction

[reproduction.zip](https://github.com/user-attachments/files/18118114/reproduction.zip)

### Steps to reproduce

Run `pnpm dlx wxt@latest init`, follow the setup and select `svelte`.
Then `cd` into the project and replace `@wxt-dev/module-svelte: ^2.0.0` with `@wxt-dev/module-svelte: ^2.0.1`.
Install dependencies: `pnpm i`.
Build and zip the extension: `pnpm zip:firefox`.
Visit `about:debugging#/runtime/this-firefox` and load temporary Add-on.
Click the Add-ons Icon in Add-on bar and check console in Add-on Inspector.

### System Info

```shell
System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 5800X3D 8-Core Processor
    Memory: 25.36 GB / 31.27 GB
    Container: Yes
    Shell: 3.7.1 - /bin/fish
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 10.5.0 - ~/.local/share/pnpm/npm
    pnpm: 9.15.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chromium: 131.0.6778.108
  npmPackages:
    wxt: ^0.19.13 => 0.19.22
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by avi12** [comment]
I also face this issue, but only in my existing project
In a new one, I can run the Svelte-powered popup without issues

**Comment by avi12** [comment]
https://github.com/avi12/wxt-svelte-test
[wxt-svelte-test.zip](https://github.com/user-attachments/files/18131955/wxt-svelte-test.zip)

**Comment by m-krebs** [comment]
I tried your example, but I have the same Issue when building the extension and loading it manually in both chrome and firefox. How do you load the build extension into your browser?

**Comment by avi12** [comment]
In the example ext I let WXT launch the browser in dev mode

**Comment by m-krebs** [comment]
Yeah, dev mode works on mine, too. I only have the problem when building and manually testing in my browser.

**Comment by avi12** [comment]
@m-krebs I cannot reproduce the issue in [my project](https://github.com/avi12/youtube-auto-hd), whether I let WXT launch the browser for me or I manually sideload it unpacked

**Comment by avi12** [comment]
> Yeah, dev mode works on mine, too.

That's the thing, I only tried running in dev mode, and yet on YTHD it works nicely but my other project cannot run Svelte in the popup/content script 😐

**Comment by m-krebs** [comment]
That's makes it complicated 😅. Could you explain, how you sideload the extension? I might be doing it wrong.
Maybe that might help find the issue with your existing project.

**Comment by avi12** [comment]
I just run `wxt` and put the `build/chrome-mv3-development` folder in Chrome, or let WXT load it into a temp Chrome instance

**Comment by ZerGo0** [comment]
Can confirm that this happens in none dev builds.

1. Run `pnpm dlx wxt@latest init` and select the svelte template
2. Run `pnpm build`
3. Load the extension unpacked in chrome (`/path/to/proj/.output/chrome-mv3/`)
4. Open the extension example pop-up
This should log an error in the chrome extension logs:
```
Uncaught Svelte error: lifecycle_function_unavailable `mount(...)` is not available on the server https://svelte.dev/e/lifecycle_function_unavailable

Context
popup.html
```

This also happens when you zip it (probably anything that isn't dev) and in Firefox.

**Comment by andreasnuesslein** [comment]
i found a temporary fix, folks:

go to `node_modules/@wxt-dev/module-svelte/dist/index.mjs` and do:
```diff
- conditions: mode === "development" ? ["browser"] : []
+ conditions: mode === "development" ? ["browser"] : ["browser"]
```

or just `conditions: ["browser"]`

after this, `npm run build` should give something that works. at least for me. cheers

**Comment by m-krebs** [comment]
@andreasnuesslein Yeah, this seems to work temporarily. The extension just logs a warning about NODE_ENV unset or so. It probably has to do something with the Vite bundling.

**Comment by aklinker1** [comment]
Ah, I see I'm late to the party. Anyone want to open a PR for this fix?

**Comment by avi12** [comment]
@ZerGo0 

> Can confirm that this happens in none dev builds.
> 
> 1. Run `pnpm dlx wxt@latest init` and select the svelte template
> 2. Run `pnpm build`
> 3. Load the extension unpacked in chrome
>    3.1. Visit `chrome://extensions/`
>    3.2. Click the `Load unpacked` button and point it the the example extension directory (`/path/to/proj/.output/chrome-mv3/`)
> 4. Open the example extension pop-up
>    This should log an error in the chrome extension logs:
> 
> ```
> Uncaught Svelte error: lifecycle_function_unavailable `mount(...)` is not available on the server https://svelte.dev/e/lifecycle_function_unavailable
> 
> Context
> popup.html
> ```
> 
> This also happens when you zip it (probably anything that isn't dev) and in Firefox.

What's weird is that in my YTHD I don't get any error during dev mode and yet in YTTM I do get this this Svelte error during dev mode

**Comment by aklinker1** [comment]
OK, I got a fix that works in both dev mode and production builds, without any errors:

```diff
- conditions: mode === "development" ? ["browser"] : []
+ conditions: ["browser", mode]
```

Will open a PR.

**Comment by aklinker1** [comment]
https://github.com/wxt-dev/wxt/pull/1283

**Comment by avi12** [comment]
I tried to put
```json
{
  "devDependencies": {
    "wxt": "github:wxt-dev/wxt"
  }
}
```
and I got
```
C:\repositories\extensions\youtube-time-manager\extension git:[wxt]
pnpm i
../../../../Users/avi12/AppData/Local/pnpm/store/v3/tmp/_tmp_43032_4ea2b01e2261984cc6dc179bc826dd9b [@]: Running pnpm-install script, done in 2m 27.1s
../../../../Users/avi12/AppData/Local/pnpm/store/v3/tmp/_tmp_43032_4ea2b01e2261984cc6dc179bc826dd9b [@]: Running prepublish script, failed in 938ms
...3032_4ea2b01e2261984cc6dc179bc826dd9b prepublish$ pnpm -s build
│ 'build' is not recognized as an internal or external command,
│ operable program or batch file.
└─ Failed in 938ms at C:\Users\avi12\AppData\Local\pnpm\store\v3\tmp\_tmp_43032_4ea2b01e2261984cc6dc179bc826dd9b
 ERR_PNPM_PREPARE_PACKAGE  Failed to prepare git-hosted package fetched from "https://codeload.github.com/wxt-dev/wxt/tar.gz/64a704fc729e95e0703b2549ee62c5577e1628ce": @ prepublish: `pnpm -s build`
Exit status 1

This error happened while installing a direct dependency of C:\repositories\extensions\youtube-time-manager\extension
Progress: resolved 48, reused 48, downloaded 0, added 0
```

**Comment by aklinker1** [comment]
No changes to the `wxt` module. Released fix in https://github.com/wxt-dev/wxt/releases/tag/module-svelte-v2.0.2

**Comment by avi12** [comment]
I installed
```json
{
  "devDependencies": {
    "@wxt-dev/module-svelte": "^2.0.2"
  }
}
```
it seems to be able to load Svelte now, both in the content script and popup page
