### ISSUE TITLE
redirect URI  is different

### ISSUE THREAD

**Issue by ruhchjdbdbhccjjc** [wxt-dev/wxt#1288]
### Describe the bug

```
// Set the redirect URI to the chromiumapp.com provided by Chromium
const redirectUri = typeof browser !== "undefined" && browser.identity ?
    browser.identity.getRedirectURL() : 
    `${window.location.origin}/index.html`;

```
ablove code ,when use in popup html in chrome mainfest 3.0 is return a url start with Https:  ,just like :
https://aaonobiaachigcfphciphdkoljbiil/index.html
, but in wxt ,is return a url start with chrome :just like:
chrome-extension://aaonobiaachigcfphcipoljmkbiil/index.html,

What i missing ？ Any ideas？

### Reproduction

 redirectUri  should like : https://aaonobiaachigcfphciphdkoljbiil/index.html

### Steps to reproduce

pnpm dev

### System Info

```shell
Windows11,64.
Chrome.
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aiktb** [comment]
![image](https://github.com/user-attachments/assets/2ca613ac-bd1f-456a-8f49-e260e7b4b3f9)
`chrome-extension://*/*` is as expected.
I think this issue has nothing to do with WXT.

**Comment by ruhchjdbdbhccjjc** [comment]
Thanks for your reply !
You are right.
