### ISSUE TITLE
in firefox browser.tabs/browser.windows  is undefined

### ISSUE THREAD

**Issue by Jevin0** [wxt-dev/wxt#1294]
### Describe the bug

I created a `message.ts` file in the `devtools-panel` directory. But in `message.ts` I use `browser.tabs` or `browser.windows` and both objects are `undefined`. 

Since this is my first time writing an extension, I'm not sure if it's because of my code or `wxt`, please forgive me if I'm offended.

The following is a link to the specific code in the repository

### Reproduction

https://github.com/Jevin0/css-diff-devtools/blob/fe26f155ae68aa80327962f1dfe488f35577ddbb/entrypoints/devtools-panel/message.ts#L14

https://github.com/Jevin0/css-diff-devtools/blob/fe26f155ae68aa80327962f1dfe488f35577ddbb/entrypoints/devtools-panel/message.ts#L20

### Steps to reproduce

-  pnpm i
-  pnpm dev:firefox

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 8.45 GB / 31.86 GB
  Binaries:
    Node: 22.11.0 - ~\AppData\Local\Volta\tools\image\node\22.11.0\node.EXE
    Yarn: 1.22.22 - ~\AppData\Local\Volta\tools\image\yarn\1.22.22\bin\yarn.CMD
    npm: 10.9.0 - ~\AppData\Local\Volta\tools\image\node\22.11.0\npm.CMD
    pnpm: 9.14.1 - C:\Program Files\Volta\pnpm.EXE
  Browsers:
    Firefox: 133.0.3 (64x)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aiktb** [comment]
Try renaming to `entrypoints/devtools`

**Comment by Jevin0** [comment]
> Please refer to the following guide to debug your devtools extension in firefox:请参考以下指南在 Firefox 中调试您的 devtools 扩展： https://extensionworkshop.com/documentation/develop/debugging/#debugging-developer-tools-pages-and-panels
> 
> It seems that the permission control of firefox devtools is inconsistent with chrome.看来firefox devtools的权限控制和chrome不一致。 ![image](https://private-user-images.githubusercontent.com/104723527/397743747-5049d187-9231-4fac-9169-dd82d85eace0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTE2NTQsIm5iZiI6MTczNDg1MTM1NCwicGF0aCI6Ii8xMDQ3MjM1MjcvMzk3NzQzNzQ3LTUwNDlkMTg3LTkyMzEtNGZhYy05MTY5LWRkODJkODVlYWNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDlmYWU2YTlhYmZhNTlkMmMzNjQ2NjUzMDEwMjIxYWRlNmI2ZGNkYWYxZDBlNDYzNmQ0NzQwY2JkZGFkOTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2TOgv54zyeu8bR0aAJN4UQX3qKIOnJFknShoZMeysbU) ![image](https://private-user-images.githubusercontent.com/104723527/397744008-9d162e58-da91-41b4-bea1-b2ae2d7029d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTE2NTQsIm5iZiI6MTczNDg1MTM1NCwicGF0aCI6Ii8xMDQ3MjM1MjcvMzk3NzQ0MDA4LTlkMTYyZTU4LWRhOTEtNDFiNC1iZWExLWIyYWUyZDcwMjlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMlQwNzA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGEwN2Q4MWU4NDQyYzY2NzA4YjFiOGYyMzJkNTcwMjk5YTk4NDYyZWMzYTQ3MTQ5ZjcwNmQ3OTZjYzRhYzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QyFVXqwMtu12W7j7nJhGoxARBS2rUYpf1PahtExbW6w)
> 
> I tried adding tabs permissions, but it didn't work, so the only way to do it is through background transfer.我尝试添加选项卡权限，但没有成功，所以唯一的方法是通过后台传输。
> 
> Nothing to do with WXT, closing this.与WXT无关，关闭此。

Thank you.
