### ISSUE TITLE
Auto Permissions collect doesn't work for newtab page.  

### ISSUE THREAD

**Issue by Shramkoweb** [wxt-dev/wxt#1296]
### Describe the bug

I'm using `chrome.bookmarks` in /newtab folder with React. 
Permissions collect doesn't work  and generate - wrong permissions`  "permissions": [
    "tabs",
    "scripting"
  ]`. 
  
  Does it work for newtab ? Or i need to do it manually?

### Reproduction

1. create `newtab` with React
2. Use `chrome.bookmarks`
3. Auto generated Permissions incorrect in .output  manifest

### System Info

```shell
System:
    OS: macOS 15.2
    CPU: (14) arm64 Apple M3 Max
    Memory: 3.01 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.14.2 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.2
  npmPackages:
    wxt: ^0.19.13 => 0.19.22
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Dev mode adds additional permissions to enable hot reloading. Try a production build to see what your permissions really are.

**Comment by Shramkoweb** [comment]
> Dev mode adds additional permissions to enable hot reloading. Try a production build to see what your permissions really are.

It doesn't work. 

`{
  "manifest_version": 3,
  "name": "wxt-react-starter",
  "description": "manifest.json description",
  "version": "0.0.0",
  "icons": {
    "16": "icon/16.png",
    "32": "icon/32.png",
    "48": "icon/48.png",
    "96": "icon/96.png",
    "128": "icon/128.png"
  },
  "chrome_url_overrides": {
    "newtab": "newtab.html"
  }
}`

**Comment by aklinker1** [comment]
So to be clear, WXT does not automatically collect permissions. You have to add them yourself.

Did you see something that made you think WXT does this?

**Comment by Shramkoweb** [comment]
> So to be clear, WXT does not automatically collect permissions. You have to add them yourself.
> 
> Did you see something that made you think WXT does this?

Yes. For some reason, I thought so based on these theses in the documentation

1. In WXT, there is no manifest.json file in your source code. Instead, WXT generates it during the build process based on files in your project. [LINK](https://wxt.dev/guide/essentials/config/manifest.html)
2. The standard behavior of WXT in the `dev` mode was that it added `["tabs", "scripts"]` permissions itself, so I thought from these 2 points that the permissions are built automatically.

**Comment by Shramkoweb** [comment]
@aklinker1 I think we resolve my "issue" so we can close this issue. 

But I think maybe some more clear explain in documentation will be great idea 🤗

**Comment by aklinker1** [comment]
OK, I've also added a paragraph to explicitly describe how/when permissions are added: https://github.com/wxt-dev/wxt/commit/1a72a0cdc61fde6de7091c2db422c81203c9ba22
