### ISSUE TITLE
Upgrading or downgrading WXT version from package.json is taking by default current version of the WXT framework.

### ISSUE THREAD

**Issue by nishu-murmu** [wxt-dev/wxt#1301]
### Describe the bug

While looking into that windows terminal crash issue, I decided to downgraded WXT version from the current version to much older version than *0.19.19* but I faced this issue where I'm not able to downgrade the version.

Like in the loom video I've shared below I'm showing a demo extension that I'm working on, it has version **0.19.11**, then I decided to upgrade the version to **0.19.19**

### Reproduction

https://www.loom.com/share/97776b82c5ef44958c6ebd982ecb9e43?sid=e0c39be5-9c62-4f30-a9dd-afd64d094a90

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 1.85 GB / 7.84 GB
  Binaries:
    Node: 22.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.38 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (131.0.2903.86)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aiktb** [comment]
Do you use "^" in the version?

**Comment by nishu-murmu** [comment]
My bad.
I feel dumb 😭.

**Comment by nishu-murmu** [comment]
Learnt the importance of "^" and "~" in **package.json** today.
Always assumed that it would install that version😓 .
