### ISSUE TITLE
Is it possible to add a field to disable AutoLaunch?

### ISSUE THREAD

**Issue by code4you2021** [wxt-dev/wxt#135]
## Why add the disableAutoLaunch field?
```
disableAutoLaunch: true // Do not auto-open the browser
disableAutoLaunch: false // Auto open the Browser
```
For example: 
> https://github.com/aklinker1/vite-plugin-web-extension/blob/161921596f71f760a30d18a3a355de31f2bba97e/packages/vite-plugin-web-extension/src/index.ts#L19

---

I set disableAutoLaunch to true and manually loaded the chrome-mv3 directory for development so that I could easily debug the background.js

![shot0](https://github.com/wxt-dev/wxt/assets/83153991/03850dce-1db9-4df5-a86a-3b160ff7d8c5)

Currently using WXT, and I've encountered a debugging issue: `How to debug background.js?`

![shot1](https://github.com/wxt-dev/wxt/assets/83153991/d73524bc-8f56-4a69-83e8-26119e13711c)

**Comment by aklinker1** [comment]
@code4you2021 you need to enable dev mode in chrome to see the inspect view. You've done it in your personal profile, but not the blank profile that `web-ext` opens in by default.

I'll add this feature, because there are other cases where this is useful, but in your case, you just need to toggle the switch in the top right corner of `chrome://extensions`.

https://github.com/wxt-dev/wxt/assets/10101283/041b957f-3723-4c94-9665-91244506e3df

I'll look into seeing if it's possible to enable this setting by default when opening the browser from WXT.

**Comment by aklinker1** [comment]
Released in [`v0.6.6`](https://github.com/wxt-dev/wxt/releases/tag/v0.6.6). See #136 for how to disable opening the browser automatically.

**Comment by code4you2021** [comment]
@aklinker1 

I found a problem, when disable is true, the output folder is hidden.

Can it be a visible directory?

```
disable: true // out folder visible (output/chrome-mv3)
disable: false // out folder hidden (.output/chrome-mv3)
```

<img width="503" alt="" src="https://github.com/wxt-dev/wxt/assets/83153991/57507c06-71cc-4b68-bb3e-0db4a513dbd5">

<img width="676" alt="" src="https://github.com/wxt-dev/wxt/assets/83153991/5073e449-7dde-465d-a214-1c194416361a">

**Comment by aklinker1** [comment]
The output folder is visible in the output file list, regardless of `runner.disabled`.

#### `runner.disabled: false`

<img width="1142" alt="Screenshot 2023-09-30 at 9 42 27 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/095e9a0d-229d-4a59-b79e-f03871853a17">

#### `runner.disabled: true`

<img width="1151" alt="Screenshot 2023-09-30 at 9 44 31 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/9bee2bf7-8dfa-480f-8ccd-291a8614dfa9">

**Comment by aklinker1** [comment]
Oh, I see what you mean, it's a hidden directory that starts with a dot.

I think you're mistaken, it's always a hidden directory, regardless of `runner.disabled`. This directory is hard coded that way

I don't plan on making it a non-hidden directory.

If you have trouble opening the directory, most terminals will let you `ctrl+click` a directory to open it in the system file explorer. Editors also let you open a file's location in the system file explorer.

**Comment by code4you2021** [comment]
I'm sorry I didn't express myself very clearly

If `runner.disabled` is set to `true` and the `out` folder is hidden, chrome will not load the `out` folder.
![](https://github.com/wxt-dev/wxt/assets/83153991/7d200189-4237-4697-9342-bd700deaba87)

**Comment by aklinker1** [comment]
On Mac, `cmd+shift+.` will show hidden files.

https://github.com/wxt-dev/wxt/assets/10101283/ae60962a-56ce-4b4e-887c-cd2c98a4b6a5

You can also drag and drop the directory onto the `chrome://extensions`

https://github.com/wxt-dev/wxt/assets/10101283/4dea8cd4-98f1-4cf0-8410-af6a4e03d08a

**Comment by code4you2021** [comment]
Thanks.
