### ISSUE TITLE
TailwindCSS Example

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#171]
### Feature Request

Create an example for using TailwindCSS in the examples repo:

https://github.com/wxt-dev/wxt-examples

**Comment by aklinker1** [comment]
For now, see https://github.com/aklinker1/github-better-line-counts

**Comment by dvlden** [comment]
What kind of example are you looking for, to cover TailwindCSS usage?
I just followed the official Tailwind PostCSS implementation and it just works. 

Asking as I can see you have plans for many cool features, so maybe example(s) are something I can help with.

**Comment by aklinker1** [comment]
Yes, that is exactly it. Just follow the [postcss guide](https://tailwindcss.com/docs/installation/using-postcss) they provide, and it will work. But someone new to web development might not understand how to setup WXT and setup tailwind, it's hard when learning multiple new tech at once. So having an actual working code example for someone to reference might be worthwhile. Without knowing WXT uses Vite, or what Vite is, they might not realize it uses postcss.

I appreciate your offer for help! Let me sort out a good solution to documenting the examples better, and get your feedback on it to see if it's better. Then I'd appreciate any help you could provide!

**Comment by aklinker1** [comment]
New example setup is complete and available on the website: https://wxt.dev/examples.html

I'll add this example next.
