### ISSUE TITLE
Support custom output filename format

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [wxt-dev/wxt#177]
### Describe the bug

after changed `vite.rollupOptions.output.chunkFileNames`, manifest cannot get correct filename

### To Reproduce

[WOSHIZHAZHA120/6a97ab1d8fae3a62719c8e695586fe709398a94a](https://github.com/WOSHIZHAZHA120/6a97ab1d8fae3a62719c8e695586fe709398a94a)

1. Run build
2. Check output filename and manifest

### Expected behavior

Manifest file should get the correct new filename

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/52521836/3cf92d5e-a8e9-445f-a069-1eb6c82fdf60)
![image](https://github.com/wxt-dev/wxt/assets/52521836/31c4b367-624d-4291-b613-5559cf71f595)

### Environment

```
  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 19.15 GB / 31.75 GB
  Binaries:
    Node: 20.8.1 - ~\scoop\apps\nodejs\current\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.1.0 - ~\scoop\apps\nodejs\current\npm.CMD
    pnpm: 8.8.0 - ~\scoop\apps\nodejs\current\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.46)
    Internet Explorer: 11.0.22621.1
```

### Additional context

Add any other context about the problem here, otherwise you can delete this section.

**Comment by aklinker1** [comment]
This is intentional, why do you want to rename the output files?
