### ISSUE TITLE
createContentScriptIFrame API

### ISSUE THREAD

**Issue by molvqingtai** [wxt-dev/wxt#205]
### Feature Request

Currently, all WebExtension frameworks do not implement contentScript HMR. Perhaps this is the only solution that can achieve true HMR:

Inject an `iframe` into the page and load `content.html`.

You can refer to the following links for more information:

- [antfu/vitesse-webext](https://github.com/antfu/vitesse-webext/issues/139)
- [louisremi/vite-react-extension](https://github.com/louisremi/vite-react-extension/blob/chore/react-fork/src/contentScripts/index.ts)

Consider adding a `createContentScriptIFrame` API to implement contentScript HMR.

#### Is your feature request related to a bug?

N

### What are the alternatives?

N

### Additional context

N

**Comment by aklinker1** [comment]
@molvqingtai Great feature idea, thanks for the suggestion.

Would an API similar to [`createContentScriptUi`](https://wxt.dev/entrypoints/content-scripts.html#ui) be what you're looking for? It would include options for positioning and alignment.

**Comment by molvqingtai** [comment]
> @molvqingtai Great feature idea, thanks for the suggestion.
> 
> Would an API similar to [`createContentScriptUi`](https://wxt.dev/entrypoints/content-scripts.html#ui) be what you're looking for? It would include options for positioning and alignment.

I know createContentScriptUi, shadow can only be reload, and iframe can HMR.

**Comment by aklinker1** [comment]
Yes, it will use an iframe and include HMR. I'm gonna make the API similar to `creayeContentScriptUi`, with similar options.

**Comment by molvqingtai** [comment]
Awesome work！

**Comment by onlyfortesting** [comment]
> Released in [`v0.8.7`](https://github.com/wxt-dev/wxt/releases/tag/v0.8.7)!
> 
> I'll add more in-depth examples in the future, but for now, you can see it's usage here: https://wxt.dev/entrypoints/content-scripts.html#iframe

@aklinker1, I got `ReferenceError: createContentScriptIframe is not defined`. Looking at the dist files `createContentScriptIframe` doesn't seem to be exported. Can you verify this? Thank you.

**Comment by aklinker1** [comment]
@onlyfortesting It's in the generated docs, so yes, it's exported: https://wxt.dev/api/wxt/client/functions/createContentScriptIframe.html

It's exported from the `wxt/client` module, but is also available via auto-imports. Try running

```sh
pnpm install wxt@0.8.7 # or 0.9.0
pnpm wxt clean
pnpm wxt prepare
pnpm wxt dev
```

**Comment by onlyfortesting** [comment]
@aklinker1 For some reason, I thought I was running the latest version. It turns out it was 0.8.6. Sorry for the nuisance.

**Comment by aklinker1** [comment]
No worries! Glad you got it sorted 👍
