### ISSUE TITLE
Improve regex for manifest icons

### ISSUE THREAD

**Issue by dvlden** [wxt-dev/wxt#235]
### Feature Request

1. Allow plural directory or entirely swap singular possibility for plural option.
Current regex for directory:
`/^icon[\/\\]([0-9]+)\.(png|bmp|jpeg|jpg|ico|gif)$/`

I'd improve it with the optional `s` to allow plural dir name:
`/^icons?[\/\\]([0-9]+)\.(png|bmp|jpeg|jpg|ico|gif)$/`

2. Not sure why WXT supports all those file extensions or why, as `png` is the requirement for Chrome and I did not find anything related to Firefox. In the docs it states either `png` or `svg`.

So I'd simplify it a bit, unless you found something that I haven't in your research?
`/^icons?[\/\\]([0-9]+)\.png$/`

### What are the alternatives?

1. Define directory as singular
2. Manually define all icon sizes in the wxt.config for the manifest, because directory is plural

### Additional context

I'd be happy to do this simple task, and update the tests and docs.

**Comment by aklinker1** [comment]
Sure, feel free to add this!

I'm not sure why I added the other extensions as well lol. Probably had plans to transform them into png, or add auto-scaling. But I didn't end up doing that. 

https://github.com/wxt-dev/wxt/pull/72

**Comment by aklinker1** [comment]
Released in v0.10.0
