### ISSUE TITLE
contentScript sourceMap does not work

### ISSUE THREAD

**Issue by molvqingtai** [wxt-dev/wxt#236]
### Describe the bug

contentScript sourceMap does not work

### Expected behavior

It can be used at the tsx source file breakpoint

### Screenshots

![Screenshots](https://github.com/wxt-dev/wxt/assets/26295698/d7c335f8-dea3-42d0-9091-d5de98f720c0)

![image](https://github.com/wxt-dev/wxt/assets/26295698/f5d1c797-d825-43b2-be40-d4e8e43a5e47)

### Environment

```
  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 72.80 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    pnpm: 8.6.9 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Chrome Canary: 121.0.6127.0
    Safari: 17.0
  npmPackages:
    wxt: ^0.9.0 => 0.9.0

```

**Comment by aklinker1** [comment]
Thanks for reporting. As far as I know, this is a problem with Chrome, not WXT. I have another build tool, `vite-plugin-web-extension`, and it has the same problem: 

- https://github.com/aklinker1/vite-plugin-web-extension/issues/142
- https://github.com/aklinker1/vite-plugin-web-extension/issues/147

It works in Firefox, and this can be reproduced with any other bundler or project setup.

This [comment/thread](https://github.com/aklinker1/vite-plugin-web-extension/issues/147#issuecomment-1806234202) might help you out if you're trying to setup a debugger and break points

**Comment by aklinker1** [comment]
If anyone can make this work with a basic setup or different build tool, I would gladly implement the fix in WXT, because this is very annoying.

**Comment by lionelhorn** [comment]
@aklinker1 I'm not sure that it actually is an issue with chrome as I get proper line numbers and mapping with this plasmo example : https://github.com/PlasmoHQ/examples/tree/main/with-content-scripts-ui

<img width="487" alt="image" src="https://github.com/wxt-dev/wxt/assets/50528276/e146bf48-505e-41b5-a1a8-35fd3ef976fb">
<img width="392" alt="image" src="https://github.com/wxt-dev/wxt/assets/50528276/8c65439a-25a7-4bdc-9563-f8091c75d2df">

<img width="620" alt="image" src="https://github.com/wxt-dev/wxt/assets/50528276/2372ef02-77a0-4b4a-a21e-f7dae6206aef">

**Comment by lionelhorn** [comment]
Starting vite with

```ts
export default defineConfig({
  vite: () => ({
    plugins: [react()],
    mode: "development",
    build: {
      minify: false,
      sourcemap: "inline",
      terserOptions: {
        sourceMap: true,
        compress: false,
      },
      rollupOptions: {
        treeshake: false,
      }
    }
  }),
});
```

I get the following error message `(wxt:unimport plugin) Sourcemap is likely to be incorrect: a plugin (wxt:unimport) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
`

```shell
WXT 0.14.7                                                                                                                                             23:55:32
√ Started dev server @ http://localhost:3000                                                                                                           23:55:32
i Pre-rendering chrome-mv3 for development with Vite 5.0.12                                                                                            23:55:32
(wxt:unimport plugin) Sourcemap is likely to be incorrect: a plugin (wxt:unimport) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
(wxt:unimport plugin) Sourcemap is likely to be incorrect: a plugin (wxt:unimport) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
√ Built extension in 592 ms       
```

**Comment by lionelhorn** [comment]
CRXJS which also used vite plugins added this https://github.com/crxjs/chrome-extension-tools/pull/701

**Comment by aklinker1** [comment]
@lionelhorn After making the change in #381, I was able to get source maps working, but I needed to uncheck the "content scripts injected by extension" checkbox under the ignore list in devtools.

https://github.com/wxt-dev/wxt/assets/10101283/1496ca27-7389-4d79-98c6-8586d079ac13

Unfortunately, it resets when running `wxt` in dev mode by default. This can be mitigated by using a custom `runner.chromiumProfile` with the setting toggled. I can't figure out where this setting is stored or if it can be configured on startup or in new profiles...

**Comment by aklinker1** [comment]
Looks like it's a setting called `"skipContentScripts"`?

https://source.chromium.org/chromium/chromium/src/+/main:out/fuchsia-Debug/gen/third_party/devtools-frontend/src/front_end/panels/settings/settings.js;l=875;drc=b274bd7ace3a064c7fae27748b6d007068bbea30

**Comment by aklinker1** [comment]
Released some new changes to improve sourcemaps in [`v0.15.0`](https://github.com/wxt-dev/wxt/releases/tag/v0.15.0)

- #381 
- #382

**Comment by lionelhorn** [comment]
There are lots of command line flags in chromium
https://peter.sh/experiments/chromium-command-line-switches/

I'm not using the runner so your PR fixed the issue for me 👍 Thanks for the quick fix !

**Comment by aklinker1** [comment]
Found it! `devtools.synced_preferences_sync_disabled.skipContentScripts` under the `<profile>/Preferences` file.

I should be able to enable it automatically once my web-ext PR gets merged, or I add the change into my fork, `web-ext-runner`. It doesn't work for all preferences, but hopefully it will work for this one.
