### ISSUE TITLE
Add Firefox Sidebar support to the Side Panel Entrypoint

### ISSUE THREAD

**Issue by ddushok** [wxt-dev/wxt#248]
### Feature Request

[WXT documentation](https://wxt.dev/entrypoints/sidepanel.html) suggests only Chrome Side Panel is supported.  The same functionality exists in Firefox, but it is called [Sidebar](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Sidebars).  Adding Firefox Sidebar Support to the existing Side Panel Entrypoint would allow devs to create cross browser extensions using the sidepanel/sidebar.

#### Is your feature request related to a bug?

"N/A"

### What are the alternatives?

"N/A"

### Additional context

"N/A"

**Comment by aklinker1** [comment]
Firefox recently made lots of changes around MV3, so I'll add this back!

**Comment by aklinker1** [comment]
@ddushok After double checking, WXT already supports firefox sidepanels, the docs were wrong. They have been updated. Chrome MV2 is the only target that doesn't support sidepanels.
