### ISSUE TITLE
Setting the output directory

### ISSUE THREAD

**Issue by KnightYoshi** [wxt-dev/wxt#257]
Maybe I'm just blind, but I don't see a way to specify the output directory. I've tried setting the `build.outDir` in the vite config, but it always puts the compiled output in `.output`. Looking through the repo, everything seems to point to only `.output` 

 Is it not possible to set the output directory?

— side note, this is awesome. Working to migrate my extension from Webpack and WebExtension Toolbox — which was great on it's own — to Vite and this is a fantastic package and I'm looking forward to the publishing support

**Comment by aklinker1** [comment]
Released in [`v0.10.4`](https://github.com/wxt-dev/wxt/releases/tag/v0.10.4)

```ts
// wxt.config.ts
import { defineConfig } from 'wxt';

export default defineConfig({
  outDir: "dist",
});
```
