### ISSUE TITLE
defineUnlistedScript works with index.ts but not index.tsx

### ISSUE THREAD

**Issue by AndrewWalsh** [wxt-dev/wxt#271]
### Describe the bug

- Given an unlisted script directory, files named `index.ts` work as intended, but `index.tsx` does not. The guide says `entrypoints/<name>/index.[jt]sx?`

### To Reproduce

[test.zip](https://github.com/wxt-dev/wxt/files/13647280/test.zip)

1. Create a new project with `pnpx wxt@latest init test`
2. Select React, pnpm
3. Create a new directory under `entrypoints` called `test`
4. In `test` create an `index.tsx` file with the code below

```
export default defineUnlistedScript({
  main() {
    console.log('test');
  }
});
```

### Expected behavior

- `.output` contains a file named `test.js`, this doesn't happen
- It will work if you rename `index.tsx` to `index.ts`

**Comment by aklinker1** [comment]
Looks like the glob patterns are out of date. JS files are also ignored.

https://github.com/wxt-dev/wxt/blob/bcb93afe4e8c51ba98197f898d4294ce268c13de/src/core/utils/building/find-entrypoints.ts#L423-L424

It should look like:

https://github.com/wxt-dev/wxt/blob/bcb93afe4e8c51ba98197f898d4294ce268c13de/src/core/utils/building/find-entrypoints.ts#L408-L409

Feel free to open a PR, or I'll try and get to this soon.

**Comment by aklinker1** [comment]
Release in [`v0.11.2`](https://github.com/wxt-dev/wxt/releases/tag/v0.11.2)
