### ISSUE TITLE
Firefox is unable to open automatically.

### ISSUE THREAD

**Issue by asasas234** [wxt-dev/wxt#324]
When I run pnpm run dev:firefox, the Firefox browser does not automatically open and reports the following error.
```
 ERROR  connect ECONNREFUSED 127.0.0.1:61244                                                                                                                                                  10:30:21 PM

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1592:16)
  at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by aklinker1** [comment]
This is an issue with Firefox it seems, not `wxt` or `web-ext`. See https://github.com/mozilla/web-ext/issues/2975#issuecomment-1868209943

What version of firefox are you using?

**Comment by aklinker1** [comment]
Thanks for the update, I'll upgrade it.

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/v0.14.7
