### ISSUE TITLE
When creating a template, it is recommended to include a "Hello world" example with 1 test case.

### ISSUE THREAD

**Issue by asasas234** [wxt-dev/wxt#325]
### Feature Request
When creating a template, it is recommended to include a "Hello world" example with 1 test case.
I think this approach will make it convenient for people who are not familiar with vitest to quickly write unit tests. For example, in the Java Spring Boot framework, the initialization template will also come with a "hello world" unit test.

**Comment by aklinker1** [comment]
JS frameworks don't include tests in their templates. React, Vue, Vite, Nuxt, Nextjs, none of them include tests in their starter templates, so WXT doesn't either. I don't plan on adding any features to the templates either, they're supposed to be minimal.

The JS community seems to leave it up to individuals to create custom starter templates with custom combinations of tools, for example: https://github.com/antfu/vitesse

To add Vitest to a project, I've already written a small walkthrough in the testing example: https://github.com/wxt-dev/wxt-examples/tree/main/examples/vanilla-vitest#readme
