### ISSUE TITLE
Manifest extension version in config is ignored

### ISSUE THREAD

**Issue by GODrums** [wxt-dev/wxt#326]
### Describe the bug

When defining a `version` field in the `package.json` file but also defining a `version` in `wxt.config.ts`, the version from the config will not be the one used for the manifest. 
I'm not certain if this is intended behavior as the docs do not mention the version field in the manifest config explicitly, but it would be great to have everything needed for continued development configurable in one file (the overwritten manifest fields in `wxt.config.ts`). Otherwise removing the `version` field in the config may resolve such confusion as well

### To Reproduce

My repo [BetterBuff](https://github.com/GODrums/BetterBuff) currently has the described bug.

1. `package.json` uses version 1.0.0, while `wxt.config.ts` defines the version as 0.0.9
2. Run `pnpm build`
3. The deployed extension manifest define the version as 1.0.0 instead of 0.0.9

### Expected behavior

In the docs (https://wxt.dev/guide/manifest.html) it sounds like when overwritting a field in the `wxt.config.ts`, they will be directly reflected in the output manifest.

### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 16.19 GB / 31.21 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.0.18 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^5.0.10 => 5.0.10
    wxt: ^0.13.2 => 0.13.2
```

**Comment by aklinker1** [comment]
I recently updated this logic while re-writing unit tests and found some issues with it, so this should be fixed now.

> Here are the changes I made: https://github.com/wxt-dev/wxt/commit/b0eb7da9b4012f11e35580ee539156843e8f896d#diff-3e8cbeb9d99837959397a97a792be99577a364084c6fe599964d4e57315a5288

Can you try out `0.13.3`?

**Comment by GODrums** [comment]
Thank you for the fast response and fix. In `0.13.3` the version is gets correctly overwritten by the config.

I recently switched from the wxt vite plugin to the framwork and have been posively surprised about its improvements, great job on it!

**Comment by aklinker1** [comment]
Thanks! 😊
