### ISSUE TITLE
Support control the accessable of entry points

### ISSUE THREAD

**Issue by yunsii** [wxt-dev/wxt#330]
### Feature Request

It seems that all existed entry points must be build and released, I want to work with some of all entry points or make some entry points only accessable in specific env, how can I acheive this?

For instance, if an extention is too big, it is very helpful for controling the accessable of entry points in dev env.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

I have to rename the entry name.

**Comment by aklinker1** [comment]
Interesting idea, have you thought about what you'd want this to look like?

There are `include` and `exclude` options for entrypoints, but that only works for including and excluding entrypoints for specific browsers.

Right now, I'd recommend just renaming any entrypoints you don't want to run, putting a `.` in front of the name (`overlay.content/index.ts` &rarr; `.overlay.content/index.ts`). That should exclude them from being built.

**Comment by yunsii** [comment]
`include` and `exclude` type infer from `type TargetBrowser = string`, I think I do not known the specific acceptable value. And the rename approach is so inconvenience to cooperation obviously, Maybe add extra field `accessable` (boolean) like `include` and `exclude` to control the accessable?

**Comment by aklinker1** [comment]
It wouldn't do what you're asking, I just provided it as an example: https://wxt.dev/guide/multiple-browsers.html#customizing-entrypoints

If renaming is inconvinent, wouldn't a boolean also be inconvinent in a similar way? Both would involve a change to a version controlled file, or multiple version controlled files.

Would a CLI flag like `wxt -e popup` or `wxt --allow-entrypoint popup` be better? That way the change wouldn't be tracked in version control. CLI flags are also configurable through the `wxt.config.ts` file, so there would be a way to configure it all in one place as well, instead it spread accross multiple files.

```ts
import { defineConfig } from 'wxt';

export default defineConfig({
  allowedEntrypoints: ["popup", "options", ...],
});
```

What do you think of that?

**Comment by aklinker1** [comment]
Hmm, we could probably add types for it.

**Comment by yunsii** [comment]
Is the feature in the recent plan? We have to wait not short of time to develop only one entrypoint for now, because there are 10+ existing entrypoints 😂

**Comment by aklinker1** [comment]
I don't plan on working on this right now. My priority is everything required for v1.0 to be released.

It could be a good first issue though, if anyone is looking to contribute. To get started:

- You'll need to figure out how to add an array flag with [`cac`](https://www.npmjs.com/package/cac). Will likely go around here: 
   https://github.com/wxt-dev/wxt/blob/8c834835c453dcb49f8b44fa432203d83b902a81/src/cli.ts#L18-L38
- You'll need to add the new config field to the [`InlineConfig`](https://github.com/wxt-dev/wxt/blob/8c834835c453dcb49f8b44fa432203d83b902a81/src/types/external.ts#L9) and [`InternalConfig`](https://github.com/wxt-dev/wxt/blob/8c834835c453dcb49f8b44fa432203d83b902a81/src/types/internal.ts#L17) types.
- Once the types are added, you'll need to map the value from `InlineConfig` to `InternalConfig`, applying a default value, here:
   https://github.com/wxt-dev/wxt/blob/8c834835c453dcb49f8b44fa432203d83b902a81/src/core/utils/building/get-internal-config.ts#L99-L135
- Finally, you'll have to filter the entrypoints being built. You could do that in two places, not sure which one is better without putting more thought into it:
  - When finding the entrypoints:
     https://github.com/wxt-dev/wxt/blob/8c834835c453dcb49f8b44fa432203d83b902a81/src/core/utils/building/find-entrypoints.ts#L31
  - When performing the build:
     https://github.com/wxt-dev/wxt/blob/8c834835c453dcb49f8b44fa432203d83b902a81/src/core/utils/building/build-entrypoints.ts#L19

Let's not worry about adding types for this right now, and focus on adding just the functionality. I'll probably have to help setup the generated types.

**Comment by yunsii** [comment]
Cool, so detailed explaination, I think I can make a PR this weekend 😀

**Comment by yunsii** [comment]
> Edit: Maybe `-e | --filter-entrypoint` and `dev.filterEntrypoints` would be better names compared to `-e | --allow-entrypoint` and `allowedEntrypoints`?

My original goal is just control the accessable of the entrypoints, it can be environment agnostic, So `allowedEntrypoints` I think is better choice.

**Comment by yunsii** [comment]
@aklinker1 Hi, please review the draft PR and give me some feedback.

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/v0.14.2
