### ISSUE TITLE
web_accessible_resources not MV2 compliant for Firefox

### ISSUE THREAD

**Issue by dboyd13** [wxt-dev/wxt#340]
### web_accessible_resources not outputted MV2 compliant

When specifying the `web_accessible_resources` within `wxt.config.ts` the MV2 output is not compliant with the schema [Expected by Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources) (tested on FireFox `115.5.0` and WXT `0.14.0`)

```
Extension is invalid

Reading manifest: Error processing web_accessible_resources.0: Expected string instead of {"resources":["script.js"],"matches":["https://example.com/*"]}
```

### To Reproduce

1. Specify `web_accessible_resources` within `wxt.config.ts`

```
manifest: {
    name: 'Extension name',
    description: "Extension description",
    version_name: "0.0.1",
    content_scripts: [
      {
        matches: ["*://*.github.com/*"],
        js: ['content-script.js'],
        run_at: "document_end"
      }
    ],
    web_accessible_resources: [
      {
        "resources": ["script.js"],
        "matches": ["https://example.com/*"]
      }
    ],
    permissions: ["storage", "tabs"],
  }
});
```

1. Build extension (`wxt build -b firefox`)

1. Review the produced `manifest.json` file within `.output/firefox-mv2`, which has `web_accessible_resources` not aligned with Firefox [MV2 expectations](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources)

1. Verify that it's not accepted by attempting to load into Firefox, and receive the following error:

```
Extension is invalid

Reading manifest: Error processing web_accessible_resources.0: Expected string instead of {"resources":["script.js"],"matches":["https://example.com/*"]}
```

### Expected behavior

Produces a MV2 manifest where `web_accessible_resources` value is an array containing string(s).

### Environment

```
  System:
    OS: macOS 13.6.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 438.41 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Brave Browser: 117.1.58.124
    Chrome: 120.0.6099.216
    Firefox: 115.5.0
    Safari: 17.2.1
  npmPackages:
    wxt: ^0.14.0 => 0.14.0
```

**Comment by aklinker1** [comment]
Hey @dboyd13 thanks for opening an issue. The `manifest` option isn't anything special - whatever you put there gets output verbatim to the final manifest. Attempting to migrate MV3 options into MV2 or vise-versa isn't something I plan on supporting in WXT.

Instead, use a function and specify the different formats manually. Here's one example:

```ts
const baseManifest = {
  name: 'Extension name',
  description: "Extension description",
  version_name: "0.0.1",
  content_scripts: [
    {
      matches: ["*://*.github.com/*"],
      js: ['content-script.js'],
      run_at: "document_end"
    }
  ],
  permissions: ["storage", "tabs"],
}
const webAccessibleResources = [
  {
    "resources": ["script.js"],
    "matches": ["https://example.com/*"]
  }
];

export default defineConfig({
  manifest: ({ manifestVersion }) => ({
    ...baseManifest,
    web_accessible_resources: manfiestVersion === 3
      ? webAccessibleResources
      : webAccessibleResources.flatMap(entry => entry.resources),
  })
});
```

**Comment by dboyd13** [comment]
Thanks for this. Works well.

**Comment by aklinker1** [comment]
In [`v0.16.4`](https://github.com/wxt-dev/wxt/releases/tag/v0.16.4), I've added a feature to convert MV3 web_accessible_resources to MV2 when necessary. See #423 for an example, you don't need to use a function anymore for the `manifest` option.
