### ISSUE TITLE
Provide a way to reopen the browser

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [wxt-dev/wxt#348]
### Feature Request

Provides a way to reopen the browser. For example, Vite can be restarted using the `r` key.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

Restarted the wxt process but also trigger the build

### Additional context

**Comment by aklinker1** [comment]
We can listen for key presses like so: 

> ```
> let readline = require('readline');
> 
> readline.emitKeypressEvents(process.stdin);
> 
> process.stdin.on('keypress', (ch, key) => {
>   console.log('got "keypress"', ch, key);
>   if (key && key.ctrl && key.name == 'c') {
>     process.stdin.pause();
>   }
> });
> 
> process.stdin.setRawMode(true);
> ```
>
> &ndash; https://stackoverflow.com/questions/43286881/how-do-i-detect-whether-a-key-is-pressed-in-node-js#answer-74545520

Here's how Vite does it:

https://github.com/vitejs/vite/blob/bf1e9c2fd7b05f84d05e59f72b3fc26ca22807bb/packages/vite/src/node/shortcuts.ts

**Comment by aklinker1** [comment]
I like the idea of a few keyboard shortcuts for the dev server.

**Comment by aklinker1** [comment]
Released in [`v0.19.19](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.19)

**Comment by TimGuendel** [comment]
Pardon the intrusion, but does this work on windows? 😶 Nothing happens when I press o + enter 🤔

**Comment by royal430** [comment]
> Pardon the intrusion, but does this work on windows? 😶 Nothing happens when I press o + enter 🤔

me too

**Comment by aklinker1** [comment]
We ran into a ton of issues with windows and this feature... I don't have windows, so I can't debug any further. If either of you are willing to help out and open a PR fixing it, that would be great.
