### ISSUE TITLE
browser.runtime.getURL can not pass options.html with hash part

### ISSUE THREAD

**Issue by honwhy** [wxt-dev/wxt#349]
### browser.runtime.getURL can not pass options.html with hash part

With options.html developed by Vue (SPA)，it simply use hash as route path param. However, **wxt** generate `.wxt/types/path.d.ts` specify `browser.runtime.getURL` param's type to some strings, among them are `options.html`. So, when there pass hash part, it will prompt ts error, for example
```ts
Argument of type '`/options.html#/search?keyword=${string}&city=${string}`' is not assignable to parameter of type 'PublicPath'.ts(2345)
```

### To Reproduce
with content script,
```
export default defineContentScript({
  main() {
      const url = browser.runtime.getURL(
        `/options.html#/search?keyword=1`
     )
     window.open(url)
  },
})
```
with options.html, use vue & vue-router

**Comment by aklinker1** [comment]
Ah 🤦

**Comment by aklinker1** [comment]
Just need to add an override like so:

```diff
export interface WxtRuntime extends Runtime.Static {
  getURL(path: PublicPath): string;
+ getURL(path: `${PublicPath}${string}`): string;
}
```

Here: 

https://github.com/wxt-dev/wxt/blob/89d8ef9a508ff9b211ec457240ff5b3242497f63/src/core/utils/building/generate-wxt-dir.ts#L82-L84
