### ISSUE TITLE
[Reload the Extension] Self-registered shortcut without my consent 

### ISSUE THREAD

**Issue by dvlden** [wxt-dev/wxt#358]
### Describe the bug

Spent an hour figuring why it doesn't let me run my extension in dev mode. Saying "**Too many shortcuts specified for 'commands': The maximum is 4.**", while I have 4 inside of wxt config.

### To Reproduce

- Create four (4) commands with suggested keys
- Run `wxt`

### Expected behavior

Should work fine, cause limit is four (4). I did not consent to have the injected keyboard shortcut during development environment.

Later on, I noticed it and read about it in the [docs](https://wxt.dev/guide/development.html#reload-the-extension).

It's very useful, but lowers the suggested keys limit to three (3) during development. I am already used to clicking refresh in Extensions page, so I don't even want this, but... 

1. Can you instead inject a custom implementation of keyboard event listener that globally listens for the built-in keystroke, without using commands API?
2. Alternatively, make it enabled by default _(as it's useful)_ but allow it to be disabled through WXT config?

**Comment by aklinker1** [comment]
I'll add config to dlet you disable it.

**Comment by aklinker1** [comment]
I'll also not add it if there are already 4 shortcuts registered.

**Comment by aklinker1** [comment]
In the meantime, you can remove it via [`transformManifest`](https://wxt.dev/api/wxt/interfaces/InlineConfig.html#transformmanifest)

**Comment by aklinker1** [comment]
Both changes released in https://github.com/wxt-dev/wxt/releases/tag/v0.14.5
