### ISSUE TITLE
chromiumProfile  Not active

### ISSUE THREAD

**Issue by laozl** [wxt-dev/wxt#366]
### Describe the bug
I configured the chromiumProfile path accurately according to the documentation, but the program does not take effect.

### To Reproduce
``` 
runner: {
        binaries: {
            chrome: 'C:/Program Files/Google/Chrome/Application/chrome.exe',
        },
        startUrls: ['chrome://version/'],
        chromiumProfile: 'D:/ChromeUsers/DevTools/Default',
    },
```

### Expected behavior

Able to make the specified path effective

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/43659166/92c0e562-b8d0-433c-a8aa-b06cf9dd9380)

### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 13.54 GB / 23.82 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    wxt: ^0.14.0 => 0.14.5

```

**Comment by aklinker1** [comment]
I believe `web-ext` (package used to open browser) copies the profile into a temp directory so any changes you make during development, like installing a test version of your extension, doesn't affect your actual profile when you open it back up again.

So things like login state aren't persisted when opening the browser in dev mode, but other installed extensions show show up.

If you want to use your real profile, set `runner.enabled: false`, and install it manually in your actual profile.

**Comment by StyleT** [comment]
I still have this issue with `WXT 0.17.7` and here is a workaround:

```typescript
import * as path from 'path';
import {defineConfig} from 'wxt';

// See https://wxt.dev/api/config.html
export default defineConfig({
  runner: {
    chromiumArgs: [
      '--auto-open-devtools-for-tabs',
      `--user-data-dir=${path.join(__dirname, '.browser-profiles/chromium')}`,
      '--hide-crash-restore-bubble',
    ],
  },
});


```

**Comment by aklinker1** [comment]
Yes! I found out that `--user-data-dir` solves this problem a few weeks ago as well! I forgot about this issue, sorry I didn't share an update
