### ISSUE TITLE
Build errors when leveraging `wxt/storage`: `You must add the 'storage' permission to your manifest to use 'wxt/storage'`

### ISSUE THREAD

**Issue by kboucher** [wxt-dev/wxt#371]
### Describe the bug

Build error when attempting to utilize the `wxt/storage` module: `Error: You must add the 'storage' permission to your manifest to use 'wxt/storage'` (even after adding `storage` to `manifest.permissions` in `wxt.config.ts`).

### To Reproduce

I am not including the prescribed _minimal reproduction_ because the steps to reproduce are enough to encounter the problem, and because I already have the solution. However, I thought posting this issue might be helpful to others who may encounter this problem.

Steps to reproduce the bug:

* Create a new WXT project
* Run `yarn dev`
* Import `wxt/storage` module into background.ts: `import { storage } from "wxt/storage";`
* Define storage item in background.ts (**outside of `defineBackground`**)
```
  import { storage } from "wxt/storage";

  const isBugStorageItem = storage.defineItem<boolean>(
    "local:isBug",
    {
      defaultValue: false,
    },
  );

  export default defineBackground(() => {
    /* ...other stuff here... */
  });
```
* Stop and start dev server
* Observe build error: `Error: You must add the 'storage' permission to your manifest to use 'wxt/storage'`
* Add `storage` permission to `wxt.config.ts` manifest section:
```
  manifest: {
    permissions: [
      "storage",
    ],
  },
```
* Start dev server
* Observe build error: `Error: You must add the 'storage' permission to your manifest to use 'wxt/storage'`

### Expected behavior

A successful build is expected after adding the `storage` permission to the manifest.

### Solution

As mentioned above this problem is encountered when attempting to reference `storage` from outside of the `defineBackground` definition object.

_Note: I did not encounter this problem when referencing `storage` outside of React modules (Ex: In `content`, `popup`, or `sidepanel` entrypoints.)_

So, to be explicit, moving the reference to `storage` into the body of the `defineBackground` definition object solved this issue:

```
export default defineBackground(() => {
  const isBugStorageItem = storage.defineItem<boolean>(
    "local:isBug",
    {
      defaultValue: false,
    },
  );
  
  /* ...other stuff here... */
});
```

**Comment by aklinker1** [comment]
Thanks for the report! You can move the storage definition to another file and it will work.

Basically, you can't run any code outside the main function of the entrypoint files. Related to #336, see it for more details.

**Comment by aklinker1** [comment]
The entrypoint is imported during the build process in a node environment, but it doesn't know that. It sees that `chrome.storage` is undefined, so it thinks you're missing the storage permission.

**Comment by aklinker1** [comment]
I'm gonna close this as a duplicate, but I improved the error message.

<img width="843" alt="Screenshot 2024-01-27 at 12 19 48 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/f819a095-8b63-417b-8acb-5e5ed7a3c7e5">

**Comment by aklinker1** [comment]
Released error message improvements in https://github.com/wxt-dev/wxt/releases/tag/v0.14.7

**Comment by kboucher** [comment]
> I'm gonna close this as a duplicate, but I improved the error message.
> 
> 
> 
> <img width="843" alt="Screenshot 2024-01-27 at 12 19 48 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/f819a095-8b63-417b-8acb-5e5ed7a3c7e5">
> 
> 

Awesome. Thanks!

**Comment by FJRG2007** [comment]
@aklinker1 Hi, today I noticed that my extension suddenly displayed this error. What can I do?

<img width="536" height="247" alt="Image" src="https://github.com/user-attachments/assets/f9e2b3ee-4e48-4ae8-988e-61c98b4c0ae6" />

**Comment by aklinker1** [comment]
@FJRG2007 Looks like this is being reported at runtime? Are you trying to use it in a `main` world content script or some other context without access to the extension APIs?

**Comment by FJRG2007** [comment]
Now that I think about it, it could be because it might be injecting itself into code on the web. I'll check it later to see if that's the case or if it's something else.

**Comment by Blon168** [comment]
@FJRG2007 @aklinker1 
Same one issue.
\entrypoints\background\index.ts

<img width="864" height="264" alt="Image" src="https://github.com/user-attachments/assets/94da7569-4667-4f19-ac7a-82a5ed77ef4e" />

but **after build background.js** is

<img width="1485" height="216" alt="Image" src="https://github.com/user-attachments/assets/1aef5181-f39f-4826-9ae8-ac2683138620" />

**Comment by aklinker1** [comment]
@Blon168 Yes, the error message is included in the bundle. Are you seeing an error at runtime or somewhere else?

**Comment by Blon168** [comment]
> [@Blon168](https://github.com/Blon168) Yes, the error message is included in the bundle. Are you seeing an error at runtime or somewhere else?

in background.js after build.

**Comment by aklinker1** [comment]
@Blon168 Can you create a new issue with a reproduction for me to look into? Hard to help in this case if I can't see your full codebase.

**Comment by Blon168** [comment]
> [@Blon168](https://github.com/Blon168) Can you create a new issue with a reproduction for me to look into? Hard to help in this case if I can't see your full codebase.

Yes, done https://github.com/wxt-dev/wxt/issues/2203
