### ISSUE TITLE
permissions and host_permissions auto-collecting

### ISSUE THREAD

**Issue by honwhy** [wxt-dev/wxt#379]
### permissions and host_permissions auto-collecting

In defineContentScript or defineBackgound, excel from matches which is auto collecting into manifest.content_scripts[i].matches, how about define another keys permission, host_permissions, and auto collect them and deduplicate so as to generate manifest.permissions or host_permissions in mv3 style.
#### Is your feature request related to a bug?

"N/A"

### What are the alternatives?

alternative solutions, is defined permissions, host_persmissions and web_accessible_resources according to mv2 or mv3 request.

### Additional context

ex,
```
export default defineContentScript({
  matches: ['https://*.blog.csdn.net/**'],
  permission: [],
  host_permissions: [],
  main(ctx) {
   ...
  },
})
```

**Comment by aklinker1** [comment]
Closing in favor of #544, which includes these fields and others.
