### ISSUE TITLE
Tailwind changes no longer detected

### ISSUE THREAD

**Issue by dvlden** [wxt-dev/wxt#386]
### Describe the bug

It's like it suddenly stopped working and it became a really painful DX. I am not really certain when did this happen, but I've been developing some new features on another branch, with so much time waste and pain. Every time I make some style changes, I must restart WXT in order to see them. Reloading the extension does not work either. Previously, this behaviour was only when I made changes in entry file `popup/index.html` for example, but now it is happening in all files.

### To Reproduce

Will update issue once I figure out what the problem is.

1. Pending...

### Expected behavior

Should take effect once file is saved.

### Video recording

[Video recording](https://github.com/wxt-dev/wxt/assets/3460368/8eb6b564-95a0-4110-8c7f-ba6100ca3a4a)

### Environment

```

  System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 55.40 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.asdf/installs/nodejs/21.2.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.14.3 - /opt/homebrew/bin/pnpm
    bun: 1.0.21 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 121.1.62.153
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.83
    Firefox Nightly: 124.0a1
    Safari: 17.2.1
    Safari Technology Preview: 17.4
  npmPackages:
    wxt: ^0.13.0 => 0.13.5

```

### Additional context

I tested the TW example, saw it's broken, but HMR works. Going to fix the template and then hunt down why it isn't working for me anymore.

**Comment by aklinker1** [comment]
I see you're working on the reproduction, but I just wanted to say, I like the gradient border and logo you've got, it looks very crisp 😎

**Comment by dvlden** [comment]
> I see you're working on the reproduction, but I just wanted to say, I like the gradient border and logo you've got, it looks very crisp 😎

Yeah, I am trying to reproduce on my own project. Go back a handful of commits to the point where it worked and then see how/where could I fu*k it up. 

Thanks, we could probably use something similar for WXT examples too. 💯

**Comment by aklinker1** [comment]
From what I can tell looking at the example, the tailwind CSS file doesn't contain all the classes, just the ones present at build time. This is the usual behavior for production, obviously we want to strip out all the classes that aren't used, but in development, I thought tailwind's CSS file was populated with all it's classes...

**Comment by aklinker1** [comment]
OK, so the problem is that when we render the HTML file to the file system (so that Chrome doesn't say "ERR can't find popup.html for action.default_popup" while loading the extension), the assets should be loaded from localhost, not from the extension's directory.

This is because the code WXT uses to load ignores TSConfig path aliases 🤦 . The condition on line 60 is just looking for relative paths, and doesn't work with something like `~/assets/tailwind.css` 🤦 

https://github.com/wxt-dev/wxt/blob/9cee9eefb407dd5a1294b78e97b1ccf3712e8c15/src/core/builders/vite/plugins/devHtmlPrerender.ts#L50-L68

**Comment by aklinker1** [comment]
In the example:

| With `~/assets/main.css` | With `../../assets/main.css` | 
| --- | --- | 
| <img width="522" alt="Screenshot 2024-01-29 at 4 43 56 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/7e182f66-08df-4128-b979-6a7020ed4de1"> | <img width="558" alt="Screenshot 2024-01-29 at 4 43 33 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/2c488f83-037e-4fee-a2b5-493b06da680f"> |

**Comment by aklinker1** [comment]
To fix this:

1. In `wxt/src/core/builders/vite/plugins/devHtmlPrerender.ts`, we need to grab the `resolve.alias` option from the [configResolved hook](https://vitejs.dev/guide/api-plugin.html#configresolved) and store it in a varaible.
2. Then, in the `pointToDevServer` in the same file, we need to attempt to resolve the path using the aliases. I don't know how to do this off the top of my head? Maybe `@rollup/plugin-alias` (the plugin vite uses to make it's `resolve.alias` work) provides a helper function we can use? Or we can just do simple `str.replace`? Like I said, not sure.

**Comment by dvlden** [comment]
Yeah, I am at that point now. Just looking at `~/assets/app.css` in my codebase.
I'm sorry, I do not follow the codebase snippet from above.

How the heck did you figure this so quickly? I went 30 commit behind, thinking it could be the src/public directory changes in the config.

**Comment by dvlden** [comment]
Given the input, I'll try to add make this and see if it works. 
I read it once, sounds simple, I read it twice, sounds complex. But I'll give it a shot.

If I fail, I'll simply wait for your solution. No rush. I developed for over a week with no tailwind styles being applied 🤣

**Comment by dvlden** [comment]
You already have aliases in the config argument:

```ts
    alias: {
      '@': '/Users/nn/Projects/Personal/ultrawideo-v3/src',
      '~': '/Users/nn/Projects/Personal/ultrawideo-v3/src',
      '@@': '/Users/nn/Projects/Personal/ultrawideo-v3',
      '~~': '/Users/nn/Projects/Personal/ultrawideo-v3'
    },
```

Identical to the ones from the `configResolved` hook:
```ts
    {
      find: '@',
      replacement: '/Users/nn/Projects/Personal/ultrawideo-v3/src'
    },
    {
      find: '~',
      replacement: '/Users/nn/Projects/Personal/ultrawideo-v3/src'
    },
    {
      find: '@@',
      replacement: '/Users/nn/Projects/Personal/ultrawideo-v3'
    },
    {
      find: '~~',
      replacement: '/Users/nn/Projects/Personal/ultrawideo-v3'
    },
```

So unless we also need those for something:
```ts
    {
      find: 'webextension-polyfill',
      replacement: '/Users/nn/Projects/Personal/ultrawideo-v3/browser.ts'
    },
    {
      find: '@wxt/reload-html',
      replacement: '/Users/nn/Projects/Personal/ultrawideo-v3/node_modules/wxt/dist/virtual/reload-html.js'
    },
    {
      find: /^\/?@vite\/env/,
      replacement: '/@fs/Users/nn/Projects/dvlden-wxt/node_modules/.pnpm/vite@5.0.12_@types+node@20.10.3_sass@1.69.5/node_modules/vite/dist/client/env.mjs'
    },
    {
      find: /^\/?@vite\/client/,
      replacement: '/@fs/Users/nn/Projects/dvlden-wxt/node_modules/.pnpm/vite@5.0.12_@types+node@20.10.3_sass@1.69.5/node_modules/vite/dist/client/client.mjs'
    }
```

I'll assume we can use `config.alias` object instead? So sounds like we need just another condition that checks for alias? Will test this now.

**Comment by aklinker1** [comment]
Yeah, using InternalConfig.alias should be fine... If anyone wants to add custom aliases, that's where they would add it.

**Comment by aklinker1** [comment]
Yeah, using InternalConfig.alias should be fine... If anyone wants to add custom aliases, that's where they would add it.

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/v0.15.2
