### ISSUE TITLE
Dev server doesn't watch for changes in html files in `vanilla-devtools` example

### ISSUE THREAD

**Issue by lionelhorn** [wxt-dev/wxt#388]
### Describe the bug

Dev server doesn't watch html files changes

### Expected behavior

Changes in  `examples/vanilla-devtools/entrypoints/devtools-panel/index.html`  to be detected without having to restart server.

### To Reproduce

1. Clone [examples](https://github.com/wxt-dev/wxt-examples) repo
2. Install deps
3. Start dev server in `examples/vanilla-devtools`
4. Modify `examples/vanilla-devtools/entrypoints/devtools-panel/index.html`  

### Screenshots
https://github.com/wxt-dev/wxt/assets/50528276/c435272e-90ce-424c-96bc-c62df7d81fa6

### Environment
```
  System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 33.11 GB / 63.15 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.83)
```

**Comment by aklinker1** [comment]
Thanks for the report, I'll try and look into this sometime soon.

**Comment by aklinker1** [comment]
Alright, I've found the problem. Updated the issue title.

**Comment by aklinker1** [comment]
Alright, I've found the problem.

https://github.com/wxt-dev/wxt/blob/ddbc66813efe4d7440bb1cedb77ec0312bed3808/src/core/utils/building/detect-dev-changes.ts#L128

This line expects `changedPath = "/some/path/to/entrypoints/devtools-panel.html` and `chunk.fileName = "devtools-panel.html"`. If that were the case, it would correctly reload the page. However, `changedPath` is actually `"/some/path/to/entrypoints/devtools-panel/index.html"`, so the `.endsWith` doesn't work as expected.

```ts
"/some/path/to/entrypoints/devtools-panel/index.html".endsWith("devtools-panel.html") // false
```

A quick fix:

```diff
-    (chunk.type === 'asset' && changedPath.endsWith(chunk.fileName)) ||
+    (chunk.type === 'asset' && changedPath.replace("/index.html", ".html").endsWith(chunk.fileName)) ||
```
