### ISSUE TITLE
ESLint / Prettier / TypeCheck / Vite Plugins in general

### ISSUE THREAD

**Issue by Timeraa** [wxt-dev/wxt#405]
This is more of a question / feature task. Ideally I would like to utilize ESLint, TypeScript Typechecking and Prettier when developing a browser extension. Using something like `vite-plugin-checker` is what I use in most Vite projects for this task but with how the entry points work it would start said task for each entry point. 

I also utilize a small helper function to generate the `_locales` folder which downloads strings from my project's API and writes them into the file, I used to have a Vite plugin for that which ran it on `buildStart` which now would be called multiple times but it also didn't work because I think WXT checks if there's a _locales folder before startup.

**Comment by aklinker1** [comment]
> I also utilize a small helper function to generate the _locales folder which downloads strings from my project's API and writes them into the file, I used to have a Vite plugin for that which ran it on buildStart which now would be called multiple times but it also didn't work because I think WXT checks if there's a _locales folder before startup.

I could add hooks for this, outside vite. Similar to nuxt's build hooks. Been hesitant to do this, since it's a large undertacking lol.

> This is more of a question / feature task. Ideally I would like to utilize ESLint, TypeScript Typechecking and Prettier when developing a browser extension. Using something like `vite-plugin-checker` is what I use in most Vite projects for this task but with how the entry points work it would start said task for each entry point.

I use prettier, eslint, and Typescript on some projects and don't have any issues, but I don't run them before/during dev or build, which I assume you're doing if you're with `vite-plugin-checker`.

But that said, since there aren't any hooks, there isn't an equivalent to that plugin. I'll open a separate issue around adding some basic build hooks.

**Comment by Timeraa** [comment]
> > I also utilize a small helper function to generate the _locales folder which downloads strings from my project's API and writes them into the file, I used to have a Vite plugin for that which ran it on buildStart which now would be called multiple times but it also didn't work because I think WXT checks if there's a _locales folder before startup.
> 
> I could add hooks for this, outside vite. Similar to nuxt's build hooks. Been hesitant to do this, since it's a large undertacking lol.
> 
> > This is more of a question / feature task. Ideally I would like to utilize ESLint, TypeScript Typechecking and Prettier when developing a browser extension. Using something like `vite-plugin-checker` is what I use in most Vite projects for this task but with how the entry points work it would start said task for each entry point.
> 
> I use prettier, eslint, and Typescript on some projects and don't have any issues, but I don't run them before/during dev or build, which I assume you're doing if you're with `vite-plugin-checker`.
> 
> But that said, since there aren't any hooks, there isn't an equivalent to that plugin. I'll open a separate issue around adding some basic build hooks.

Yeah `vite-plugin-checker` runs during compilation / dev mode, it does work just runs like 5 tasks for my project plus clears the console haha

**Comment by aklinker1** [comment]
Released hooks in [`v0.16.3`](https://github.com/wxt-dev/wxt/releases/tag/v0.16.3)
