### ISSUE TITLE
Auto detection of `new URL(...)`  calls from third party code for external assets bundling

### ISSUE THREAD

**Issue by lionelhorn** [wxt-dev/wxt#417]
First let me thank you for your reactivity and handling of my previouses reports! :)

### Description
Most probably not a bug. Maybe more a feature request/question.

### To Reproduce

I reused the code you gave in https://github.com/wxt-dev/wxt/issues/392#issuecomment-1925456421

Made a different branch: https://github.com/lionelhorn/wxt-wasm-vlcn-repro/tree/missing-assets-bundle

And modifed a bit
<img width="320" alt="image" src="https://github.com/wxt-dev/wxt/assets/50528276/4cb6e1c4-bf40-4831-8d44-81c12c82dd91">

If I remove the `() => wasmUrl` param. A different code path will be taken here:

```ts
  async function ui(h) {
    if (Pt != null) return Pt;
    const s = await te({
      locateFile(c) {
        return h ? h(c) : new URL("crsqlite.wasm", self.location.href).href;
      }
    }), n = Us(s);
    return n.vfs_register(new Xs("idb-batch-atomic", { durability: "relaxed" })), Pt = new ci(n), Pt;
  }
 ```
 
The last part of the ternary will be called
` new URL("crsqlite.wasm", self.location.href).href`

And will result in a missing asset `crsqlite.wasm` that will not be automatically detected and added to the output.

https://github.com/lionelhorn/wxt-wasm-vlcn-repro/blob/42340f75e0757a9cba9f74a7a7e5559861b14727/.output/chrome-mv3/background.js#L3597-L3605

### Wished behavior
Calls to `new URL("asset")` to be picked up with WXT and automatically outputted as a file in the output (deduplicated if possible)

**Comment by aklinker1** [comment]
Unfortunately I don't know the best way to discover which file to copy to the output directory.... Are these URLs for project files, node modules, etc?

How would I know to copy `node-modules/iforgotthemodulename/crsqlite.wasm` when we see `new URL("crsqlite.wasm", self.location.href).href`?

I could obviously search all project files, but if we include node_modules, that's gonna take a long time and slow things down...

I'm going to be adding hooks soon. As an alternative, you could add a post-build hook that copies the wasm to the correct location as expected by the module. Or copy it and pass a custom function using `browser.runtime.getURL` to get the known url.

**Comment by lionelhorn** [comment]
I see what you mean.

Hooks would enable manual copy of assets post build. That would be a good solution.

**Comment by aklinker1** [comment]
Released hooks in [`v0.16.3`](https://github.com/wxt-dev/wxt/releases/tag/v0.16.3)

**Comment by lionelhorn** [comment]
@aklinker1 

Using my projet mentionned in first post I was able to use

```ts
  hooks: {
    build: {
      async done() {
        await copyFile("../../node_modules/@vlcn.io/crsqlite-wasm/dist/crsqlite.wasm", "./.output/chrome-mv3/crsqlite.wasm");
      }
    }
  },
  ```
  Would it be possible to get some context passed to the function handler for the hook?
Like 
```
async done(ctx: BuildContext)
```

With context like the current build output path?
As that would change depending of browser target (chome, firefox etc.)

**Comment by aklinker1** [comment]
@lionelhorn the first parameter is already exactly what you're looking for.

```ts
async done(wxt) {
  await copyFile(
    resolve(wxt.config.root, "node_modules/@vlcn.io/crsqlite-wasm/dist/crsqlite.wasm"),
    resolve(wxt.config.outDir, "crsqlite.wasm"),
  );
}
```

**Comment by lionelhorn** [comment]
My bad. Didn't get any params for done() on intellisense. Wrongly assumed they weren't any params.

**Comment by aklinker1** [comment]
No worries!
