### ISSUE TITLE
Content Script not getting added to manifest

### ISSUE THREAD

**Issue by michaelkasper** [wxt-dev/wxt#434]
### Describe the bug
I’m following the directions best I can, but the content-script never gets added to the manifest.

not sure if their is a better example. Followed the ShadowRoot react option . Have also tried the vanilla option.

On Mac chrome using NPM and node 20.

**Comment by aklinker1** [comment]
Here's a minimal example that loads a content script: [wxt-issue-434.zip](https://github.com/wxt-dev/wxt/files/14213895/wxt-issue-434.zip)

```sh
npm install
npm run dev
```

Note that during development, content scripts are registered and reloaded at runtime using the `chrome.scripting` API. So they don't show up int he output manifest. Once you do a build, `wxt build`, the manifest will contain the content scripts:

<details>
<summary>Dev Manifest</summary>

```json
{
  "manifest_version": 3,
  "name": "wxt-starter",
  "description": "manifest.json description",
  "version": "0.0.0",
  "commands": {
    "wxt:reload-extension": {
      "description": "Reload the extension during development",
      "suggested_key": {
        "default": "Alt+R"
      }
    }
  },
  "background": {
    "service_worker": "background.js"
  },
  "host_permissions": [
    "<all_urls>",
    "http://localhost/*"
  ],
  "content_security_policy": {
    "extension_pages": "script-src 'self' 'wasm-unsafe-eval' http://localhost:3000; object-src 'self';"
  },
  "permissions": [
    "tabs",
    "scripting"
  ]
}
```

</details>

<details>
<summary>Prod Manifest</summary>

```json
{
  "manifest_version": 3,
  "name": "wxt-starter",
  "description": "manifest.json description",
  "version": "0.0.0",
  "content_scripts": [
    { "matches": ["<all_urls>"], "js": ["content-scripts/content.js"] }
  ]
}
```

</details>

**Comment by aklinker1** [comment]
If that doesn't help, provide a reproduction or the code you're using, I can't help if you don't tell me anything about your setup.

**Comment by michaelkasper** [comment]
@aklinker1 thanks! thats what i needed. Just needed a solid example. Its also good to know that the manifest will only show the content-scripts when you build. Dont think i saw anything about that in the docs, just examples of what the content-script section will look like in the manifest. It also might be helpful to other to add that example to the example repo, i couldn't find a content-script example in their.

Thanks for the help!

**Comment by aklinker1** [comment]
I'll add an example. Can you tell what you were doing wrong? Anything I can do to improve the docs in the meantime?

**Comment by michaelkasper** [comment]
I think my initial issue was i was following this [example](https://wxt.dev/guide/content-script-ui.html#shadow-root) but not understanding all the props it uses. Because the example is only a snippet its hard to fully connect what anchor does/means.   I had left it as `#anchor` assuming that was a default and it should work out of the box. 

When i didnt see anything on chrome after starting the dev env i looked at the manifest to see if my stuff compiled right. Not seeing the manifest as the docs described took me down a rabbits hole.

I think the take aways is the complete working example and adding a note to the examples of what the manifest would render too when building and that running dev would result in a different manifest.

**Comment by aklinker1** [comment]
I've added the react content script ui example: https://wxt.dev/examples.html

**Comment by wywppkd** [comment]
So why aren't the content scripts automatically added when running `npm run dev`? This is inconsistent with the `build` mode, and there is no hint about this in the documentation
