### ISSUE TITLE
Automatically disable "Show warning about Self-XSS when pasing code" in new chrome

### ISSUE THREAD

**Issue by aaronklinker-st** [wxt-dev/wxt#435]
### Feature Request

New versions of chrome require you to type "allow pasting" before pasting code into the dev console. Can we disable that automatically for new profiles created by `web-ext` when running in dev mode?

WXT recently did a similar change in #382. I don't know what the profile flag is for JSON.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

N/A

### Additional context

- https://stackoverflow.com/questions/77587864/disable-paste-protection-in-chrome-devtools

<img width="809" alt="Screenshot 2024-02-09 at 9 46 35 AM" src="https://github.com/wxt-dev/wxt/assets/92738025/c91a5738-ba51-4477-9404-cc617f0e2507">

**Comment by aaronklinker-st** [comment]
Looks like the chromium source code might have a setting to disable it? 

https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/panels/console/ConsoleView.ts;l=447-448;drc=b22c7711886858bf6bbf4fe69a6ecdbc6cb28ea8

```js
    this.selfXssWarningDisabledSetting = Common.Settings.Settings.instance().createSetting(
        'disable-self-xss-warning', false, Common.Settings.SettingStorageType.Synced);
```

Doesn't show up in my profiles preferences file though...

**Comment by aaronklinker-st** [comment]
There is a `--no-experiments` flag: https://peter.sh/experiments/chromium-command-line-switches/#no-experiments

Maybe that would help?

Edit: Nope, didn't disable the devtools experiments.

**Comment by aaronklinker-st** [comment]
Looks like the only option is to create a custom profile and list it in `~/web-ext.config.ts` file.

**Comment by rxliuli** [comment]
I found a useful parameter `--unsafely-disable-devtools-self-xss-warnings`, and I will try to submit a PR to address it.
