### ISSUE TITLE
I get a typescript error in defineContentScript

### ISSUE THREAD

**Issue by ddeisadze** [wxt-dev/wxt#444]
See image. I do have a yarn mono repo. I used react template

This is the error: `The inferred type of 'default' cannot be named without a reference to '../../node_modules/wxt/dist/index-TYmXqKVq'. This is likely not portable. A type annotation is necessary.ts(2742)
`

<img width="609" alt="image" src="https://github.com/wxt-dev/wxt/assets/1585369/acf043b1-361c-4fb4-a5ff-73a12d7b4c8d">

**Comment by aklinker1** [comment]
Please provide a minimal reproduction. It can be a zip file of a simple monorepo.

**Comment by ddeisadze** [comment]
@aklinker1 looks like if I remove "composite: true" (because I have a monorepo) from tsconfig the error goes away

**Comment by aklinker1** [comment]
Hmm, I need to do more research into what composite and this error message means. I've never had to use composite for monorepos, but I bet there's a reason to enable it...
