### ISSUE TITLE
If i add ChromiumArgs to save user data, dev server crashes

### ISSUE THREAD

**Issue by ddeisadze** [wxt-dev/wxt#446]
### Describe the bug

I am trying to preserve cookies, cache, and any other data so i don't have to authenticate, etc during development.

Dev server crashes with the message, only if i add the following command to: 	`chromiumArgs: ['--user-data-dir=./.dev-profile'],` to defineRunnerConfig

```
ERROR  connect ECONNREFUSED 127.0.0.1:52123                                                  9:53:31 PM

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```
### To Reproduce

Share minimal reproduction. Examples of a minimal reproduction:

Add this to web-ext.config.ts

```
export default defineRunnerConfig({
	startUrls: [
		'https://www.capitalonecareers.com/search-jobs',
		'chrome://extensions/',
	],
	chromiumArgs: ['--user-data-dir=./.dev-profile'],
	openConsole: true,
	openDevtools: true,
});
```

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`
3. Wait a few seconds and the dev server will return the error

**Comment by aklinker1** [comment]
Works for me when I add that flag.

A minimal reproduction is not steps to create a project, it's a zip file or a link to a github repo. Also please share your environment information like the template requests so I know which OS you're on.

https://github.com/wxt-dev/wxt/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1
