### ISSUE TITLE
Weird error when sourcemap is enabled

### ISSUE THREAD

**Issue by neilfranci** [wxt-dev/wxt#449]
### Describe the bug

When I update from 0.14.7 to 0.15.0 source map is enabled by default and
whenever I make change in content script and save it print the error
`Error when using sourcemap for reporting an error: Can't resolve original location of error.`

Set it off `sourcemap: false` will not cause it anymore.

Not sure if this happened with other frameworks like React or Svelte 

### To Reproduce

Share minimal reproduction. Examples of a minimal reproduction:
[temp.zip](https://github.com/wxt-dev/wxt/files/14297370/temp.zip)

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`
3. Go to MainUI.vue
4. Try comment `const test = ref('test');`
5. It will crash

### Screenshots
![image](https://github.com/wxt-dev/wxt/assets/66520542/ca0ba1f5-6d01-4f37-a97a-6f85d3bcddb0)

### Environment
```
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 4.44 GB / 15.73 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.112)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    wxt: ^0.15.0 => 0.15.0
```

### Additional context
Already tested out latest 0.16.6 but still yeah

**Comment by aklinker1** [comment]
Yeah, not sure TBH. This is the second problem with the vue plugin, also see #270. I haven't had time to look into this yet, but it appears only related to content scripts... Re-running the dev command works, but that's obviously not a solution...

I'll have to explore the vue plugin a bit more to try to figure out what's going on, but I have other priorities right now, so it'd be a great help if someone else helped out with this.

**Comment by Timeraa** [comment]
Hey, I updated all the dependencies in the temp.zip and it does not seem to happen anymore, so I think this issue seems fixed!

**Comment by neilfranci** [comment]
> Hey, I updated all the dependencies in the temp.zip and it does not seem to happen anymore, so I think this issue seems fixed!

I've not used Vue and Wxt for about 6 months. So I can't be sure, but maybe it's been fixed. So I'll close it
