### ISSUE TITLE
Is there support for script injection functionality?

### ISSUE THREAD

**Issue by asasas234** [wxt-dev/wxt#455]
The function I want to achieve is roughly as shown in the following code：
```
function injectScript(file_path: string) {
            //var node = document.getElementsByTagName(tag)[0];
            let node = document.documentElement
            let script = document.createElement('script');
            script.setAttribute('type', 'text/javascript');
            script.setAttribute('src', file_path);
            node.appendChild(script);
        }
injectScript(browser.runtime.getURL('/xxx.js'));
```

Afterwards, I followed the documentation and created a file named injected.ts in the endpoint directory, with the following code：
```
export default class Test {
    constructor() {
        console.log("hello world!!!~~~~")
    }
}
new Test()
```
Then I use injectScript to perform script injection.
```
injectScript(browser.runtime.getURL('/injected.js'));
```
Did I misunderstand the documentation when I found that the output of the code is during the compilation phase, rather than at runtime? How can I develop this kind of script injection feature based on wxt while also supporting TypeScript?

**Comment by aklinker1** [comment]
Injected scripts are considered "unlisted", so you need to export default `defineUnlistedScript`, similar to `defineBackground` or `defineContentScript`

https://wxt.dev/entrypoints/unlisted-scripts.html#definition

Otherwise everything else looks fine in the code you typed up.

**Comment by asasas234** [comment]
@aklinker1 Thank you, I understand how to operate now.

**Comment by scoful** [comment]
Hello, this example is very similar to my requirements. Could you please share how you modified this example?

```
function injectScript(file_path: string) {
            //var node = document.getElementsByTagName(tag)[0];
            let node = document.documentElement
            let script = document.createElement('script');
            script.setAttribute('type', 'text/javascript');
            script.setAttribute('src', file_path);
            node.appendChild(script);
        }
injectScript(browser.runtime.getURL('/xxx.js'));
```

**Comment by aklinker1** [comment]
https://github.com/wxt-dev/examples/tree/main/examples/inject-script

**Comment by scoful** [comment]
> @aklinker1 Thank you, I understand how to operate now.

Thank you very much for your reply.
What I want to do is change the html content inside the content.
For example, 
`document.getElementsByClassName('')[0].innerHTML`
Get the html content, modify it, reassign it, but find that your example doesn't work.
The error message is as follows:
`TypeError: Cannot read properties of undefined (reading 'innerHTML')`
By the way, it's okay to use pure js.
look forward to your reply.

**Comment by scoful** [comment]
> https://github.com/wxt-dev/examples/blob/main/examples/inject-script/utils/inject.ts

Thank you very much for your reply.
What I want to do is change the html content inside the content.
For example,
`document.getElementsByClassName('')[0].innerHTML`
Get the html content, modify it, reassign it, but find that your example doesn't work.
The error message is as follows:
`TypeError: Cannot read properties of undefined (reading 'innerHTML')`
By the way, it's okay to use pure js.
look forward to your reply.
