### ISSUE TITLE
Support set `sidebar_action.open_at_install` option

### ISSUE THREAD

**Issue by yunsii** [wxt-dev/wxt#462]
### Feature Request

With firefox add-on, it will open sidebar after add-on installed by default, how can I set [`sidebar_action.open_at_install`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) option?

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

N/A

But I think WXT can provide a hook to modify manifest.json? for example, `postManifest` to modify the json object?

**Comment by aklinker1** [comment]
Looks like I have a TODO for this: https://github.com/wxt-dev/wxt/blob/ea0e40c269c8100e5ee2cb9ed92b833ec7b738ad/src/core/utils/manifest.ts#L333-L337

You can modify the manifest in the `"build:manifestGenerated"` hook for now. https://wxt.dev/api/wxt/interfaces/WxtHooks.html#build-manifestgenerated
