### ISSUE TITLE
`wxt build` `-c | --config` is ignored

### ISSUE THREAD

**Issue by zhugazi** [wxt-dev/wxt#467]
### Describe the bug

When I used wxt build-c to specify the configuration file, I found that it did not take effect according to my configuration.

<img width="523" alt="image" src="https://github.com/wxt-dev/wxt/assets/20312521/72ce9690-66c4-42ac-98bc-aa5899b342d5">

Still read the default configuration file, wxt.config.ts in the root directory.

<img width="560" alt="image" src="https://github.com/wxt-dev/wxt/assets/20312521/5787fa47-1d8d-4051-8c4e-e81937ff1fcc">

I found that it seems that when wxt executes the build command, the parameter name used by loadConfig is written dead, which limits the use. Does this place need to be modified, or is there any other way to meet my needs?

What I want is for different browsers to type a different file.

**Comment by aklinker1** [comment]
Released fix in [`v0.16.10`](https://github.com/wxt-dev/wxt/releases/tag/v0.16.10)
