### ISSUE TITLE
Injecting Content Script conditionally

### ISSUE THREAD

**Issue by mbersier** [wxt-dev/wxt#469]
So I have this project where I need to inject my content script from my background.js only if a given cookie is set.
What I did is converting my content script js to a UnlistedScript, but UnlistedScript doesn't pass a ctx to it's main method. That means I cannot use the createShadowRootUi function and init my app in it.

Is there a way to still use content script, but inject it manually?

**Comment by aklinker1** [comment]
I'll add a `registration:"runtime"` option to disable adding it to the manifest (and adding `host_permissions` instead).

**Comment by aklinker1** [comment]
Released in [`v0.16.10`](https://github.com/wxt-dev/wxt/releases/tag/v0.16.10)

**Comment by mbersier** [comment]
Thx @aklinker1 for this!
Since this new update, I noticed an issue with the generated background.js when registration is set to runtime.
It seems like reloadContentScript always fetches the content script for the hot reload, so it's not working well in dev, but no issues when building the app.

Sorry if I'm not creating a new issue, not sure if I should or not :/

**Comment by aklinker1** [comment]
> reloadContentScript always fetches the content script for the hot reload

@mbersier I don't understand whats wrong this... For me, `reloadContentScript` is getting called correctly. When a script changes, it is reloaded properly.

**Comment by aklinker1** [comment]
@mbersier Could you provide a simple reproduction so I don't have to create one myself when testing this out?

**Comment by aklinker1** [comment]
@mbersier or could you just try `wxt@0.16.12-alpha1`? I just published test version with the dev mode changes

**Comment by mbersier** [comment]
@aklinker1 Good news! wxt@0.16.12-alpha1 seems to be working fine in dev now!
Thanks!

**Comment by aklinker1** [comment]
Awesome, I need to cleanup the code that finds the correct content script to reload, I'll release an update after that. Hopefully today or tomorrow

**Comment by aklinker1** [comment]
Released in [`v0.17.0`](https://github.com/wxt-dev/wxt/releases/tag/v0.17.0)
