### ISSUE TITLE
Add `content` to the template `entrypoints`

### ISSUE THREAD

**Issue by btea** [wxt-dev/wxt#494]
### Feature Request

After initializing a project through the provided command, there is no `content.ts` in the `entrypoints`. 

I would like to add `content.ts` to all templates, and if you agree to this proposal, I can create a PR.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

No.

### Additional context

No.

**Comment by aklinker1** [comment]
I could see this being useful. What are you going to put in the content script?

**Comment by btea** [comment]
I think putting a simple piece of code will do the trick.
```ts
export default defineContentScript({
  matches: ['*://*.google.com/*'],
  runAt: 'document_start',
  main() {
    coneole.log('Hello content.')
  },
});
```
