### ISSUE TITLE
`iconDir` configuration option

### ISSUE THREAD

**Issue by uncenter** [wxt-dev/wxt#514]
### Feature Request

Add a root level `iconDir` configuration to specify a directory other than the `publicDir` for icons.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

Manually entering the icons in the manifest: https://wxt.dev/guide/manifest.html#icons.

**Comment by aklinker1** [comment]
Why do you need to put the icons in a different directory?

**Comment by uncenter** [comment]
Some complicated mess with copying assets from a submodule. I'll just add a script to do some janky stuff in the before hook ahah.
