### ISSUE TITLE
Browser extension icon disappears after changing `srcDir` to `src`

### ISSUE THREAD

**Issue by eastack** [wxt-dev/wxt#515]
In one of my projects, I modified `srcDir` to `src` to conform to my previous development habits (one major reason was that I felt it might affect plugins I used in regular front-end development). Afterwards, I found the browser extension icon had disappeared. I spent some time debugging wxt, but did not resolve the issue. However, I finally found the explanation in the Directory Config summary section of the documentation, and finally figured it out.

![wxt-doc](https://github.com/wxt-dev/wxt/assets/17524858/e77a0bd8-4215-4d02-bbd4-c4ad5b055996)

Perhaps we could do something to avoid this kind of problem, such as mentioning this potential issue in the `srcDir` documentation. Or maybe it would be better to decouple the `publicDir` and `srcDir` relationship? I'm not very familiar with WXT or front-end development since I'm new, but it feels like there is room for improvement here.

**Comment by aklinker1** [comment]
This is the same behavior as Nuxt, which this project is based off of. I can add docs to the `srcDir` option for clarity.

**Comment by aklinker1** [comment]
I also added some warnings in #516

**Comment by aklinker1** [comment]
Released in [`v0.17.6`](https://github.com/wxt-dev/wxt/releases/tag/v0.17.6)
