### ISSUE TITLE
use unocss 

### ISSUE THREAD

**Issue by Idiot-Alex** [wxt-dev/wxt#522]
### Feature Request

I want to use UnoCSS in the WXT project, but my attempts have been unsuccessful.

I have updated the wxt.config.ts and uno.config.ts files, the contents are as follows. (see Additional context)

But when I launch the project, I receive the following error message:
<img width="876" alt="image" src="https://github.com/wxt-dev/wxt/assets/16541166/b394139b-1de8-47cf-aa28-eacd6745c7d1">

I am able to launch another Vite project normally using the same approach.

#### Is your feature request related to a bug?

N/A

### Additional context

There is my project configs:
1. wxt.config.ts
```
import { defineConfig } from 'wxt';
import vue from '@vitejs/plugin-vue';
import UnoCSS from 'unocss/vite';

// See https://wxt.dev/api/config.html
export default defineConfig({
  imports: {
    addons: {
      vueTemplate: true,
    },
  },
  vite: () => ({
    plugins: [
      vue(),
      UnoCSS(),
    ],
  }),
});

```

2. uno.config.ts
```
// uno.config.ts
import { defineConfig, presetAttributify, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetAttributify({ /* preset options */}),
    presetUno(),
    // ...custom presets
  ],
})
```

**Comment by aklinker1** [comment]
Seems to work just fine for me. Followed the vite setup, and I don't get that error.

[uno-css-example.zip](https://github.com/wxt-dev/wxt/files/14482167/uno-css-example.zip)


https://github.com/wxt-dev/wxt/assets/10101283/3d4ce8a3-18ae-43d2-a145-159d83f1bbca


Something seems messed up about your setup, there's that auto-import warning that shouldn't be showing up either, which makes me think you're not running the application correctly? Can you share a repro?

**Comment by aklinker1** [comment]
Also see #596
