### ISSUE TITLE
`npx wxt build --mode development` doesn't set `process.env.NODE_ENV` to `development`

### ISSUE THREAD

**Issue by pavitra-infocusp** [wxt-dev/wxt#529]
### Describe the bug

 Try to build extension in `development` mode using the command `npx wxt build --mode development` doesn't set `process.env.NODE_ENV` to `development`. It is set to `production`.

### To Reproduce

Steps to reproduce the bug using the reproduction:

1. In a new wxt project.
2. Add `console.log("NODE_ENV", process.env.NODE_ENV)` somewhere in the code.
3. Run `npx wxt build --mode development`
4. Notice that the build command correctly infers the mode
    > ℹ Building chrome-mv3 for development with Vite 5.1.5                                                 8:23:16 PM
6. Open `.output/chrome-mv3/chucks/index*.js` file.
7. Find that the `console.log` statement is transformed to `console.log("NODE_ENV", "production")`

### Expected behavior

Step 5 should have `console.log("NODE_ENV", "development")`

### Environment

```
  System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 23.39 GB / 31.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Browsers:
    Chrome: 121.0.6167.184
  npmPackages:
    wxt: ^0.17.7 => 0.17.7
```

### Additional context

Add any other context about the problem here, otherwise you can delete this section.

**Comment by pavitra-infocusp** [comment]
Sorry, I'm mistaken. Since wxt uses Vite, I should replace all `process.env` to `import.meta.env`

https://vitejs.dev/guide/env-and-mode#node-env-and-modes

**Comment by aklinker1** [comment]
Yup!
