### ISSUE TITLE
WSL Support

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#55]
WXT supports windows CMD, but not Windows Subsystem for Linux (WSL). It should also supports WSL.

- Original Windows issue: #48 
- CMD support: #50 

I don't expect to have any problems with paths like what #50 fixed, instead, it will probably be an issue with `web-ext` and opening the browser. Maybe everything is working fine and we can just close this issue. I haven't even tried it yet.

**Comment by aklinker1** [comment]
Tested WSL2 today, and got the following errors:

![image](https://github.com/wxt-dev/wxt/assets/10101283/86a5ba9d-0042-42aa-8efd-dc5ec685e2d2)

![image](https://github.com/wxt-dev/wxt/assets/10101283/b1f46ada-7d5b-4c6d-93b4-929dccf23112)


It appears to be trying to use the linux paths prefixed with `C:\`? An issue with `web-ext`, not WXT.

For now, I'm going to disable opening the browser automatically when WSL is detected.

**Comment by bogdano2** [comment]
Could this be solved with wsplath from WSLU which is installed by default with the Ubuntu distribution?

[WSL Utilities](https://github.com/wslutilities/wslu) package provides ability to use the wslpath command.

Example usage:

cd $(wslpath 'C:\Users<username>\Documents')
... will change to /mnt/c/Users//Documents.

The reverse conversion is also possible with the -w option:

mspaint.exe $(wslpath -w ~/profile.jpg)
... will open the file \wsl$<distroname>\home<username>\profile.jpg in the Paint application.

**Comment by bogdano2** [comment]
@aklinker1 In the meantime, using a 'junction' mklink approach to the C:\ prefix issue that does not require waiting on web-ext which could simply be added to wxt documentation (and reverting the current fix).

For example, the following command should fix the second error you encountered in this thread:
mklink /d c:\mnt\c \\wsl$\\Ubuntu

**Comment by bogdano2** [comment]
> Tested WSL2 today, and got the following errors:
> 
> ![image](https://private-user-images.githubusercontent.com/10101283/270078163-86a5ba9d-0042-42aa-8efd-dc5ec685e2d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxODIyMTAsIm5iZiI6MTcwMjE4MTkxMCwicGF0aCI6Ii8xMDEwMTI4My8yNzAwNzgxNjMtODZhNWJhOWQtMDA0Mi00MmFhLThlZmQtZGM1ZWM2ODVlMmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA0MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NmQ1Nzc0YzE2OGI5M2U1YjhiZGQ4OWRjMjNmMWFmNzUyYTk0ZDAxZDIyYTM2ZjZhNjMyOGRmNTljNjYxZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kgxXry7Ow5V107jNsrUU63FDCqwqUpJpEP2kTrrdylw)
> 
> ![image](https://private-user-images.githubusercontent.com/10101283/270078179-b1f46ada-7d5b-4c6d-93b4-929dccf23112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxODIyMTAsIm5iZiI6MTcwMjE4MTkxMCwicGF0aCI6Ii8xMDEwMTI4My8yNzAwNzgxNzktYjFmNDZhZGEtN2Q1Yi00YzZkLTkzYjQtOTI5ZGNjZjIzMTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA0MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZGExNGY0OTg5ZWNhNjFkMTM3ZTU0YTMyZjU1Mzk1NjhhYjQyYzcyMTJlNDFlYzk5M2U1ZjAyNzY5YzZkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ky0jGqU4U9Lr04tI9ZsMVQKvCkSDZaN1CD_jUuRODxI)
> 
> It appears to be trying to use the linux paths prefixed with `C:\`? An issue with `web-ext`, not WXT.
> 
> For now, I'm going to disable opening the browser automatically when WSL is detected.

To allow the browser to launch in Windows 11 from a wsl environment (and auto-load the plugin):
1. Open a cmd prompt with admin privileges.
2. For the first error, issue the following command: mklink /D "c:\tmp" "\\wsl$\Ubuntu\tmp"
3. For the second error, create a folder called mnt (mkdir c:\mnt) and then: mklink /D "c:\mnt\c" "\\wsl$\Ubuntu"

Seems like this instruction can be provided in documentation (followed by mod of the error and allowing the browser launch attempt).

**Comment by aklinker1** [comment]
Thanks for the full details, I'll add this to the docs tomorrow, or you can open a PR if you'd like.
