### ISSUE TITLE
Graceful error handling

### ISSUE THREAD

**Issue by KnightYoshi** [wxt-dev/wxt#553]
### Feature Request

**preamble**
I tend to save files periodically, just out of habit from being burned in the past, but also my IDE auto-saves when it loses focus. This causes the extension to be rebuilt—as expected. This is fine until there's an error with the compilation step, say a syntax error because of an incomplete thought.

**request**
It would be ideal if the file watcher didn't die as a result of compilation errors.

#### Is your feature request related to a bug?

Not really a bug per se, but the issue I run into this is that I have it configured to open a browser when it builds and while rebuilding after a change. If there is an error the build command stops and the browser instance stays open. Then running the build command again opens a new browser instance. 

### What are the alternatives?

I'm not sure if the more immediate solution would be to kill the browser processes that is started as a result of the build command, or if it is easier to wrap the compilation step and just prevent it from dying if there's an error.

Can just keep manually closing the browser and restarting the command, but kind of annoying 😅

**Comment by aklinker1** [comment]
Thanks for the report. I've seen this too, but haven't fixed it yet. It should be as easy as adding a try/catch somewhere, just need a reproduction to test it easily. You said it quits when there's a syntax error? I'll try that out.

**Comment by KnightYoshi** [comment]
Yeah, so with just the basic setup, you replicate it just by going to the `background.ts` start it, and then while it's running delete the `log('Hello background!', { id: browser.runtime.id });` to trigger a syntax error. Simple to replicate. I figured it'd would be a try catch and I'd have made a PR if I knew where to look, but I haven't taken a deep dive into this project yet to know how the whole thing works 😅
Simple setup: 
https://github.com/KnightYoshi/wxt-vanilla-test

**Comment by aklinker1** [comment]
Released in [v0.17.8](https://github.com/wxt-dev/wxt/releases/tag/v0.17.8)
