### ISSUE TITLE
tabGroups API missing

### ISSUE THREAD

**Issue by m1911star** [wxt-dev/wxt#558]
### Describe the bug

I just called `browser.tabGroups` (origin is chrome.tabGroups), but got undefined

ref: https://developer.chrome.com/docs/extensions/reference/api/tabGroups

### To Reproduce

browser types do not contain tabGroups

**Comment by m1911star** [comment]
invalid, sorry

**Comment by ShermanTsang** [comment]
Hey, I met the same problem like you.
I try to use `browser.tabGroups` to invoke the API in chrome, but failed.
Can I ask how you solve the problem?
