### ISSUE TITLE
Ability to Auto Open Browser with `--analyze` Build Flag

### ISSUE THREAD

**Issue by joealden** [wxt-dev/wxt#561]
### Feature Request

Like https://github.com/KusStar/vite-bundle-visualizer allows, it'd be nice if `wxt` could open our default browser to view the bundle analysis automatically, instead of having to open the generated HTML file manually.

Maybe via a `--open` flag in addition to the `--analyze` flag, or a seperate `--analyze-open` flag?

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

N/A

### Additional context

N/A

**Comment by aklinker1** [comment]
I like `wxt build --analyze --analyze-open`. A little repetitive, but I don't want to confuse it with opening the extension that was built.

**Comment by aklinker1** [comment]
Released in [v0.17.8](https://github.com/wxt-dev/wxt/releases/tag/v0.17.8)
