### ISSUE TITLE
Weird error only happening in production. Wondering if anyone has seen it? GET chrome-extension://invalid/ net::ERR_FAILED

### ISSUE THREAD

**Issue by ddeisadze** [wxt-dev/wxt#571]
This happens only in production. Content script is not being loaded

<img width="919" alt="image" src="https://github.com/wxt-dev/wxt/assets/1585369/31133e22-1177-4356-913c-a8732761590e">

This is the call the fetch is making from image: "chrome-extension://<extesion>id/content-scripts/jobDesc.css"

This is what it logs to console `GET chrome-extension://invalid/ net::ERR_FAILED`

**Comment by ddeisadze** [comment]
If it helps I am using Chakra React UI Library https://chakra-ui.com/

**Comment by ddeisadze** [comment]
Registering via a shadow dom see content script: 

`import { isJobDescriptionPage } from '@/lib/utility/html';
import ReactDOM from 'react-dom/client';
import App from './app';
import Providers from './providers';

export default defineContentScript({
	matches: ['<all_urls>'],
	cssInjectionMode: 'ui',

	async main(ctx) {
		// 3. Define your UI
		const ui = await createShadowRootUi(ctx, {
			name: 'scout-ahead',
			position: 'inline',
			mode: 'open',

			onMount: (container) => {
				const root = ReactDOM.createRoot(container);

				root.render(
					<Providers container={container}>
						<App />
					</Providers>
				);

				return root;
			},
			onRemove: (root) => {
				root?.unmount();
			},
		});

		const isJobDescription = await isJobDescriptionPage(
			window.location.href,
			document.body.innerHTML
		);

		if (isJobDescription) {
			// 4. Mount the UI
			ui.mount();
			return;
		}
	},
});
`

**Comment by aklinker1** [comment]
This error is thrown when you try and fetch a file from your extension that's not in the `web_accessible_resources`.

WXT should add this automatically in this case, but it appears not to have for you, otherwise you wouldn't see this error.

I need a minimal reproduction, a full project, to debug your case. Screenshots and a couple code snippets is not enough.

**Comment by wuzequanyouzi** [comment]
You can use code in the wxt.config.ts like:
`
import { defineConfig } from 'wxt';
import vue from '@vitejs/plugin-vue';

// See https://wxt.dev/api/config.html
export default defineConfig({
  imports: {
    addons: {
      vueTemplate: true,
    },
  },
  vite: () => ({
    plugins: [vue()],
    build: {
      cssCodeSplit: false
    }
  }),
});
`
抱歉，英文不行，还是用中文，猜测wxt中魔改了fetch，暂时可将样式直接打包进js中~

**Comment by wuzequanyouzi** [comment]
你可以将css直接打包进js中，使用以下代码可暂时解决问题
```ts
import { defineConfig } from 'wxt';
import vue from '@vitejs/plugin-vue';

// See https://wxt.dev/api/config.html
export default defineConfig({
  imports: {
    addons: {
      vueTemplate: true,
    },
  },
  vite: () => ({
    plugins: [vue()],
    build: {
      cssCodeSplit: false
    }
  }),
});
```

**Comment by ddeisadze** [comment]
@aklinker1 it only happens on this webpage: https://babson.wd1.myworkdayjobs.com/en-US/Staff/job/Career-Advisor--part-time---Undergraduate-Center-for-Career-Development_R0013016-1

Works well on every other one. Could it be the website is blocking it?

How can I send you a repo to reproduce?
