### ISSUE TITLE
CSS module stripped off when imported as a side effect

### ISSUE THREAD

**Issue by TomPradat** [wxt-dev/wxt#573]
### Describe the bug

When importing CSS modules directly in a content script : `import "my.module.css"`. The resulting CSS doesn't exist in the content.css.

```js
import "./test.module.css"; // This CSS is never included in the output
import test2styles from "./test2.module.css"; // This CSS is included (apparently because we use test2styles.hello later)

export default defineContentScript({
  matches: ["*://*.google.com/*"],
  main() {
    console.log("Hello content.", test2styles.hello);
  },
});

```

NB : I looked at Vite options and tried a repro but it seems to work fine on a simple Vite project

### To Reproduce

[wxt-css-stripped-repro.zip](https://github.com/wxt-dev/wxt/files/14771693/wxt-css-stripped-repro.zip)

NB : There is a commit for the added code (compared to the initial example)

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `npm i`
2. Start dev mode: `npm dev`
3. Check the `.output/content-scripts/content.css`

### Expected behavior

In `.output/content-scripts/content.css`, I expect to have :

```css
:root {
  --test-variable: black;
}
:root {
  --test-variable-2: white;
}

```

But I have :

```css
:root {
  --test-variable-2: white;
}
```

### Screenshots

N/A

### Environment

N/A

**Comment by aklinker1** [comment]
To the best of my knowledge, this is not how CSS modules work/should be used. CSS modules are a JSX thing to scope CSS to a specific component, and don't have "side effects".

https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

Content scripts are build with Vite's library mode for "production", and it's seeing that the CSS module isn't used, and thus stripping it out. Maybe Vite's dev mode behaves differently like you said, but that's not how production builds work, they strip out unused CSS.

Here's a vanilla Vite project that demonstrates this behavior:

[lib-mode-example.zip](https://github.com/wxt-dev/wxt/files/14783350/lib-mode-example.zip)

1. `npm i`
2. `npm run build`
3. Look at `dist/style.css`. It only contains CSS from `src/test.css`, not `src/test.module.css`. Both are imported in `src/index.ts` as side-effects

---

In this case, simply renaming `test.module.css` &rarr; `test.css` makes everything work.
