### ISSUE TITLE
filtered out excluded entryPoint files when pack into firefox source zip

### ISSUE THREAD

**Issue by honwhy** [wxt-dev/wxt#574]
### filtered out excluded entryPoint files when pack into firefox source zip

for example, When define content script with `exclude['firefox']`, I don't want this content script to show within the zip file

#### Is your feature request related to a bug?

"N/A"

### What are the alternatives?

alternatives as I think of, maintain another git branch and remove those files shall not show within zip file at the end.

### Additional context

use wxt version 0.17.7

**Comment by aklinker1** [comment]
Good catch. I'll look into adding support.

In the meantime, you can add those entrypoints to [`zip.excludeSources`](https://wxt.dev/api/wxt/interfaces/InlineConfig.html#excludesources).

**Comment by nishu-murmu** [comment]
How do we do this? Do we read js files for this value in the output directory? or do we have any method to get the config options for each content script that we define using `defineContentScript` method?

**Comment by aklinker1** [comment]
Yeah, this isn't as easy as I though... We have a `findEntrypoints` function, but it returns entrypoints already filtered out. We could then do a diff to figure out which files/folders in the `entrypoints` folder can be excluded, but I'd rather not implement a second way to list all entrypoints, I'd rather reuse `findEntrypoints` somehow.

So we need to add a boolean parameter to `findEntrypoints` that makes it return all entrypoints, not only the non-skipped ones.

**Comment by aklinker1** [comment]
Just add the files to `wxt.config.zip.excludeSources`: https://wxt.dev/api/reference/wxt/interfaces/ResolvedConfig.html#excludesources

**Comment by nishu-murmu** [comment]
😓 I overthinked it.

**Comment by aklinker1** [comment]
Released in [`v0.19.19](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.19)
