### ISSUE TITLE
I can't override wxt default `--user-data-dir` by chromiumArgs

### ISSUE THREAD

**Issue by kevin-zx** [wxt-dev/wxt#586]
### Describe the bug

Here is my configuration file:
```js
import { defineConfig } from 'wxt';
import vue from '@vitejs/plugin-vue';
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

// See https://wxt.dev/api/config.html
export default defineConfig({
  imports: {
    addons: {
      vueTemplate: true,
    },
  },
  vite: () => ({
    plugins: [
      vue(),
      AutoImport({
        resolvers: [ElementPlusResolver()],
      }),
      Components({
        resolvers: [ElementPlusResolver()],
      }),
    ],
  }),
  runner: {
    startUrls: ['https://www.baidu.com'],
    chromiumProfile: 'd:/workspace/browser_extension/douyin-daren-tool/chromeprofile/Default',
    chromiumArgs: [`--user-data-dir=d:/workspace/browser_extension/douyin-daren-tool/chromeprofile`],
  },
});

```
I want to set --user-data-dir through chromiumArgs, but it doesn't take effect. In chrome://version/, you can see two --user-data-dir parameters (refer to the screenshot below). The setting with the tmp-web-ext-- prefix is the one that takes effect. I want to know how to override the default user data dir set by wxt.

### To Reproduce
1. set `chromiumArgs: [`--user-data-dir=xxx/xxx/`],`
2. pnpm dev
3. open ` chrome://version/`

### Expected behavior

got two `--user-data-dir` args, and first one effected.

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/20208599/a41c3c1e-1cb6-4f43-8af9-7bf2443966d9)

### Environment

```
  System:
    OS: Windows 11 10.0.22635
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400F
    Memory: 16.66 GB / 31.82 GB
  Binaries:
    Node: 18.17.0 - D:\ProgramFiles\nodejs\node.EXE
    npm: 9.6.7 - D:\ProgramFiles\nodejs\npm.CMD
    pnpm: 8.6.11 - D:\ProgramFiles\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    wxt: ^0.17.10 => 0.17.10
```

### Additional context

Add any other context about the problem here, otherwise you can delete this section.

**Comment by aklinker1** [comment]
Chrome ignores invalid flags. Use real windows paths.

```diff
  runner: {
    startUrls: ['https://www.baidu.com'],
-   chromiumProfile: 'd:/workspace/browser_extension/douyin-daren-tool/chromeprofile/Default',
+   chromiumProfile: 'D:\\workspace\\browser_extension\\douyin-daren-tool\\chromeprofile\\Default',
-   chromiumArgs: [`--user-data-dir=d:/workspace/browser_extension/douyin-daren-tool/chromeprofile`],
+   chromiumArgs: [`--user-data-dir=D:\\workspace\\browser_extension\\douyin-daren-tool\\chromeprofile`],
  },
```

**Comment by kevin-zx** [comment]
> ```diff
> chromiumArgs: [`--user-data-dir=D:\\workspace\\browser_extension\\douyin-daren-tool\\chromeprofile`],
> ```

Thank you for your response and for pointing out my mistakes. I copied and pasted the code you provided (the complete configuration file below), but the situation remains the same as before. 
The Chrome version information in the screenshot below does indeed show parameters in Windows format, and I have repeatedly confirmed that the folder address is correct.

There are still two `--user-data-dir` parameters, and the folder I specified does not contain any user data related files. In fact, I had previously attempted using Windows paths format without success. I am indeed a bit confused. I will try the latest version later (the current version is wxt/0.17.10).

I'm a newcomer to browser extension as well. I tried to find the code related to setting chromiumArgs in the wxt repository, but I couldn't find it.

## chrome version screenshot
![image](https://github.com/wxt-dev/wxt/assets/20208599/ccd95668-28e8-48f4-bc13-c745e4b481a1)

## wxt.config.ts
```ts
import { defineConfig } from 'wxt';
import vue from '@vitejs/plugin-vue';
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

// See https://wxt.dev/api/config.html
export default defineConfig({
  imports: {
    addons: {
      vueTemplate: true,
    },
  },
  vite: () => ({
    plugins: [
      vue(),
      AutoImport({
        resolvers: [ElementPlusResolver()],
      }),
      Components({
        resolvers: [ElementPlusResolver()],
      }),
    ],
  }),
  runner: {
    startUrls: ['https://www.baidu.com'],
    // chromiumProfile: 'd:/workspace/browser_extension/douyin-daren-tool/chromeprofile/Default',
    // chromiumArgs: [`--user-data-dir=d:/workspace/browser_extension/douyin-daren-tool/chromeprofile`],
    chromiumProfile: 'D:\\workspace\\browser_extension\\douyin-daren-tool\\chromeprofile\\Default',
    chromiumArgs: [`--user-data-dir=D:\\workspace\\browser_extension\\douyin-daren-tool\\chromeprofile`],
  },
  dev: {
    server: {
      port: 3001,
    },
  },
});
```

**Comment by aklinker1** [comment]
Ah, you likely can't specify both a profile and a data directory at the same time. web-ext sees the profile, copies it into a temp directory (the first `--user-data-url`), then appends your path. So try just removing the custom profile?

**Comment by kevin-zx** [comment]
I have tried setting the profile or data directory separately, but neither of them took effect. When I tried setting chromiumProfile alone, I found that the profile was actually influenced by user-data-dir (it was in the temporary directory C:\Users\zhang\AppData\Local\Temp\tmp-web-ext--3544-9nLnd0hrVFk1\Default). That's why I attempted to see if user-data-dir could solve the problem.

**Comment by aklinker1** [comment]
Just tested, and this works just fine on Mac. It points the browser to `./data`

```ts
  runner: {
    chromiumArgs: ['--user-data-dir=data'],
  },
```

<img width="764" alt="Screenshot 2024-04-01 at 11 15 57 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/56ee9a75-6dd5-4448-b78a-ca437aa55e99">

**Comment by kevin-zx** [comment]
Okay, I will test it on my Mac. Thank you very much for your response.

**Comment by kevin-zx** [comment]
I found the source of the bug. It's actually in web-ext-run. They seem to have a solution, so I'm noting it down here:
https://github.com/mozilla/web-ext/issues/1909
https://github.com/mozilla/web-ext/pull/1920
I hope it can help people who encounter the same issue.
