### ISSUE TITLE
UnoCSS Vite plugin failed to pick up import from entrypoint's `index.ts`

### ISSUE THREAD

**Issue by HigherOrderLogic** [wxt-dev/wxt#596]
### Describe the bug

UnoCSS failed to pickup `uno.css` import from `index.ts`.

I open this issue here because the plugin works perfectly fine in vanilla Vite project. Will open an issue upstream if the problem doesnt lie in WXT.

### To Reproduce

https://stackblitz.com/edit/github-c9syzq

You can also try https://github.com/Deuscx/starter-vue-wxt

To reproduce the bug, just run the build script and see the warning pop up at console.

### Expected behavior

No warning

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/73709188/5e6c455c-1778-4144-abaf-27a6e3c8cb47)

### Environment

```
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    wxt: ^0.17.0 => 0.17.11 
```

### Additional context

N/A

**Comment by aklinker1** [comment]
UnoCSS is working just fine. You can see the `mt-2` class is applied correctly in the github repo you shared:

<img width="862" alt="Screenshot 2024-04-03 at 12 45 05 PM" src="https://github.com/wxt-dev/wxt/assets/10101283/b65eb74f-d4d0-41e3-b49d-0c32bb2470dc">

WXT orcastrates multiple vite builds. The two warnings come from building the background and content script, neither of which include the `uno.css` import. So those warnings are working as expected.

I can add a util that helps scope vite plugins to specific entrypoints.

**Comment by aklinker1** [comment]
As of [`v0.17.12`](https://github.com/wxt-dev/wxt/releases/tag/v0.17.12), you can now conditionally add vite plugins based on the entrypoints being built. This will let you exclude unocss for the background and content scripts:

```ts
export default defineConfig({
  // ...

  vite: () => ({
    plugins: [vue()],
  }),
  hooks: {
    "vite:build:extendConfig": (entries, config) => {
      const entryNames = entries.reduce((set, entry) => {
        set.add(entry.name);
        return set;
      }, new Set<string>());
      if (entryNames.has("popup") || entryNames.has("options")) {
        config.plugins!.push(UnoCSS());
      }
    },
    "vite:devServer:extendConfig": (config) => {
      config.plugins!.push(UnoCSS());
    },
  },
});
```

Tested this exact code with your repro, and it's working without any warnings.

**Comment by HigherOrderLogic** [comment]
Thanks for your work!
