### ISSUE TITLE
[Shadow DOM UI] ui.mounted prop is always undefined

### ISSUE THREAD

**Issue by TomPradat** [wxt-dev/wxt#597]
### Describe the bug

According to the docs (https://wxt.dev/api/wxt/client/type-aliases/ShadowRootContentScriptUiOptions.html#onmount). Returning a variable from the `onMount` options should make it available in the `mounted` property of the value returned by `createShadowRootUi `.

The issue is that this value is always `undefined`.

```js
// 1. Import the style
import "./app.css";

export default defineContentScript({
  matches: ["<all_urls>"],
  // 2. Set cssInjectionMode
  cssInjectionMode: "ui",

  async main(ctx) {
    // 3. Define your UI
    const ui = await createShadowRootUi(ctx, {
      name: "example-ui",
      position: "inline",
      onMount(container) {
        // Define how your UI will be mounted inside the container
        const app = document.createElement("p");
        app.textContent = "Hello world!";
        container.append(app);

        return "Hello world!";
      },
    });

    // 4. Mount the UI
    ui.mount();

    // This should return "Hello world", but returns "undefined"
    console.log(ui.mounted);
  },
});
```

### To Reproduce

Here is a ZIP of a minimal repro :

[wxt-ui-mounted-repro.zip](https://github.com/wxt-dev/wxt/files/14854886/wxt-ui-mounted-repro.zip)

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `npm install`
2. Start dev mode: `npm run dev`
3. Go on any website
4. You will see `undefined` displayed in the console

### Expected behavior

The console should display `Hello world!` instead

### Environment

```
  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 95.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.5.1 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.15.5 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
    bun: 1.0.14 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 123.1.64.113
    Chrome: 123.0.6312.105
    Firefox Nightly: 121.0a1
    Safari: 16.5.2
```

**Comment by aklinker1** [comment]
Probably because I return the value instead of using a getter 🤦 

https://github.com/wxt-dev/wxt/blob/2e0e104d48215e862ae6096543f9fef1b86df5d0/src/client/content-scripts/ui/index.ts#L147

Looks like I also have a typing mistake with the `!`. I'll fix hat too.
