### ISSUE TITLE
Can you provide an example of integrating Antd？

### ISSUE THREAD

**Issue by ggymzz** [wxt-dev/wxt#601]
### To Reproduce

Share minimal reproduction. Examples of a minimal reproduction:

- PR with a failing test case
- ZIP file containing a minimal WXT project (be sure to include your lockfile!!)

> **_⚠️ If you don't upload a minimal reproduction, your issue will be closed until a reproduction is added._**
>
> Why? https://antfu.me/posts/why-reproductions-are-required

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`
3. Click this...
4. Do that...
5. Etc...

### Environment

```
Paste output here
```

### Additional context

Add any other context about the problem here, otherwise you can delete this section.

**Comment by aklinker1** [comment]
No, just use it how you would in a regular project. 

https://ant.design/docs/react/introduce

**Comment by sedationh** [comment]
@aklinker1  I try to use Antd 5 in content ui {createShadowRootUi}
bt the style seems not work
<img width="1261" alt="image" src="https://github.com/wxt-dev/wxt/assets/56129212/55104a46-b77f-4a81-9d80-15d1150db450">

except for that, in the shell output a lot of error log
![image](https://github.com/wxt-dev/wxt/assets/56129212/6dc698ab-a48b-484a-8818-eadb89716a0a)

i provide the mvp here https://github.com/sedationh/awesome-toc/tree/question
> ples attention the branch is question

**Comment by aklinker1** [comment]
@sedationh Looks like by default, Ant adds component styles to the webpage's `head` element, not the shadow root. So basically, the styles are applied to the page, but the shadow root is isolated style-wise from the page, so they don't show up.

They have docs for this exact case: https://ant.design/docs/react/compatible-style#shadow-dom-usage

As for WXT, `createShadowRootUi` handles creating the shadow root and the container. Just modify the `onMount` to look like this:

```diff
-onMount: (container) => {
+onMount: (container, shadow) => {
        const app = document.createElement('div');
        container.append(app);

        const root = ReactDOM.createRoot(app);
-        root.render(<App />);
+        root.render(
+         <StyleProvider container="shadow" />
+           <App />
+         <StyleProvider />
+        );
        return root;
      },
```

**Comment by zrkun** [comment]
the message comonent of the Antd doesn't work in the content UI, how to resolve? @aklinker1

**Comment by zrkun** [comment]
it seems that the component doesn't render in the shadowRoot 
![image](https://github.com/wxt-dev/wxt/assets/163830553/38cafde0-31d1-40ef-9887-76934a9b3995)
@aklinker1

**Comment by sedationh** [comment]
@aklinker1  LGTM thank you~
