### ISSUE TITLE
In serve mode, when changing the App. vue file, the render function is missing

### ISSUE THREAD

**Issue by wuzequanyouzi** [wxt-dev/wxt#606]
### Describe the bug
When I update the App. vue file, the console displays the following warning：

![image](https://github.com/wxt-dev/wxt/assets/49070557/93461736-8017-47eb-981c-7bf9beb3f21f)

I looked at the context scripts/content.js file in the packaged product, and the variable (_sfc_main) that defines the information of the App. vue component was overwritten。
![image](https://github.com/wxt-dev/wxt/assets/49070557/a6d0b3d6-c49b-44c5-969a-376fde463c74)

The overwrite operation here is performed by Vue's compiler-sfc ([compileScript.ts](https://vscode.dev/github/vuejs/core/packages/compiler-sfc/compileScript.ts))
![image](https://github.com/wxt-dev/wxt/assets/49070557/e335494c-bb00-4807-adf5-c6b15de1ec89)

I am currently unclear about the purpose of this attribute called 'inlineTemplate', but in wxt, I set the preset config of vite, config.build.sourcemap, to false, and it can work now
![image](https://github.com/wxt-dev/wxt/assets/49070557/c12ddf27-7893-41be-8dbc-7a696e172020)
![image](https://github.com/wxt-dev/wxt/assets/49070557/d90fda32-0aa5-4007-9997-97137fd27b18)

**Comment by northsea4** [comment]
Any updates on the Vue issue? Developing without source maps is terrible!
