### ISSUE TITLE
Unable to clear `default_popup`

### ISSUE THREAD

**Issue by ZhUyU1997** [wxt-dev/wxt#612]
### Describe the bug

I tried the setting from other issues, but failed to clear "default_popup"

```js
export default defineConfig({
  vite: () => ({
    plugins: [react()],
  }),
  manifest: {
    action: {},
  },
});
```
manifest.json
```json
{
  "manifest_version": 3,
  "name": "wxt-starter",
  "description": "manifest.json description",
  "version": "0.0.0",
  "icons": {
    "16": "icon/16.png",
    "32": "icon/32.png",
    "48": "icon/48.png",
    "96": "icon/96.png",
    "128": "icon/128.png"
  },
  "action": {
    "default_title": "Default Popup Title",
    "default_popup": "popup.html"
  },
  "background": { "service_worker": "background.js" },
  "content_scripts": [
    { "matches": ["*://*.google.com/*"], "js": ["content-scripts/content.js"] }
  ]
}

```
### To Reproduce

- Install
```sh
 pnpm dlx wxt@latest init wxt-hellp
 pnpm install
 pnpm install vite
```
- Change the wx.config.js
```js
import { defineConfig } from "wxt";
import react from "@vitejs/plugin-react";

// See https://wxt.dev/api/config.html
export default defineConfig({
  vite: () => ({
    plugins: [react()],
  }),
  manifest: {
    action: {},
  },
});
```
- run `pnpm build`
- 
### Expected behavior

`default_popup` should be cleared

### Environment

```
  System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 9.32 GB / 31.81 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.28.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.0.36 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22621.1
```

**Comment by aklinker1** [comment]
It's getting added back because you have a popup entrypoint defined, so it's including the popup in the manifest. Delete `entrypoints/popup.html` and it will go away.

See https://wxt.dev/entrypoints/popup.html

**Comment by ZhUyU1997** [comment]
> It's getting added back because you have a popup entrypoint defined, so it's including the popup in the manifest. Delete `entrypoints/popup.html` and it will go away.
> 
> See https://wxt.dev/guide/entrypoints.html and https://wxt.dev/entrypoints/popup.html

I don't want to delete popup.html. Currently, `browser.action.onClicked` is denied due to `default_popup `.
Any method to keep popup.html but remove `default_popup ` in manifest.json?

**Comment by aklinker1** [comment]
Rename the file to something other than `popup.html`, or use the `build:manifestGenerated` to modify the generated manifest before it's written to the output directory.
