### ISSUE TITLE
Cannot use browser when executeScript

### ISSUE THREAD

**Issue by pengjeck** [wxt-dev/wxt#616]
### Describe the bug

Inject in function with a browser object into a tab,  Warn "Uncaught ReferenceError: browser is not defined"

### To Reproduce
zip file is here: 
[for_issue.tar.gz](https://github.com/wxt-dev/wxt/files/14986610/for_issue.tar.gz)
issue code is in background.js:
```typescript
export default defineBackground(() => {

  function renderPage() {
    console.log("render page")
    document.body.style.backgroundColor = 'red'
    browser.runtime.sendMessage({
      type: "renderPage"
    })
  }

  browser.action.onClicked.addListener((tab) => {
    console.log("on clicked", tab)

    if (tab == undefined || tab.id == undefined) return

    browser.scripting.executeScript({
      target: { tabId: tab.id },
      func: renderPage
    }).then(injectionResults => {
      console.log("injectionResults", injectionResults)
    })
  })

  console.log('Hello background!', { id: browser.runtime.id });
});

```

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`
3. Open a webpage and inspect console, for example: google.com
4. Click extension icon in brower tool bar

You will notice a warning 
![image](https://github.com/wxt-dev/wxt/assets/14035577/640eccb2-7529-472a-9cf9-e82aeb6af122)

### Expected behavior

use browser object in executScript to replace <all_urls> permissions with activeTab
reference: https://developer.chrome.com/docs/extensions/develop/concepts/activeTab

### Environment
```
  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 87.75 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.11 - ~/.nvs/default/bin/yarn
    npm: 10.4.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.3 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 16.4
  npmPackages:
    wxt: ^0.17.0 => 0.17.12 ```

**Comment by aklinker1** [comment]
`browser` is imported from `wxt/browser`, so of course it's not defined when executed in the script.

Since `exexuteScript` doesn't support ESM imports, there isn't a way to make it available inside your function. There's no way for WXT to do it either.

Instead, use `chrome` directly:

```ts
function renderPage() {
  console.log("render page")
  document.body.style.backgroundColor = 'red'
  chrome.runtime.sendMessage({ type: "renderPage" })
}
```

**Comment by pengjeck** [comment]
I see! Thank you for your reply
