### ISSUE TITLE
chrome plugin uninstall listening

### ISSUE THREAD

**Issue by zhugazi** [wxt-dev/wxt#627]
### Feature Request
I need to listen for the extension to uninstall, and Chrome provides this method.
API address: https://developer.chrome.com/docs/extensions/reference/api/management?hl=zh-cn#event-onUninstalled

#### Is your feature request related to a bug?

N

### What are the alternatives?

I have no alternative plan for the time being.

### Additional context

chrome management API provides a lot of functions, I hope the author can add these functions, for plug-in development, I still need these data for analysis, thank you.

![image](https://github.com/wxt-dev/wxt/assets/20312521/a8ff7789-bdcc-40a1-97d1-fb66197ab25d)

**Comment by aklinker1** [comment]
WXT already supports this... You should be able to access `browser.managment.*` just fine.
