### ISSUE TITLE
Type-safe for storage API like `defineExtensionMessaging`

### ISSUE THREAD

**Issue by ZhUyU1997** [wxt-dev/wxt#628]
### Feature Request

I like `defineExtensionMessaging`, it ensures the type-safe. Why not create a similar thing for storage?
Then we can remove the type parameter

```ts
interface StorageMap {
  "local:foo": string[];
  "local:bar: number
}
export const { storage } = defineExtensionStorage<StorageMap>();


// usage
storage.getItem("local:foo")
storage.setItem("local:foo", ["1", "2"])
```
#### Is your feature request related to a bug?

N/A

### What are the alternatives?

N/A

### Additional context

N/A

**Comment by aklinker1** [comment]
I don't think this is very helpful. I already provide the `storage.defineItem` API, which supports types, default values, and migrations, so if we were to add a schema to the storage object as you've described, it would only be useful for types.

Instead, does something like this work for you?

```ts
import { storage as wxtStorage } from 'wxt/storage';

export const storage = {
  foo: wxtStorage.defineItem<number>('local:foo'),
  bar: wxtStorage.defineItem<string[]>('local:bar'),
}
```

**Comment by ZhUyU1997** [comment]
> @ZhUyU1997 I don't think this adds anything new. I already provide the `storage.defineItem` API, which supports types, default values, and migrations. If we were to add a schema to the storage object as you've described, it would only be useful for types.
> 
> Instead, does something like this work for you?
> 
> ```ts
> import { storage as wxtStorage } from 'wxt/storage';
> 
> export const storage = {
>   foo: wxtStorage.defineItem<number>('local:foo'),
>   bar: wxtStorage.defineItem<string[]>('local:bar'),
> }
> ```

It sound good enough for me. Thanks for your notice, I miss this part in docs.
