### ISSUE TITLE
wxt is required to support Chrome onInstall and onUnInstall

### ISSUE THREAD

**Issue by zhugazi** [wxt-dev/wxt#629]
### Feature Request

The Chrome plugin supports installation and uninstallation of extensions. Currently WXT only supports installation event monitoring at runtime, but I can't find event monitoring at uninstallation.

#### Is your feature request related to a bug?

N

### What are the alternatives?

I haven't seen an alternative on WXT yet, but Chrome does support it and hopefully WXT does.

### Additional context

[chrome onUninstall api address](https://developer.chrome.com/docs/extensions/reference/api/management?hl=zh-cn#event-onUninstalled)  

![image](https://github.com/wxt-dev/wxt/assets/20312521/c80566db-b2d2-4245-9570-87840fb2acf7)

**Comment by aklinker1** [comment]
Not all APIs are typed, specifically ones that aren't supported by Firefox, or ones that are new. However, they're available at runtime if the browser supports them, so you can call `browser.management.onUninstalled.addListener` already.

Types are provided by an upstream library, so you can open an issue there: `webextension-polyfill-ts`
