### ISSUE TITLE
Unable to retrieve defaultValue set with defineItem using getItem

### ISSUE THREAD

**Issue by 1natsu172** [wxt-dev/wxt#645]
### Describe the bug

I noticed a strange behavior, and I'm not sure if it's intentional, so I'm post an issue.

When I try to retrieve the defaultValue defined with defineItem using `storage.getItem` instead of `defineItem.getValue`, it returns null.

After investigating, I found that if I call `defineItem.setValue` or `storage.setItem` even once, I can then retrieve the value using `storage.getItem` . In other words, there's no problem if it's not the defaultValue.

If this behavior is unintended, please check out the draft PR.

### To Reproduce

- PR with a test case
  - https://github.com/wxt-dev/wxt/pull/644

Steps to reproduce the bug using the reproduction:

1. Run test: `pnpm test`

### Expected behavior

I expected to be able to retrieve the defaultValue using `storage.getItem`, but I'm not sure what the correct behavior should be...

### Screenshots

none

### Environment

development

### Additional context

none

**Comment by 1natsu172** [comment]
For now, I want to get the defaultValue from `storage.getItem`, so I set the defaultValue by self as a patch.

```
const defined = centralStorage.defineItem<Config["defaultValue"]>(
  config.storageKey,
  config.storageOptions
);
// PATCH for
await defined.setValue(config.defaultValue);
```

**Comment by aklinker1** [comment]
This is the intended behavior. `storage.getItem` supports a second argument with a default value, but if you use `defineItem`, you're meant to only access the value via the defined item, not via the regular storage APIs.

**Comment by 1natsu172** [comment]
@aklinker1 Thank you for quick response! Copy that. This behavior is intentional.

So in short, most of the APIs are common, but accessing `defineItem` and regular storage API through the same key is not originally approved. (Although it is not currently in error.) I should use the two separately.

---

By the way...
I am writing my own react version of [this](https://github.com/wxt-dev/wxt-examples/tree/main/examples/vue-storage-composable#readme). And I was trying to get the storage value of item defined in the backend simply by "key only", without importing them in the frontend. I will rethink my frontend design! 👍
