### ISSUE TITLE
Vue-router error in wxt template development

### ISSUE THREAD

**Issue by QuietlyChan** [wxt-dev/wxt#664]
Hey everyone, I'm facing an issue while using vue-router in my wxt vue template development. The error message I'm getting is: "[Vue warn]: Failed to resolve component: router-view. If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement."

The weird thing is, it works perfectly fine in regular development, but as soon as I integrate it into wxt, it starts throwing this error. Has anyone else encountered this issue before? Any help would be greatly appreciated!

**Comment by aklinker1** [comment]
Hmm, interesting. This error usually occurs when you forget to register the router plugin with the vue app. Can you double check that you're calling `app.use(router)`? https://router.vuejs.org/guide/#Registering-the-router-plugin

**Comment by QuietlyChan** [comment]
<img width="301" alt="image" src="https://github.com/wxt-dev/wxt/assets/8343216/200258aa-8079-4429-af0a-c034f8ddc0f1">
<img width="586" alt="image" src="https://github.com/wxt-dev/wxt/assets/8343216/9489ea97-d2b3-4a92-b671-b05e1cf5458f">
<img width="620" alt="image" src="https://github.com/wxt-dev/wxt/assets/8343216/ae4938c7-92f1-41b5-9734-ae0052afd779">
<img width="864" alt="image" src="https://github.com/wxt-dev/wxt/assets/8343216/12022bcb-d36f-4f2a-8b6c-6d4e7fc31d0f">
Hello, I have already properly used app.use(router). This code logic was copied from a Vue 3 project, and everything works fine in a standard Vue 3 environment. However, I encountered a strange issue. As shown in the image above, I imported the Vuetify component library in the main.ts file within the popup and initialized it correctly. It works fine in the popup, but when I tried to use the same method in content.ts, just like with vue-router, it cannot be recognized. In content.ts, I used createShadowRootUi to create the UI. The popup and content each use two separate app.vue and main.ts files. Is this a common practice for developing plugin UIs?

**Comment by QuietlyChan** [comment]
Thank you for your reply. I have normally used app.use(router). It turns out that I need to add relevant logic when creating with createShadowRootUi in content.ts. However, I feel that vue-router may conflict with and affect the URL of the host webpage. Do you all use vue-router? I feel that using it may bring more problems.

**Comment by QuietlyChan** [comment]
I found another problem. When I use Vuetify components in the popup, everything works fine. However, when I try to use Vuetify components in the content, it reports an error. Is there a significant difference between using the Vue instance in createShadowRootUi and using it in main.ts?

**Comment by QuietlyChan** [comment]
<img width="802" alt="image" src="https://github.com/wxt-dev/wxt/assets/8343216/71a1e607-ba37-4787-8cac-1d1681a52ad1">
<img width="1476" alt="image" src="https://github.com/wxt-dev/wxt/assets/8343216/7438cf15-fe99-49d7-bb88-fcaf9e2f753f">

**Comment by QuietlyChan** [comment]
Thank you so much, using Memory mode did solve the problem.
