### ISSUE TITLE
Modules - API Proposal

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#665]
### Feature Request

Create build-time "modules" that can configure and inject shared code.

```ts
// modules/analytics.ts
export default defineWxtModule<AnalyticsModuleOptions>({
  meta: {
    // NPM package name, or inferred from filename: "modules/*.ts"
    // name: "wxt-module-analytics",
    // The key in `wxt.config` that holds your module options
    configKey: "analytics",
    // Compatibility constraints
    compatibility: {
      // Semver version of supported nuxt versions
      wxt: "^0.18.0",
    },
  },
  // Default configuration options for your module, can also be a function returning those
  defaults: {},
  // Shorthand sugar to register WXT hooks
  hooks: {},
  setup(moduleOptions, wxt) {
    // ...
  },
});
```

To include a NPM package as a module:

```ts
// wxt.config.ts

export default defineConfig({
  modules: ["analytics"], // Finds package named "wxt-module-analytics"
});
```

The design of the modules system is based on [Nuxt's modules system](https://nuxt.com/docs/guide/going-further/modules). Basically, everything revolves around using hooks to modifying the build process to achieve some effect, either injecting code, changing vite config, adding entrypoints, or something else.

Modules should be able to:

1. Based on the module definition, add types to the `InlineConfig` interface to allow adding type-safe config
   ```ts
   // .wxt/plugins.d.ts
   module "wxt" {
     export interface InlineOptions {
       analytics: import("wxt-module-analytics").ModuleOptions
     }
   }
   ```
2. Provide a way to inject code that will be ran in an entrypoins (background, popup, etc) and access results
   ```ts
   import { injectJs, addScriptElement } from 'wxt/modules';
  
   export default defineWxtModule({
     // ...
     setup(_, wxt) {
      injectJs(async (entrypoint) => {
        // Return undefined to not inject code
        if (entrypoint.type !== "content-script") return;

        return {
          imports: "import { init } from 'wxt-module-analytics/client'",
          code: `const analytics = init("${entrypoint.name}")`,
          provide: ["analytics"],
        }
      });
      addScriptElement((entrypoint) => {
        if (entrypoint.name !== "popup") return;
        return `<script type="module" src="wxt-module-analytics/client/init"></script>`
      });
     },
   });
   ```
4. Add automatic imports
   ```ts
   import { addAutoImports } from 'wxt/modules';
  
   export default defineWxtModule({
     // ...
     imports: [
       { from: "wxt-module-analytics/client", name: "reportEvent" },
     ],
   });
   ```
5. Add entrypoints
   ```ts
   import { addEntrypoint } from 'wxt/modules';
  
   export default defineWxtModule((wxt) => {
     addEntrypoint({
       type: "content-script",
       name: "some-analytics-script",
       options: {
         matches: "*://*/*",
         // ...
       },
       // ...
     })
   });
   ```
   > Might want to change this to only allow "pre-bundled" entrypoints so these don't effect build time, and are just copied into the output directory.
6. Modify vite config (add plugins or override fields)
   ```ts
   import { addViteConfig } from 'wxt/modules';
  
   export default defineWxtModule((wxt) => {
     addViteConfig((entrypoint) => ({
       plugins: [...],
     }))
   });
   ```

Some examples of modules:

- Analytics - configure and expose APIs for reporting analytic events for different services (GA, umami, etc)
- Bug reporting - configure and expose APIs for reporting errors (sentry, bugsnag, etc)
- Changelog generator - When the extension updates, open a `changelog.html` file based off a `CHANGELOG.md` file or github releases
- ...

This is extremely useful when you need to reuse logic between extensions that whose setup spans multiple entrypoints. If you were to use a shared library for sharing this type of code, you would have to setup the library in all the different entrypoints, which can be annoying if you maintain multiple extensions or the setup is complex.

#### Is your feature request related to a bug?

N/A

**Comment by aklinker1** [comment]
Edit. These are actually "modules", not "plugins", according to Nuxt verbiage. These operate at build-time, not runtime. So I'm renaming this issue: "Plugins (API discussion)" &rarr; "Modules (API discussion)"

**Comment by aklinker1** [comment]
I need to figure out a better way of transforming the JS/TS code to run custom JS code. For example, we need to be able to add imports, call functions, and set the results of those functions in some kind of global scope so they can be accessed later by the client.

If we just use regex to replace code, it will result in Vite complaining about source maps not aligning.

**Comment by aklinker1** [comment]
I suppose one option would be to add an import at the top of all JS entrypoints, like this:

```ts
// .output/chrome-mv3/background.js
import initModules from 'virtual:wxt-modules'
import definition from '...';

try {
  const provided = initModules();
  definition.main(provided);
} catch (err) {
  // ...
}
```

Then use a vite plugin to load custom code for the `virtual:wxt-modules` import. In the example above, this module's content might look like this:

```ts
import { init } from 'wxt-module-analytics/client';

export function initModules() {
  const analytics = init("background");

  return {
    analytics
  }
}
```

This would get around the issues with transforming code. But in this case, it's suddenly looking quite a bit like a plugin-API, with the need for runtime code... Do I have to do both at the same time?

**Comment by aklinker1** [comment]
@davestewart thanks for the idea! Layers is definitely something I want to support at some point. I'm starting with modules because I already have hooks setup, and that's really all that's needed. The main thing that I see modules providing over layers is the ability to modify project entrypoints, like injecting analytics or crash reporting. I don't think that's something layers is capable of.

Though I guess you could add a plugin to a layer which might accomplish similar things... I'm currently thinking through what a plugin-like API would look like with WXT, since it's not really 1-to-1 with Nuxt. 

Need to answer questions like:
- Where do plugin files go?
- How do you decide which entrypoints a plugin effects?
- How does WXT actually include and execute plugin code at runtime?

> For reference, in Nuxt, modules are executed during the build while plugins are executed at runtime in the server.

**Comment by aklinker1** [comment]
Alright, settled on the plan for adding code to JS entrypoints.

1. Register a plugin
   ```ts
   export default defineWxtModule((wxt) => {
      registerPlugin(wxt, (entrypoint) => true, "some-plugin");
    });
    ```
    > Second argument lets you filter which type of entrypoint the plugin is loaded in.
 2. In the plugin, export a default plugin object:
    ```ts
    // some-plugin
    export default defineWxtPlugin(() => {
      // Do something
    });
    ```
 3. Inside WXT, all plugins will be called before the entrypoint's main options:
    ```ts
    // virtual:wxt-background-entrypoint
    import definition from 'your-entrypoint';
    import { initPlugins } from 'virtual:wxt-plugins';
    
    try {
      initPlugins();
      definition.main();
    } catch (err) {
      // ...
    }
    ```
    ```ts
    / / virtual:wxt-plugins
    import plugin1 from 'some-plugin'
    
    export function initPlugins() {
      plugin1.main();
    }
    ```
 
Right now, since plugins won't be user-defined by adding files in a `plugins` folder, I'm not going to worry about ordering, other than respecting the order you call `registerPlugin` in.

Will need to figure out how to use local files for plugins, but I'm not too worried about that, don't need to consider it at this planning stage.

**Comment by aklinker1** [comment]
Released building blocks and basic implementation in [`v0.18.5`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.18.5).

Will be providing more examples and actual modules soon. For now, refer to the docs: https://wxt.dev/guide/go-further/reusable-modules.html

**Comment by davestewart** [comment]
For anyone interested, I wrote a [WXT Layers](https://github.com/davestewart/wxt-module-layers) module, thanks to @aklinker1's awesome work.
