### ISSUE TITLE
 vuetify components error

### ISSUE THREAD

**Issue by QuietlyChan** [wxt-dev/wxt#668]
[test.zip](https://github.com/wxt-dev/wxt/files/15411002/test.zip)
<img width="1390" alt="未命名" src="https://github.com/wxt-dev/wxt/assets/8343216/236d913f-d51c-48aa-9cfa-cdd4e4cc90b2">
When using vuetify components, I encountered the above error. I can use other components normally, so is this a problem with this component library, or did I import it incorrectly?

**Comment by QuietlyChan** [comment]
I've noticed that not only the vuetifyjs library but also the primevue library seems to have issues. It appears that newer libraries tend to report errors directly. However, when I use libraries such as elementUI, vant, or tdesign, I don't encounter any problems. This leads me to believe that there might be compatibility issues between different libraries and wxt. Could you please provide some insight or guidance on this matter? Thank you.

**Comment by aklinker1** [comment]
WXT has to load the entrypoints during the build process to get their metadata, like the content script's `matches`, to generate the manifest. During this process, WXT removes all imports to make sure browser code doesn't run in a node environment. you can see this by running `wxt prepare --debug`.

In this case, it's not removing all imports. Specifically, looks like my regex used to remove the imports doesn't catch `import * as ...` statements:

<img width="557" alt="Screenshot 2024-05-24 at 5 26 54 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/a159fa12-3d95-4f35-a6d0-91b2b5d1f07e">

So it's trying to run browser code in node, and it's failing.

I'll update the regex
