### ISSUE TITLE
The window is not defined error occurs because Sizzle relies on window. Import it only in the browser.

### ISSUE THREAD

**Issue by small-carbon** [wxt-dev/wxt#675]
### Describe the bug

The window is not defined error occurs when trying to use Sizzle in the findElement.ts file. This happens because Sizzle is designed for the browser environment and relies on the window object, which is not available in Node.js.

### To Reproduce

1. Create a file `findElement.ts` in the `utils` directory (`packages\wxt-demo\src\utils\findElement.ts`):

    ```typescript
    import Sizzle from 'sizzle';

    export function cssSelector(selector: string, documentCtx: Document) {
      const elements = Sizzle(selector, documentCtx);
      return elements;
    }
    ```

2. Call `cssSelector` in `main-world.content.ts` (`packages\wxt-demo\src\entrypoints\main-world.content.ts`):

    ```typescript
    import { cssSelector } from '../utils/findElement';

    // Example usage
    const elements = cssSelector('.my-class', document);
    console.log(elements);
    ```
3. Install dependencies: `pnpm i`
4. Start dev mode: `pnpm dev`
5. Observe the error: `window is not defined`

### Expected behavior

The `cssSelector` function should work without causing the `window is not defined` error.

### Screenshots

![image](https://github.com/wxt-dev/wxt/assets/887531/66861fd1-9ebc-450e-ab82-48691602d1c1)

### Environment

```
Paste output here
```

### Additional context

The window is not defined error indicates that Sizzle is being used in a non-browser environment. To resolve this issue, you can use a conditional import to ensure Sizzle is only used in the browser.

**Comment by aklinker1** [comment]
https://wxt.dev/guide/entrypoints.html#side-effects
