### ISSUE TITLE
Imported CSS on contect script UI not applied on sites like Reddit 

### ISSUE THREAD

**Issue by Vortex-21** [wxt-dev/wxt#678]
### Describe the bug

I am facing an issue with WXTs createShadowRootUi() with sites like Reddit . The problem is that the HTML components are injected into the DOM but the CSS is not the way I want . However it works as expected for most of the websites but for Reddit the CSS I write is not applied. Moreover, if I use inline CSS using "element.style.cssText" then it works fine but if I import the styles or use tailwind the CSS is not applied. 

### To Reproduce

Share minimal reproduction. Examples of a minimal reproduction:

[content.zip](https://github.com/wxt-dev/wxt/files/15480688/content.zip)
The above folder is the content folder. Basically in the index.jsx , I have used the createShadowRootUi() . 

### Expected behavior

The expected behaviour was , since the whole Ui is in a shadow root, the CSS should have been isolated and not webpage dependent. 

### Screenshots
![CorrectWXT](https://github.com/wxt-dev/wxt/assets/101874272/ebd89b46-dadf-4440-ba48-9d38896bd4ea)
![CSSproblem](https://github.com/wxt-dev/wxt/assets/101874272/4f711a70-1909-4164-b3ad-00e205336175)

### Additional context
WXT has been very helpful and convenient to use . I have been using it for the last three months and along with its inbuilt and configured  webpacks and all other abstractions it was amazing! Really eliminates the requirement of building extensions and integrating other libraries right from scratch.

**Comment by aklinker1** [comment]
Please provide a full project for the reproduction.

**Comment by Vortex-21** [comment]
[Project_for_reproduction.zip](https://github.com/user-attachments/files/15530158/Project_for_reproduction.zip)

Here is the project for reproduction . And I want to add one more thing . I have used tailwind for styling but the css is not applied even on Youtube. Please look into this matter .

**Comment by debsouryadatta** [comment]
I am also facing the same issues in implementing the contentscript UI(Shadow root injection mode), they are not being shown in the webpage, I am using tailwind CSS for the styles.

**Comment by aklinker1** [comment]
Thanks, I'll reopen and check it out!

Just for reference, I provide a tailwind example. The very last paragraph is relevant to content script UIs.

https://github.com/wxt-dev/wxt-examples/tree/main/examples/vanilla-tailwindcss#readme

**Comment by aklinker1** [comment]
> Here is the project for reproduction . And I want to add one more thing . I have used tailwind for styling but the css is not applied even on Youtube. Please look into this matter.

Tailwind styling is clearly working. You have outlines and padding and background colors. The problem is that while shadow roots isolate 99% of styles, some of the parent page's defaults are applied inside the shadow root as well. In your case, there are 2 things effecting this:

1. Font size: If the HTML page includes `html { font-size: ... }`, the base font size is also changed inside shadow roots.
2. Font color: If the base HTML page sets a text color, the base text color inside the shadow root also becomes that color.

I have not found a way around the font size. To fix your text color, set your own base color.

**Comment by aklinker1** [comment]
When creating UI that run ontop of all websites, you have to keep these caveots in mind. Keep an eye out for other websites that mess with your UI, and apply overrides to make them look standard.

**Comment by debsouryadatta** [comment]
> When creating UI that run ontop of all websites, you have to keep these caveots in mind. Keep an eye out for other websites that mess with your UI, and apply overrides to make them look like it should.

Thanks! It really helped. Is there anything we could do for the font size as well?

**Comment by Vortex-21** [comment]
Okay, will keep a lookout for such sites. For now everything is working as expected. Thanks for the help !!!

**Comment by aklinker1** [comment]
> Thanks! It really helped. Is there anything we could do for the font size as well?

Not that I'm aware of. Let me know if you figure it out!

**Comment by diragb** [comment]
>Not that I'm aware of. Let me know if you figure something out!

Use [postcss-rem-to-responsive-pixel](https://www.npmjs.com/package/postcss-rem-to-responsive-pixel) - essentially, REM (Root EM) always takes the value from the root HTML tag. There's no workaround for that. What you can do instead is use REM in your styles and have this PostCSS plugin convert them into PX values.

My `postcss.config.cjs` file looks like this:
```cjs
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('tailwindcss'),
    require('postcss-rem-to-responsive-pixel')({
      rootValue: 16,
      propList: ['*'],
      transformUnit: 'px',
    }),
  ]
};
```

**Comment by andrewshvv** [comment]
If you are using Tailwind that might help:
https://github.com/tailwindlabs/tailwindcss/discussions/3768#discussioncomment-11339252

**Comment by andrewshvv** [comment]
> > When creating UI that run ontop of all websites, you have to keep these caveots in mind. Keep an eye out for other websites that mess with your UI, and apply overrides to make them look like it should.
> 
> Thanks! It really helped. Is there anything we could do for the font size as well?

If you are using Tailwind that might help:
https://github.com/tailwindlabs/tailwindcss/discussions/3768#discussioncomment-11339252

**Comment by mengxi-ream** [comment]
> > Not that I'm aware of. Let me know if you figure something out!
> 
> Use [postcss-rem-to-responsive-pixel](https://www.npmjs.com/package/postcss-rem-to-responsive-pixel) - essentially, REM (Root EM) always takes the value from the root HTML tag. There's no workaround for that. What you can do instead is use REM in your styles and have this PostCSS plugin convert them into PX values.
> 
> My `postcss.config.cjs` file looks like this:
> 
> module.exports = {
>   plugins: [
>     require('autoprefixer'),
>     require('tailwindcss'),
>     require('postcss-rem-to-responsive-pixel')({
>       rootValue: 16,
>       propList: ['*'],
>       transformUnit: 'px',
>     }),
>   ]
> };

This exactly solve the problem seamlessly
