### ISSUE TITLE
Q & A: Content scripts have some limitations.

### ISSUE THREAD

**Issue by xunziheng** [wxt-dev/wxt#679]
```
However, content scripts have some limitations. They cannot:

> Use chrome.* APIs (except for parts of chrome.extension)
> Use variables or functions defined by their extension's pages
> Use variables or functions defined by web pages or by other content scripts
```
`The window object the content script sees is not the same window object that the page sees.` I mean I am using Integrated type and how can I use the page's context (I wanna use page's window.require)

any suggestions?

regards,

**Comment by xunziheng** [comment]
Thanks a lot, it worked!

by the way, how main world working? I mean can I publish to the chrome store if use main world content scripts.

**Comment by xunziheng** [comment]
Chrome MV3 doesn't allow using remote libraries, but we can do so by creating `script` tags. Isn't it strange?

**Comment by aklinker1** [comment]
They probably won't approve your extension if you are creating script tags to URLs other than a file listed in your own extension

**Comment by xunziheng** [comment]
got it, thanks

good day
