### ISSUE TITLE
Why can not I use the browser api?

### ISSUE THREAD

**Issue by xunziheng** [wxt-dev/wxt#681]
### Describe the bug

such as 
```js
export default defineBackground(() => {
  console.log('Hello background!', { id: browser.runtime.id });

  browser.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
    if (changeInfo.status === 'complete') {
      console.log('useful info: ', tabId, tab.url);
      await browser.browserAction.disable(tabId);
    }
  });
});
```

<img width="505" alt="image" src="https://github.com/wxt-dev/wxt/assets/35691153/5ef9b6d5-72cb-45c7-8497-824b6b4ddf7c">

### To Reproduce

Share minimal reproduction. Examples of a minimal reproduction:

- PR with a failing test case
- ZIP file containing a minimal WXT project (be sure to include your lockfile!!)

> **_⚠️ If you don't upload a minimal reproduction, your issue will be closed until a reproduction is added._**
>
> Why? https://antfu.me/posts/why-reproductions-are-required

Steps to reproduce the bug using the reproduction:

1. Install dependencies: `pnpm i`
2. Start dev mode: `pnpm dev`
3. Click this...
4. Do that...
5. Etc...

### Environment

```
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 186.80 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 125.0.6422.113
    Safari: 17.5
```

### Additional context

Add any other context about the problem here, otherwise you can delete this section.

**Comment by aklinker1** [comment]
Please provide a reproduction. I can think of several reasons why `browser.browserAction` is undefined, but you didn't provide any information that would help me answer the question.

<img width="768" alt="Screenshot 2024-05-31 at 12 57 52 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/100e319e-0c64-4258-94e1-9a8db6e6c54f">

<img width="498" alt="Screenshot 2024-05-31 at 12 58 13 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/5c9b8c10-64cf-42d2-9ac3-11780a4c8517">
