### ISSUE TITLE
report _background not defined

### ISSUE THREAD

**Issue by pftom** [wxt-dev/wxt#684]
### Describe the bug

![image](https://github.com/wxt-dev/wxt/assets/26423749/b10d9687-cb00-4e84-adaa-9268c32b20c1)

wxt: 0.18.3
node: v20.11.1

how to solve it? I see #649 has fixed it, but I still report error 

### Reproduction

wxt: 0.18.3
node: v20.11.1

// entrypoints/background/index.ts
export default defineBackground(() => {
  console.log('hello background');
}) 

report _background not defined

### System Info

```shell
wxt: 0.18.3
node: v20.11.1
MacOS: 14.1 (23B2073)
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Works for me. Please provide a full project with a lockfile for your reproduction

**Comment by pftom** [comment]
@aklinker1 thanks! I'll provide a full project for this
