### ISSUE TITLE
Unlock usage of session storage with content scripts with storage.session.setAccessLevel()

### ISSUE THREAD

**Issue by laugri** [wxt-dev/wxt#695]
### Feature Request

**Request: Add support for `chrome.storage.session.setAccessLevel()` in the WXT storage API.**

Details:

Today, if someone wants to use the browser extension session storage from a content script, they have to "set access level" of the storage area first.

From the `chrome.storage.session` API :
> Holds data in memory for the duration of a browser session. By default, it's not exposed to content scripts, but this behavior can be changed by setting [chrome.storage.session.setAccessLevel()](https://developer.chrome.com/docs/extensions/reference/api/storage#method-StorageArea-setAccessLevel)

This is the line that would be used with plain chrome api code: `chrome.storage.session.setAccessLevel({ accessLevel: 'TRUSTED_AND_UNTRUSTED_CONTEXTS' });`

#### Is your feature request related to a bug?

"N/A"

### What are the alternatives?

Instead of using the WXT storage API, use the browser storage API directly (although i couldn't make it work using `browser` from `wxt/browser` and didn't figure out why).

**Comment by aklinker1** [comment]
@laugri do you know where to call `setAccessLevel()`? In the background like on install, or in the content script before attempting to access session storage?

**Comment by aklinker1** [comment]
Also, I looked at the code agaim, and I misremembered when storage areas are accessed... You should just be able to call `browser.storage.session.setAccessLevel()` at any time before accessing storage, and it should just work?

https://github.com/wxt-dev/wxt/blob/main/packages%2Fwxt%2Fsrc%2Fstorage.ts

**Comment by laugri** [comment]
Thanks for that @aklinker1 and sorry for not being active on this !
