### ISSUE TITLE
Bun installation doesn't work on Windows

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [wxt-dev/wxt#707]
### Describe the bug

Followed the instructions for bun here: https://wxt.dev/get-started/installation.html#bootstrap-project

Got this:
```
  ⚙️  esbuild [1/3] Resolving dependencies
Resolved, downloaded and extracted [4]
Saved lockfile
error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1
```

There doesn't seem to be a problem with esbuild per se though:
```
bun add v1.1.12 (43f0913c)

installed esbuild@0.21.4 with binaries:
 - esbuild

29 packages installed [5.03s]
```

### Reproduction

Run `bunx wxt@latest init repro`.

### Steps to reproduce

Run `bunx wxt@latest init repro`.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 46.69 GB / 63.87 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.5 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.12 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (125.0.2535.85)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

bun

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Interesting, someone reported this in discord, but were unable to install ESBuild in a fresh project. Will try and look into this soon.

**Comment by aklinker1** [comment]
OK, tested this out, looks like this only happens when using `bunx`. Once the project is initialized, `bun install` works just fine.

For now, use NPM to initialize bun projects: 

```sh
npx wxt@latest init
```

**Comment by s-h-a-d-o-w** [comment]
Cool, thanks!

**Comment by aklinker1** [comment]
Updated docs for now: 53b4eac9557a6fcc14ffff66cac57baf6e56586c

Probably won't get to this for a while, so if anyone else wants to try and tackle this, feel free!

**Comment by aklinker1** [comment]
Gonna go ahead and close this as stale. Feel free to re-open if this is still an issue.
