### ISSUE TITLE
The CSS module does not work in development mode

### ISSUE THREAD

**Issue by tonytony2020** [wxt-dev/wxt#734]
### Describe the bug

The CSS module does not work in development mode.

### Reproduction

Create a new extension via the latest version of WXT react template scaffold, 
add Mantine UI package,
add a simple custom component with CSS module,
the CSS module does not work in development (npm run dev).

### Steps to reproduce

1. pnpm dlx wxt@latest init 
2. pnpm add @mantine/core @mantine/hooks
3. pnpm add postcss postcss-preset-mantine postcss-simple-vars
4. add a custom component in content script

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.36 GB / 15.67 GB
  Binaries:
    Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.2.0 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.2 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    wxt: ^0.18.0 => 0.18.4
```
```


### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Please share a minimal reproduction. That's means a whole project, not some text steps. There are too many unknowns for me to help you until you provide one. Either ZIP up the project and upload it in a comment, or link me to a github repo.

**Comment by aklinker1** [comment]
https://github.com/wxt-dev/wxt/issues/736#issuecomment-2173730243

**Comment by aklinker1** [comment]
https://github.com/wxt-dev/examples/blob/8d8129d81a4a4a51838a37a8b946a5c03d8f4b6a/examples/react-mantine/entrypoints/content.tsx#L41-L42
