### ISSUE TITLE
Import Mantine UI style in wxt content script Shadow Root mode does not work

### ISSUE THREAD

**Issue by tonytony2020** [wxt-dev/wxt#736]
### Describe the bug

Import Mantine UI style in wxt content script Shadow Root mode does not work.

Use it in popup is ok, but import it in content script does not work both in development mode and production mode.
see also #734

This bug is pretty obvious. Curious, are there other developers using react or vue in content scripts but not other UI frameworks?

### Reproduction

https://github.com/tonytony2020/wxt-css-module-bug

### Steps to reproduce

see readme in https://github.com/tonytony2020/wxt-css-module-bug

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.68 GB / 15.67 GB
  Binaries:
    Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.2 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.56)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    wxt: ^0.18.6 => 0.18.6
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
You need to tell mantine you're in a shadow root, so it can put the styles inside it. Right now, it's probably putting them outside the shadow root, so they're not being applied.

Try https://mantine.dev/theming/mantine-provider/#cssvariablesselector or https://mantine.dev/theming/mantine-provider/#getrootelement.

```ts
onMount(container, shadow, shadowHost) {
  // Set cssVariableSelector or getRootElement to shadow or shadow.querySelector('head')
}
```

**Comment by aklinker1** [comment]
I've put together a full example for using mantine in content scripts: https://github.com/wxt-dev/examples/tree/main/examples/react-mantine

This is probably the code you're looking for:

https://github.com/wxt-dev/examples/blob/8d8129d81a4a4a51838a37a8b946a5c03d8f4b6a/examples/react-mantine/entrypoints/content.tsx#L41-L42
