### ISSUE TITLE
invalid signature for browser.tabs.query

### ISSUE THREAD

**Issue by nick-delirium** [wxt-dev/wxt#741]
### Describe the bug

Current signature expects 1 argument, browser API waits for two (options and cb)

### Reproduction

```
const tab = await new Promise<chrome.tabs.Tab>((resolve, reject) => {
  browser.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    if (tabs.length === 0) {
      reject(new Error('No active tab found'));
    } else {
      resolve(tabs[0]);
    }
  });
});
```

returns
`App.tsx:91 Error starting recording: 
Error: Expected at most 1 argument for query(), got 2`

trying to call it with one arg, no matter which, will also result in error

### System Info

```shell
does not matter?

System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 118.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 9.3.0 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
    bun: 1.1.13 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 125.0.6422.176
    Safari: 16.5.1
  npmPackages:
    wxt: ^0.18.6 => 0.18.6
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
webextension-polyfill expects you to use the MV3 promise based API, not the old MV2 callback style.

So do this instead:

```ts
export async function getActiveTab() {
  const tabs = await browser.tabs.query({
    active: true,
    currentWindow: true,
  });
  if (tabs.length === 0) throw new Error('No active tab found');

  return tabs[0];
}
```

**Comment by nick-delirium** [comment]
Hmmm. Yes indeed, you're correct here. Thank you and sorry :)

one more thing (if you don't mind: calling browser.tabCapture.capture(params, stream => ...) inside popup part of code will trigger this on popup window (which is considered part of chrome window) and always fail, but it's not present in other connecting apis (content/background)... What is the best approach here?
![image](https://github.com/wxt-dev/wxt/assets/23126999/292d3d72-e4bf-4088-bcfa-010a6880187c)
