### ISSUE TITLE
Error ECONNREFUSED is thrown on a clean project

### ISSUE THREAD

**Issue by pastukhvladyslav** [wxt-dev/wxt#766]
### Describe the bug

I have just set up a clean project with this command:
`pnpm dlx wxt@latest init test --template react`

When I run `pnpm dev` I get the error after ~30sec:
```
✖ Command failed after 26.8 s
ERROR  connect ECONNREFUSED 127.0.0.1:39925
  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
```

### Reproduction

[test.zip](https://github.com/user-attachments/files/15945106/test.zip)

### Steps to reproduce

1. `pnpm dlx wxt@latest init test --template react`
2. `pnpm dev`

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 5.93 GB / 15.44 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
  Browsers:
    Chromium: 125.0.6422.60
  npmPackages:
    wxt: ^0.18.6 => 0.18.9
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
On discord, people have appearently solved this by restarting their computer, as ridiculous as that seems lol.

I think it must clear out a port that's causing problems? Not sure TBH.

**Comment by pastukhvladyslav** [comment]
The error happens to me only on _Chromium_ on _Linux_.
It works alright on _Windows_ and on _Firefox_ on _Linux_ (when I run `dev:firefox`).
Not yet sure what is wrong though.

**Comment by aklinker1** [comment]
Tried this out today on my ubuntu setup, working for me... If you find out what's causing it, let me know. Otherwise, there's not really anything I can do :/

**Comment by pastukhvladyslav** [comment]
Haven't figured out a good fix yet...

The temporary solution (maybe can be useful to someone) is:
1. Go to `/node_modules/chrome_launcher/dist/chrome-launcher.js`
2. Find `isDebuggerReady` function
3. Find `once('error', ...`
4. Replace `reject(err);` with `resolve();`

**Comment by ulises-castro** [comment]
In my case, I set up persistent data in the browser, so I deleted chrome-data folder and that's it, it's working again.

**Comment by sdz123** [comment]
remove follow config in wxt.confis.js:
  webExt: {
   chromiumArgs: ['--user-data-dir=./.wxt/browser-data'],
  }
it works for me

**Comment by LauGau** [comment]
> remove follow config in wxt.confis.js: webExt: { chromiumArgs: ['--user-data-dir=./.wxt/browser-data'], } it works for me

I confirm that it's working, but then it wipes out everything; local storage, chrome profile, etc...
I'm wondering if there is a better way...

**Comment by rpayanm** [comment]
I was able to fix this, please check it here:
https://github.com/wxt-dev/wxt/issues/460#issuecomment-3041673360
