### ISSUE TITLE
ContentScript at MAIN world: browser-polyfill.js: "Error: This script should only be loaded in a browser extension."

### ISSUE THREAD

**Issue by thomasf1** [wxt-dev/wxt#770]
### Describe the bug

I´m trying a simple content script in the main context, however it fails by importing the polyfill which should only be included in the extension contexts.

Maybe it´s just me doing something wrong, I´m quite new to extensions. But it seems that world: 'MAIN' should not bundle the Polyfill?

### Reproduction

content.ts:
```javascript
import {createIntegratedUi} from 'wxt/client'

export default defineContentScript({
  matches: ['<all_urls>'],
  runAt: 'document_start',
  world: 'MAIN',
  matchAboutBlank: true,
  main(ctx) {
    console.log('*** main', ctx)
    const ui = createIntegratedUi(ctx, {
      position: 'inline',
      onMount: (container) => {
        // Append children to the container
        console.log('** ** createIntegratedUi-main')
        const app = document.createElement('p');
        app.textContent = '...';
        container.append(app);
      },
    });

    // Call mount to add the UI to the DOM
    ui.mount();
  },
});
```

Error (browser console):
```
browser-polyfill.js:26 Uncaught Error: This script should only be loaded in a browser extension.
    at browser-polyfill.js:26:11
    at browser-polyfill.js:5:5
    at browser-polyfill.js:13:1
    at browser-polyfill.js:1268:2
    at content.ts:24:2
```

### Steps to reproduce

Add the above to a default project and run

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 137.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - /opt/homebrew/bin/npm
    pnpm: 9.2.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.114
    Chrome Canary: 128.0.6555.0
    Safari: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Main world content scripts can't use any extension APIs, so they can only import WXT APIs from `wxt/sandbox`. Hard to tell with auto-imports, but `createIntegratedUi` uses the extension APIs.

You can add the UI to the DOM yourself if you're in a main world acript
