### ISSUE TITLE
The error "Saved groups are not editable" is thrown frequently.

### ISSUE THREAD

**Issue by aiktb** [wxt-dev/wxt#781]
### Describe the bug

[Chromium currently does not support reloading tabs for "saved groups".](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/2RO1vp-8lqE)
![image](https://github.com/wxt-dev/wxt/assets/104723527/40954627-ade5-4463-a1b6-93f9c53fa266)

The error is due to `tabs.reload` in the following line of code.

https://github.com/wxt-dev/wxt/blob/faffe20a620ca70aad8cde41cd977ddc396a94c6/packages/wxt/src/virtual/utils/reload-content-scripts.ts#L84

A method to determine if a tab is in a saved group does not exist, so can it be caught?

### Reproduction

No need zip.

### Steps to reproduce

Add the page that injects the content script to the "saved group" and then trigger the content script update.

![image](https://github.com/wxt-dev/wxt/assets/104723527/8b85072d-c989-4a05-b2b8-c659ca0efe5a)

![image](https://github.com/wxt-dev/wxt/assets/104723527/afd3839e-edd3-471e-883a-9545142de528)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (18) x64 Intel(R) Core(TM) Ultra 5 125H
    Memory: 11.52 GB / 15.43 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
  npmPackages:
    wxt: ^0.18.6 => 0.18.10
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Whelp that sucks. OK, I'll try catch it. I don't want to silence it, so I'll change it to a warning log. Otherwise people will ask me why the tab isn't reloading automatically after saving a file.
