### ISSUE TITLE
Use non-hidden dirs for output directory

### ISSUE THREAD

**Issue by aryzing** [wxt-dev/wxt#783]
### Feature Request

By default, the output dir is called `.output`, making it a hidden directory. It is quite inconvenient to reference this dir or search for it with a file explorer when trying to load unpacked extensions. Is there much of a benefit in having it be a hidden directory given it can be easily excluded with git?

### What are the alternatives?

Use any other popular non-hidden name, like `output`, `out`, `dist`, `build`.

**Comment by aklinker1** [comment]
No, I don't plan on changing this. Nuxt and Nitro uses `.output`.

I don't provide configuration for changing this setting, but there is an internal value you can change via the module API:

https://wxt.dev/guide/go-further/reusable-modules.html#actually-doing-something

**Comment by Nithur-M** [comment]
Hey @aklinker1 

How do you suggest testing the extension locally while developing? Because currently I am facing the same blocker as OP.

I am coming from Plasmo background.

Or is there any better way?

Thanks.

**Comment by aklinker1** [comment]
At some point, I must have changed my mind lol. Either show hidden files, or use `outDir: "dist"` to change it to a non-hidden directory.
