### ISSUE TITLE
Don't use `webextension-polyfill` by default

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#784]
### Feature Request

Currently, WXT's `browser` is the default export from `webextension-polyfill`. However, now that Chrome doesn't support MV2 extensions, and Firefox has MV3 support, it's not really doing anything anymore... It's main features were:

1. Add promise-based API to chrome's MV2 implementation
2. Providing a single global variable so you don't have to use both `chrome` and `browser`

However, those two features are no longer necessary:

1. Add promise-based API to chrome's MV2 implementation
   - Firefox and other browsers all support MV3 now, and Firefox's MV2 APIs are already promise-based. So you can write promise-based API calls and it will work on all browsers
2. Providing a single global variable so you don't have to use both `chrome` and `browser`
   - All browsers now support the `chrome` global, but WXT will continue to re-export it's own `browser` variable.

So how is WXT going to remove the polyfill?

First, it will provide some flag in config to continue using it if you want, but the polyfilll will not be the default. It will be moved to an optional peer-dependency so it's not even installed if it doesn't have to be.

Second, we'll be replacing `@types/webextension-polyfill` with `@types/chrome`. This will address lots of the problems with missing API and manifest types, at the cost of not being able to use type errors to know what's supported by all browsers and what's not. Either way, both ways have problems, but I think `@types/chrome` will provide a better DX.

Finally, we'll need to update `wxt/testing` to make sure it properly fakes the API. Not sure if `@webext-core/fake-browser` is still the best option for providing a fake version during development. _Edit: Been looking and can't find anything else on NPM_

So in summary, you shouldn't have to make any changes to your source code or tests. That's the goal, to make this transition as seemless as possible. You'll be able to opt into using the polyfill from `wxt.config.ts`. There will be breaking changes to types, don't think I can get around that.

If you use a library that includes the polyfill, it will work just fine, the polyfill will still be included.

#### Is your feature request related to a bug?

https://github.com/wxt-dev/wxt/issues/506 - The `vite-node` solution works well, but the polyfill is getting in the way.

https://github.com/wxt-dev/wxt/issues/521 - Improve manifest typing

https://github.com/wxt-dev/wxt/issues/299 - Improve runtime API typing

### What are the alternatives?

N/A

### Additional context

- Discord: https://discord.com/channels/1212416027611365476/1253736416425410560

**Comment by aiktb** [comment]
Does the default build target for `wxt build -b firefox` change to MV3?

**Comment by aklinker1** [comment]
> Does the default build target for `wxt build -b firefox` change to MV3?

Good call out... I'm going to say no for now. MV2 for Firefox is a better user experience and there are no problems with dev mode (MV3 CSP blocks loading scripts from localhost). So I'm a little hesitant to switch the default.

Do you want to switch to MV3 by default? If so, what are your reasons @aiktb

**Comment by aiktb** [comment]
https://github.com/mozilla/webextension-polyfill/issues/210

`webextension-polyfill` causes shorter stack traces, I've tripped over this issue several times and recently ran into it again.
It makes debugging the extension more difficult.
![image](https://github.com/wxt-dev/wxt/assets/104723527/1b618e9e-0cca-4923-acc9-fc5b988a9c40)
![image](https://github.com/wxt-dev/wxt/assets/104723527/2ce386db-217b-48c4-b9d1-774a07ae96fc)

**Comment by aiktb** [comment]
`chrome.tabs.query` is not compatible with firefox ...
I'm afraid that using the chrome namespace alone won't support firefox for this reason.

popup.html:
![image](https://github.com/user-attachments/assets/6f8b1e06-e2e7-4ea1-a88e-1de679f9ec34)

**Comment by aklinker1** [comment]
Perfect, thanks for sharing! I'm planning on manually polyfill-ing things like this so it just works. If you notice anything else, please share!

**Comment by aiktb** [comment]
> `chrome.tabs.query` is not compatible with firefox ... I'm afraid that using the chrome namespace alone won't support firefox for this reason.
> 
> popup.html: ![image](https://private-user-images.githubusercontent.com/104723527/348484162-6f8b1e06-e2e7-4ea1-a88e-1de679f9ec34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzY4NTcsIm5iZiI6MTcyMTAzNjU1NywicGF0aCI6Ii8xMDQ3MjM1MjcvMzQ4NDg0MTYyLTZmOGIxZTA2LWUyZTctNGVhMS1hODhlLTFkZTY3OWY5ZWMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwOTQyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzk0OGU5ZTRlZjI3YzZhNTgwYjUxMGQ2NzI5YjA3YmI5NWQyZDgyODI4MWZlZTNjOGY1MGM4YjYxZmJkNjA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AsQMZe_AO0n-JJnpR2lLLYfeY4mwLCyyvFPAuelNq9k)

The essence of the problem I found is that the API under the `chrome` namespace in Firefox MV2 is based on callbacks, it's not an alias for `browser`.
![image](https://github.com/user-attachments/assets/719ae7e3-9afa-44c5-8555-50fca2fb576a)

**Comment by aklinker1** [comment]
Alright, I've done some refactoring and added an option to preview what the API will look like in `v0.19.0`.

1. Enable the option
   ```ts
   export default defineConfig({
     extensionApi: "chrome",
   });
   ```
2. Install `@types/chrome` and prepare the project
   ```sh
   pnpm i -D @types/chrome
   pnpm wxt prepare
   ```

To make sure the polyfill has been removed, do a build analysis:

```sh
pnpm build --analyze --analyze-open
```

There should be no other code changes required. Your extension should work the same way as before. If you run into issues, either at runtime or with types, please report them!

**Comment by aklinker1** [comment]
I will also add, as of 0.19.0, the manifest type in your `wxt.config.ts` will still be using the type from the polyfill. Once the polyfill is no longer the default, the type will be updated.

**Comment by aklinker1** [comment]
Closing this issue in favor of https://github.com/wxt-dev/wxt/issues/868
