### ISSUE TITLE
wxt-starter@workspace can't be built (vite package issue?)

### ISSUE THREAD

**Issue by mearleycf** [wxt-dev/wxt#803]
### Describe the bug

This is a on a clean install. I ran the `pnpm dlx wxt@latest init fillit` command to create my project. Went fine. Chose svelte as template. Chose yarn as package manager. It said WXT project created with svelte template. Went into the fillit directory. ran yarn install. The yarn install is failing:
[build.log](https://github.com/user-attachments/files/16116540/build.log)

```
➤ YN0007: │ wxt-starter@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ wxt-starter@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/lq/b2s6mqss6t1c2mttbrtwxvz40000gn/T/xfs-f2dce75f/build.log)
➤ YN0000: └ Completed in 0s 939ms
➤ YN0000: · Failed with errors in 1s 154ms
```

I've attached the referenced build log. Basically, it's saying:
```
Required package: vite (via "vite/package.json")
Required by: @sveltejs/vite-plugin-svelte-inspector
Ancestor breaking the chain: @wxt-dev/module-svelte
```

So, yeah--that's it. I'm stuck, not sure what's the next step on this one. I attached the build log with the detailed message. 

### Reproduction

https://github.com/mearleycf/fillit

### Steps to reproduce

From scratch:

1. pnpm dlx wxt@latest init fillit
2. Choose a template: svelte
3. Package manager: yarn
4. <--WXT project created with the svelte template
5. cd fillit
6. yarn install
7. <--error happens at this stage, and every consecutive time I run yarn install

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 166.59 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.14.0 - ~/.local/share/mise/installs/node/latest/bin/node
    Yarn: 4.3.1 - /opt/homebrew/bin/yarn
    npm: 10.8.1 - ~/.local/share/mise/installs/node/latest/bin/npm
  Browsers:
    Safari: 17.5
    Arc 1.49.1
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Thanks, I'll get back to you soon.

Probably something to do with pnp, probably importing vite inside that module with declaring it as a dependency...

Will check it out when I get home

**Comment by mearleycf** [comment]
I have only had bad experiences with PnP. Previously it was working in Astro projects. I'll switch over the nodeLinker setting to modules so it works more like node and see if it works.

**Comment by mearleycf** [comment]
OK--I can confirm that adding `nodeLinker: node-modules` to a .yarnrc.yml file in the project root fixed this issue.

**Comment by aklinker1** [comment]
There's probably a problem with PNPM as well, I'll get it fixed, it's a valid issue

**Comment by aklinker1** [comment]
This isn't a problem with PnP, dependencies are listed properly. I think you may have multiple versions of vite installed in your workspace? Or you may need to install vite as a direct dependency in your project to specify a version? Not sure, I haven't been following whatever yarn is doing.

**Comment by mearleycf** [comment]
I'll be honest with you, I just switched over to pnpm for the project and moved on :) too frustrating to fight with yarn.
