### ISSUE TITLE
Exclude Zod

### ISSUE THREAD

**Issue by HotariTobu** [wxt-dev/wxt#824]
### Feature Request

We cannot use [Zod](https://zod.dev/) because of [Entrypoint Side Effects](https://wxt.dev/guide/go-further/entrypoint-side-effects.html) so I request to exclude Zod from the effects.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

Manual validation like with `typeof`, `instanceof`, and so on.

### Additional context

```
WXT 0.18.13
```

**Comment by aklinker1** [comment]
Ahh, I see. Added to https://github.com/wxt-dev/wxt/issues/506, going to close this one as a duplicate.

For now, you should put the zod schemas in a different file and import them or define them inside the `main` function. Either option should work for the short-term.

**Comment by HotariTobu** [comment]
The error occurs even if I define zod schemas in other script files and import them.

**Comment by aklinker1** [comment]
Don't use the schemas outside the main function and it will work
