### ISSUE TITLE
How to open the plugin in an already open browser instead of launching a new browser when run "pnpm dev"

### ISSUE THREAD

**Issue by mundane799699** [wxt-dev/wxt#831]
### Feature Request

How to open the plugin in an already open browser instead of launching a new browser when run "pnpm dev". Because the page I debugged requires an account to log in. And logging in requires someone to scan a code. This is quite troublesome. If opened in the opened browser，I don't need to log in everytime because the token is saved to the browser on first login.

#### Is your feature request related to a bug?

N/A

**Comment by aklinker1** [comment]
See "Disable Opening Browser" and "Profile Customization" sections.

https://wxt.dev/guide/directory-structure/web-ext-config.html#disable-opening-browser
