### ISSUE TITLE
Automatically generate logos in correct sizes

### ISSUE THREAD

**Issue by Timeraa** [wxt-dev/wxt#850]
### Feature Request

Was thinking it would be a nice feature if wxt can take a path to the logo and automatically generated images in the correct sizes for all the stores (512x512, 128x128 etc.) 

Just a small discussion point because I would definitely appreciate it but not sure how others / how much value it would add to the project

**Comment by aklinker1** [comment]
Someone else mentioned it as well, I'm down! 

https://github.com/wxt-dev/wxt/discussions/782#discussioncomment-10032202

They made a module to make the icon grayscale during dev, which we probably want to do as well.

**Comment by Timeraa** [comment]
Should I maybe make a module for it and merge it into wxt @aklinker1?

**Comment by aklinker1** [comment]
Yes please!

**Comment by aklinker1** [comment]
Alright, this is live! https://www.npmjs.com/package/@wxt-dev/auto-icons

I'll make an announcement in discord about this once I've fixed the issues with v0.19.0...

**Comment by aleclarson** [comment]
What's the recommended icon size when using auto-icons? 128x128?

**Comment by 1natsu172** [comment]
@aleclarson The store requirement is 128. But the original image can be larger because it is automatically converted.
https://developer.chrome.com/docs/webstore/images?hl=en#icons

**Comment by Timeraa** [comment]
> What's the recommended icon size when using auto-icons? 128x128?

I use 1024x1024 icons but anything should work really
