### ISSUE TITLE
Process not found error after creating app.config.ts

### ISSUE THREAD

**Issue by leszekkrol** [wxt-dev/wxt#862]
### Describe the bug

I’m encountering an issue after creating the app.config.ts file as described in the documentation for handling environment variables. Specifically, I’m getting a process not found error. Here’s what I’ve done:

### Reproduction

1. Created a .env file with the following content:
```
VITE_BUG_REPORTING_DISABLED=true
VITE_API_KEY=...
```

2.	Created the app.config.ts file with the following content:
```
declare module 'wxt/sandbox' {
  export interface WxtAppConfig {
    bugReportingDisabled: boolean;
    apiKey?: string;
  }
}

export default defineAppConfig({
  bugReportingDisabled: process.env.VITE_BUG_REPORTING_DISABLED === 'true',
  apiKey: process.env.VITE_API_KEY,
});
```

3.	Followed the documentation which states that you can access process.env.VITE_* anywhere in your runtime code.
However, upon running the application, I get the following error:

`Error: process not found`

### Steps to reproduce

Steps to Reproduce

	1.	Create a .env file with the specified variables.
	2.	Create the app.config.ts file with the above configuration.
	3.	Run the application.

### System Info

```shell
"dependencies": {
    "vue": "^3.4.33",
    "vue-router": "^4.4.0"
  },
  "devDependencies": {
    "@wxt-dev/module-vue": "^1.0.0",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.39",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.5.3",
    "vue-tsc": "^2.0.26",
    "wxt": "^0.18.15"
  }
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Timeraa** [comment]
Use `import.meta.env.xyz`

**Comment by aklinker1** [comment]
@Timeraa is correct, use `import.meta.env.VITE_*` instead. I updated the docs, not sure why I wrote `process.env.VITE_*` originally...

**Comment by leszekkrol** [comment]
@aklinker1 Thanks, I managed to solve the problem using `import.meta.env.VITE_*` but didn't get a chance to write a comment. Nevertheless, @aklinker1 it's great that the documentation got updated. 😄
