### ISSUE TITLE
[modules] Polluted manifest in successive `build:manifest` calls

### ISSUE THREAD

**Issue by Timeraa** [wxt-dev/wxt#863]
### Describe the bug

Just noticed that in dev mode if you change a file like the `background.ts` in the demo extension the `build:manifest` hook of the new auto-icons module sends the icons property found console log which is due to the `manifest.icons` being filled out by the module the first dev run but the build:manifestGenerated hook should always get the "clean" manifest only the generated steps at that point in time

### Reproduction

```sh
cd packages/wxt-demo
pnpm dev
# Save entrypoints/background.ts and you'll see the auto-icon warnings
```

### Steps to reproduce

1. Run dev in the demo extension
2. Notice no "icons property found" log
3. Update background.ts
4. Notice "icons property found" log

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 217.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 8.15.9 - /usr/local/bin/pnpm
    bun: 1.1.1 - ~/.bun/bin/bun
  Browsers:
    Safari: 17.5
  npmPackages:
    wxt: workspace:* => 0.19.0
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Released in [`v0.19.17`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.17)
