### ISSUE TITLE
Since version 0.19.0, the `build` command's env has been set to `DEV: true`.

### ISSUE THREAD

**Issue by 1natsu172** [wxt-dev/wxt#873]
### Describe the bug

I'm reporting an error encountered when trying to bump from version 0.18.15 to 0.19.x.

The error occurs in the production build during the React render, with the message `jsxDevRuntimeExports.jsxDEV is not a function`. This error doesn't occur in development.

After inspecting the output, it seems there's an issue with the environment. Debugging the environment shows that while the `MODE` is set to `production`, `import.meta.env.DEV` is still `true`.

I suspect this inconsistency might be causing discrepancies in the bundled output.

##### with `pnpm build`

![image](https://github.com/user-attachments/assets/7c7504b4-b051-4e8e-a23b-f5a387cf4214)

#### with `pnpm dev`

![image](https://github.com/user-attachments/assets/a37b0720-416d-4a3c-84cc-b576ae3ec743)

### Reproduction

https://github.com/wxt-dev/examples/pull/2

### Steps to reproduce

```
cd examples/react-content-script-ui
pnpm i
```

**no problem**
`pnpm dev`

**has problem**
`pnpm build`

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 144.42 MB / 8.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.16.0 - ~/.asdf/installs/nodejs/20.16.0/bin/node
    npm: 10.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.8 - ~/.asdf/installs/nodejs/20.16.0/bin/pnpm
    Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 126.0.6478.183
    Safari: 17.2.1
  npmPackages:
    wxt: 0.19.1 => 0.19.1
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aiktb** [comment]
I noticed the same issue, with `react.development.js` appearing in my production build.

**Comment by yebei199** [comment]
me too

**Comment by aklinker1** [comment]
> I noticed the same issue, with react.development.js appearing in my production build.
> Significantly increased build size.

@aiktb @yebei199 I can't reproduce this with the reproduction above. Can one of you create a new issue with a reproduction?

**Comment by yebei199** [comment]
[my-trans-master.zip](https://github.com/user-attachments/files/16404117/my-trans-master.zip)
This is my project. Removing 'jiti' will replicate the previous results.

**Comment by 1natsu172** [comment]
@aklinker1 Sorry, it seems there may be some confusion between issues. I haven't see the build size increase problem. @yebei199 says "me too" because I guided from this discussion(#874), and both of us are mainly referring to the React runtime error issue.

Are you not able to reproduce the React `jsxDev` runtime error and the environment inconsistency with the https://github.com/wxt-dev/examples/pull/2 on your machine?

@yebei199 Are you facing both the React runtime error and an increase in bundle size? Or only the runtime error?

---

Just to clarify, here is a screenshot that the bundle size hasn't increased in my machine at https://github.com/wxt-dev/examples/pull/2.

| 0.18.7 | 0.19.1 |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/575a141a-b27d-436d-baca-6243bb677b54) | ![image](https://github.com/user-attachments/assets/9fcda7d7-62c6-4cf4-be22-f6384484a848) |

**Comment by aklinker1** [comment]
Alright, this issue is also cause by `vite-node`... When I call `vite.createServer`, vite is defaulting the environment variable to `"development"`, which is then used by future vite builds, causing the error. Fix coming soon.

**Comment by yebei199** [comment]
@1natsu172 I think only runtime error , but I haven't run any tests on it, but feel free to download my project and test it.

**Comment by aklinker1** [comment]
Fix released: https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.2

**Comment by 1natsu172** [comment]
@aklinker1 Thanks for great speed fix. I tried it right away on my project, and the issue is resolved. The `jsxDev` runtime error also has been resolved. That's awesome!

![image](https://github.com/user-attachments/assets/6bcaf796-0347-48a0-9a71-0416cffa97a2)
