### ISSUE TITLE
Uncaught (in promise) ReferenceError: window is not defined

### ISSUE THREAD

**Issue by amal** [wxt-dev/wxt#883]
### Describe the bug

Tried with 0.19.2 and 0.18.15.

This error persists both in dev and prod builds.

<img width="639" alt="image" src="https://github.com/user-attachments/assets/236456c2-5bcf-4766-9e87-bc2a6f83611e">

### Reproduction

[Archive.zip](https://github.com/user-attachments/files/16433115/Archive.zip)

### Steps to reproduce

Just run the extension form attached archive and see.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 76.47 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - ~/.nvm/versions/node/v22.4.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v22.4.0/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v22.4.0/bin/pnpm
    bun: 1.1.18 - ~/.bun/bin/bun
  Browsers:
    Chrome: 127.0.6533.72
    Safari: 17.5
  npmPackages:
    vite: ^5.3.5 => 5.3.5 
    wxt: ^0.18.2 => 0.18.15 
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by amal** [comment]
Another issue is that some styles are lost in prod build, but it probably can be workarounded.

**Comment by amal** [comment]
Tried to not set a Vite version in the `package.json`, but with no luck.

**Comment by aklinker1** [comment]
Interesting error, thanks for reporting, will look into this soon!

**Comment by 1natsu172** [comment]
It looks like the might be importing files related to `typesafe-i18n` in `background.ts`. Some modules that depend on the `window` object are being unintentionally included?

**Comment by aiktb** [comment]
I have encountered this error, which is actually an error of vite dynamic import failure. Let me guess, you used dynamic import in the background.

**Comment by amal** [comment]
I've tried to remove `typesafe-i18n` usage from the background entrypoint. It helped to change things slightly, but now I have another error for dev build:

`Uncaught (in promise) Error: Not implemented: file:// pattern matching. Open a PR to add support
Context`
<img width="654" alt="image" src="https://github.com/user-attachments/assets/6e6126d9-07ef-4f54-8411-6af152008e9b">

Nothing is changed for the prod build, though:
<img width="634" alt="image" src="https://github.com/user-attachments/assets/cc2a4c2f-9a42-43c6-a793-2e168d38771a">


Why are these things even happening?

Also, `typesafe-i18n` maybe can use a `window` somewhere inside, but it's not necessary to work.  Can it be just ignored?  The original error is happening not in the `typesafe-i18n` but somewhere in the code from WXT or Vite.

**Comment by amal** [comment]
Even for empty `background.ts` entrypoint with only `console.log('Hello background!');` it still shows this error.

But I've found how to work around this issue: to remove `type: 'module'` from the background entrypoint config.  Probably something is wrong there when the entrypoint is declared as a module.

**Comment by 1natsu172** [comment]
@amal In the repro zip you submitted, simply commenting out `i18next` results in both dev and prod working fine on my machine. Have you made any other changes?

**Comment by amal** [comment]
Actually, I left i18next as is and just commented out `type: 'module'` in the entrypoint declaration.

<img width="666" alt="image" src="https://github.com/user-attachments/assets/2db2d2f6-7366-4609-b6aa-88023b851376">

**Comment by 1natsu172** [comment]
@amal Wait...whether or not you keep `type: 'module'`, I don't encounter the error on my machine. Simply removing the `i18next` prevents the error. So…try running `rm -rf node_modules`, then `pnpm store prune` and again `pnpm i`.

Also, according to @aiktb's theory, the `i18n-utils.async.ts` in your project dynamically imports the loader, which is at least a point of concern.

Additionally, your project uses hooks to modify quite a few JS files and manifests, which could potentially be causing environmental differences. 🤔

**Comment by 1natsu172** [comment]
@amal Sorry, I was misread your message. If you keep `i18next` and set `type: "module"`, it will output chunks in ESM format. Without `type: "module"`, it defaults to CJS format, resolving as static objects, and thus, the error doesn't occur.

> bundled with `type: "module"`(ESM)
![image](https://github.com/user-attachments/assets/905df1bb-85d6-4b72-8fbe-23957066375a)

> bundled without `type: "module"`(CJS)
![image](https://github.com/user-attachments/assets/cabad5f6-14b7-4ee8-abe9-ec71b845144d)

Dynamic import isn't support in the background script, it might be better to use synchronous implementations instead.

**Comment by amal** [comment]
@1natsu172, thank you. Yes, I plan to use only the synchronous implementation.

**Comment by aklinker1** [comment]
Yeah, so this is one of the reasons I don't recommend using a i18n library... You end up either having to fetch JSON files asynchronously or include all your translations in each individual entrypoint bundle :/

You do get some benefits, like being able to switch languages, but other than that... it just makes DX bad.

I swear one day I'll finish #758...

**Comment by aklinker1** [comment]
So just to clearify, the problem was dynamic imports in a background marked as `type: "module"`, right?

Solutions:
1. Don't use dynamic imports
2. Don't use `type: "module"`

If we need to keep this open, feel free to reopen!

**Comment by 1natsu172** [comment]
Right. I've checked that using dynamic imports in the background(with `type: "module"`) causes the same issue also in my project.

This is a trade-off.
- Can't avoid dynamic imports => avoid using `type: "module"` in the background
- Want to use `type: "module"` in the background => avoid using dynamic imports
