### ISSUE TITLE
Firefox: Sometimes the content script is invalidated almost immediately after execution

### ISSUE THREAD

**Issue by hikiko4ern** [wxt-dev/wxt#884]
### Describe the bug

There is some strange floating bug - sometimes `ContentScriptContext` invalidates itself: content script starts execution, and after a short time `ctx.onInvalidated` is triggered.

Judging by the code, `ContentScriptContext` should work like this:
1. `#stopOldScripts` calls `window.postMessage`, which should invalidate all old scripts by the `wxt:content-script-started` message
2. `#listenForNewerScripts` is called in `setTimeout`, which subscribes to `wxt:content-script-started` (it is subscribed via `setTimeout` in order not to catch its own message sent from `#stopOldScripts`)

Depending on the site and the page, usually the correct order of their triggering is preserved (first the message from `#stopOldScripts` is posted, and only then the context subscribes to `#listenForNewerScripts`), but sometimes the message from `#stopOldScripts` comes later - first the `#listenForNewerScripts` listener is added, and then this listener catches the message sent from `#stopOldScripts` of the listener's own context.

I tried test this on different sites and devices, and:
- it seems that the heavier the JS on a site, the more likely it is to catch the bug
  for example, on https://example.com I've never been able to reproduce it, but on https://openweathermap.org I get it almost every time
- bug is reproducible in different versions of Firefox (I tried FF and LibreWolf 128.0.3, FF 101.0.1, all with clean profiles without extensions), but in Chrome I never got it
- it can be reproduced both with `runAt = document_idle` and with `runAt = document_start`

### Reproduction

Repo: https://github.com/hikiko4ern/wxt-invalidated-cs

There's a commit that adds a patch with additional logs and a unique UUID for clarity, but the bug is reproducible even without it.

### Steps to reproduce

1. `pnpm i`
2. `pnpm dev:firefox`
3. load extension
4. open any page with heavy enough JS

   I've been able to reproduce on pages:
   - https://openweathermap.org (about 90% of the time)
   - https://coub.com/view/zxmi7 (about 50% of the time)

5. open the console and see if there is any log about script invalidation

   if it is invalidated, the logs will show this:
   ```
   [wxt] stopping old scripts 0fbc90a3-df51-4620-9413-8e29a46d6be4
   -- main --
   [wxt] will attach newer scripts listener 0fbc90a3-df51-4620-9413-8e29a46d6be4
   [wxt] invalidated from 0fbc90a3-df51-4620-9413-8e29a46d6be4
   invalidated
   [wxt] Content script "content" context invalidated
   ```
   otherwise it will be like this:
   ```
   [wxt] stopping old scripts c3b0d205-883f-4b21-98c4-5cc0f455015f
   -- main --
   [wxt] will attach newer scripts listener c3b0d205-883f-4b21-98c4-5cc0f455015f
   ```

6. try refreshing the page a few times until the bug is reproduced

### System Info

```shell
System:
  OS: Linux 5.15 Debian GNU/Linux trixie/sid
  CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
  Memory: 53.69 GB / 64.76 GB
  Container: Yes
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.15.1 - /mnt/wslg/runtime-dir/fnm_multishells/27245_1722387911992/bin/node
  npm: 10.7.0 - /mnt/wslg/runtime-dir/fnm_multishells/27245_1722387911992/bin/npm
  pnpm: 9.6.0 - /mnt/wslg/runtime-dir/fnm_multishells/27245_1722387911992/bin/pnpm
  bun: 1.1.8 - ~/.bun/bin/bun
Browsers:
  Chrome: 127.0.6533.72
  Chromium: 123.0.6312.105
npmPackages:
  wxt: ^0.19.1 => 0.19.2
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
@hikiko4ern Can you see if `wxt@0.19.3-alpha1` fixes the problem on your computer? 

Rather than using a timeout, I changed it to just ignore the first event. https://github.com/wxt-dev/wxt/pull/895

**Comment by aklinker1** [comment]
@hikiko4ern Can you see if `wxt@0.19.3-alpha2` fixes the problem on your computer? 

Rather than using a timeout, I changed it to just ignore the first event, whenever it is fired. https://github.com/wxt-dev/wxt/pull/895

**Comment by hikiko4ern** [comment]
Yep, it doesn't reproduce with the alpha.

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.3
