### ISSUE TITLE
Use `navigator.clipboard` api but an error was reported "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by lapse12** [wxt-dev/wxt#894]
### Describe the bug

I tried the navigator. clipboard.writeText and navigator. clipboard.write api, which work well in the IDE, but I encountered error during testing them
```
TypeError: Cannot read properties of undefined (reading 'writeText')
```

<img width="822" alt="image" src="https://github.com/user-attachments/assets/845db656-7ba9-47e8-ac2a-f19a2772fb0f">
<img width="852" alt="image" src="https://github.com/user-attachments/assets/44df4eaa-9390-4065-9a8b-ae2dfcab1ad1">

### Reproduction

[minimal.zip](https://github.com/user-attachments/files/16466473/minimal.zip)

### Steps to reproduce

pnpm i
wxt

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 78.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.4.1
  npmPackages:
    wxt: ^0.19.1 => 0.19.2
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
I'm gonna close this as it's not an issue with WXT, but a question about how to use the clipboard API in general.
