### ISSUE TITLE
`.wxt/tsconfig.json` is cleared and overwritten on rebuild

### ISSUE THREAD

**Issue by hikiko4ern** [wxt-dev/wxt#897]
### Describe the bug

When rebuilding, `findEntrypoints` is called, which overwrites `.wxt/tsconfig.json` with the `{}`:
https://github.com/wxt-dev/wxt/blob/97aa173f7efbbc6ad1f0ad45e7afadbd9e56b351/packages/wxt/src/core/utils/building/find-entrypoints.ts#L39
which is later overwritten in `generateTypesDir` with the newly generated content:
https://github.com/wxt-dev/wxt/blob/d79d7ed7783e9d0fa3c311a6757dc1a26eba4042/packages/wxt/src/core/utils/building/generate-wxt-dir.ts#L51

For a large enough project, it may take 1-2 seconds between two file writes. The TypeScript Server, which watches for changes to `.wxt/tsconfig.json`, will see the first change to `{}` (from `findEntrypoints`) and rebuild the project, and since `.wxt/wxt.d.ts` will not be included in the project, the code editor will show errors like
> Cannot find name 'defineContentScript'. ts(2304)

until the TS project is rebuilt again after writing the generated `.wxt/tsconfig.json` from `generateTypesDir`.

This is what it looks like in the code editor:

https://github.com/user-attachments/assets/5b4b9e40-ed87-4c11-bf1c-d36270ee17e9

---

I have tried changing (https://github.com/hikiko4ern/wxt/commit/5e9d43edd9b917b3e03e4cff3e8f9c24ff92ea43) the `fs.writeJson` flag from `w` to `wx` so that the file is not overwritten when present, and the problem does not reproduce and the tests pass, but I'm not sure if that breaks something.

### Reproduction

https://github.com/hikiko4ern/wxt-tsconfig-truncated

### Steps to reproduce

1. `pnpm i`
2. `pnpm dev`
3. save any file to trigger rebuild (e.g. `entrypoints/dummy1.content.ts`)

### System Info

```shell
System:
  OS: Linux 5.15 Debian GNU/Linux trixie/sid
  CPU: (32) x64 AMD Ryzen 9 7950X3D 16-Core Processor
  Memory: 54.69 GB / 64.76 GB
  Container: Yes
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.15.1 - /mnt/wslg/runtime-dir/fnm_multishells/13782_1722726260960/bin/node
  npm: 10.7.0 - /mnt/wslg/runtime-dir/fnm_multishells/13782_1722726260960/bin/npm
  pnpm: 9.6.0 - /mnt/wslg/runtime-dir/fnm_multishells/13782_1722726260960/bin/pnpm
  bun: 1.1.8 - ~/.bun/bin/bun
Browsers:
  Chrome: 127.0.6533.72
  Chromium: 123.0.6312.105
npmPackages:
  wxt: ^0.19.3 => 0.19.3
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Great find! I forgot about that line, was very confused when you linked to it lol. Yeah, the `wx` change should be fine!

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.4
