### ISSUE TITLE
`browser` is not defined in svelte

### ISSUE THREAD

**Issue by sacrosanctic** [wxt-dev/wxt#911]
### Describe the bug

`'browser' is not defined svelte(missing-declaration)`

The above message appears when using `browser` inside a svelte file.

### Reproduction

[wxt.zip](https://github.com/user-attachments/files/16573165/wxt.zip)

### Steps to reproduce

```bash
pnpm dlx wxt@latest init .
> choose svelte
> choose pnpm
```
open `.\src\entrypoints\popup\App.svelte`
add `{browser.runtime.id}` to Line 5
```bash
pnpm i
pnpm dev
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 17.64 GB / 31.86 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.7.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Works just fine for me:

<img width="440" alt="Screenshot 2024-08-12 at 9 23 04 AM" src="https://github.com/user-attachments/assets/1c28ff13-0832-4741-82f6-ace8b6abddde">

###### App.svelte

```diff
<script lang="ts">
  import svelteLogo from '../../assets/svelte.svg'
  import Counter from '../../lib/Counter.svelte'
</script>

+<p>{browser.runtime.id}</p>
<main>
  <div>
```

[working-example.zip](https://github.com/user-attachments/files/16588210/working-example.zip)

Can you provide screenshots of the error? Where does the error message come from, because I'm not seeing any errors when running `pnpm dev`

**Comment by sacrosanctic** [comment]
![image](https://github.com/user-attachments/assets/38222aeb-cd34-48a9-99b1-548787fece24)

It works, but this warning appears.

**Comment by 1natsu172** [comment]
I am not familiar with svelte but this issue? https://github.com/sveltejs/language-tools/issues/2187
But……it's a warning and the type works, so I guess it's not a problem. 🤔

**Comment by aklinker1** [comment]
Next time, this is what I'm looking for in a reproduction. Don't assume I'm using your editor or that I know about svelte-specific tools like `svelte-check` for checking for type errors...

---

### Describe the bug

There's a typescript type error when I use `browser` in a `.svelte` file's template:

```svelte
<p>{browser.runtime.id}</p>
```

```sh
$ pnpm svelte-check

====================================
Loading svelte-check in workspace: /Users/aklinker1/Development/local/wxt-issue-911
Getting Svelte diagnostics...

/Users/aklinker1/Development/local/wxt-issue-911/src/entrypoints/popup/App.svelte:6:5
Warn: 'browser' is not defined (svelte)

<p>{browser.runtime.id}</p>
<main>


====================================
svelte-check found 0 errors and 1 warning in 1 file
```

### Reproduction

[repro.zip](https://github.com/user-attachments/files/16599723/repro.zip)

### Steps to reproduce

```sh
pnpm i
pnpm svelte-check
```

---

A simple solution is to not use `browser` directly in a template: 

```svelte
<script>
  const id = browser.runtime.id;
</script>

<p>{id}</p>
```

This passes checks. I don't know if there's a way to add the type globally somehow, but with auto-imports enabled, the type is already added to as a global. Seems like a bug with `svelte-check` to me.
