### ISSUE TITLE
Add `zip:*` hooks

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#962]
### Feature Request

Add the following zip hooks:

- `zip:start`
- `zip:extension:start`
- `zip:extension:done`
- `zip:sources:start`
- `zip:sources:done`
- `zip:done`

#### Is your feature request related to a bug?

N/A

### What are the alternatives?

Using a separate script.

### Additional context

I'm trying to write a module that outputs a self-signed XPI file using `web-ext`, and being able to do this in a module would be great.

**Comment by Timeraa** [comment]
I'll take this

**Comment by aklinker1** [comment]
Released in [`v0.19.11`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.11)
