### ISSUE TITLE
offscreen Support

### ISSUE THREAD

**Issue by asasas234** [wxt-dev/wxt#963]
May I ask if you are considering supporting the offscreen feature? I didn't see any explanation in the wxt documentation.

**Comment by 1natsu172** [comment]
@asasas234 The example of an offscreen api can be found here, WXT support it.

- https://github.com/wxt-dev/examples/tree/main/examples/offscreen-document-setup
- https://github.com/wxt-dev/examples/tree/main/examples/offscreen-document-domparser
