### ISSUE TITLE
Feature Request: Allow Option to Disable Incognito Mode on Project Startup

### ISSUE THREAD

**Issue by alwaysCry** [wxt-dev/wxt#965]
### Description
When starting up the project, the browser always starts in Incognito mode by default. This creates limitations for persistent storage technologies like IndexedDB,  as data always cleared when the browser is closed. This makes difficult to test during development.

### Proposed Solution
Provide an option to disable Incognito mode when launching the browser

**Comment by aklinker1** [comment]
Already exists: https://wxt.dev/guide/directory-structure/web-ext-config.html#profile-customization
