### ISSUE TITLE
Removing the "Deployments" section

### ISSUE THREAD

**Issue by okineadev** [wxt-dev/wxt#979]
### Feature Request

I don't know what this section is for at all

![image](https://github.com/user-attachments/assets/928e9eb8-9c57-4368-86cf-7dc3e86a4f5e)

### What are the alternatives?

Leave everything as it was

**Comment by aklinker1** [comment]
I don't know why you can see that - I've already hidden it.

![image](https://github.com/user-attachments/assets/b4d640ba-b747-432f-917c-b5b2b2891c6b)

**Comment by okineadev** [comment]
okay...
