### ISSUE TITLE
Add `/` to `PublicPath` and `browser.runtime.getURL`

### ISSUE THREAD

**Issue by aaronklinker-st** [wxt-dev/wxt#984]
### Describe the bug

Trying to call `browser.runtime.getURL("/")`, but am getting a type error.

### Reproduction

Just add `browser.runtime.getURL("/")` to the vanilla template's background.

### Steps to reproduce

`pnpm tsc --noEmit`

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.18 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/20.10.0/bin/yarn
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 7.33.7 - ~/.asdf/installs/nodejs/20.10.0/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.6
  npmPackages:
    wxt: ^0.19.9 => 0.19.9
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://wxt.dev/guide/installation.html).
- [X] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aklinker1** [comment]
Good first issue for a contributor. Here's the function that needs updated: https://github.com/wxt-dev/wxt/blob/282458748d69556b53c391cfdb2ecdbb6b4ea0f8/packages/wxt/src/core/utils/building/generate-wxt-dir.ts#L75-L115

**Comment by pritesh7098** [comment]
Is this issue still pending? if yes then assign It to me

**Comment by aklinker1** [comment]
@pritesh7098 yup, it's all yours! Thanks 😀

**Comment by aklinker1** [comment]
To test your changes, either run tests

```ts
cd packages/wxt
pnpm test
```

Or prepare the demo extension:

```sh
cd packages/wxt-demo
pnpm wxt prepare
```

**Comment by AndreiHudovich** [comment]
@aklinker1 Hey, Aaron!

Looks like this is still an issue, and I can see, the `AugmentedBrowser` type explicitly omits `getURL`.

What's the reason of itthis Or is it an issue?

![CleanShot 2024-11-13 at 08 57 47@2x](https://github.com/user-attachments/assets/ddf7dfe1-b72a-4a48-81d9-9eeaa5a2535e)

**Comment by nishu-murmu** [comment]
> Good first issue for a contributor. Here's the function that needs updated:
> 
> https://github.com/wxt-dev/wxt/blob/282458748d69556b53c391cfdb2ecdbb6b4ea0f8/packages/wxt/src/core/utils/building/generate-wxt-dir.ts#L75-L115

@aklinker1 I've got the fix but do let me know if anyone's still working on it.
Or else I can create a PR?

**Here's the fix:**
Just have to add root path in `paths` variable in `getPathsDeclarationEntry` function.
This seems to working.

**Comment by nishu-murmu** [comment]
> @aklinker1
> 
> Hey, Aaron!
> 
> Looks like this is still an issue, and as I can see, the `AugmentedBrowser` type explicitly omits `getURL`.
> 
> What's the reason of this? Or is it an issue?
> 
> ![CleanShot 2024-11-13 at 08 57 47@2x](https://private-user-images.githubusercontent.com/3611940/385650918-ddf7dfe1-b72a-4a48-81d9-9eeaa5a2535e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODkyMzUsIm5iZiI6MTczMTQ4ODkzNSwicGF0aCI6Ii8zNjExOTQwLzM4NTY1MDkxOC1kZGY3ZGZlMS1iNzJhLTRhNDgtODFkOS05ZWVhYTVhMjUzNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMDkwODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTg3OTBkM2UwMDRhMTZiNWMwZDgwZTlkMDU5ZTU3ZTY5YjlkOWU5MWQyODcwNWRiMjIxNWVmMzgyNzM4OGYxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Fl-suSNMzTdt28oILLkobCWJXoBDlOlEn9XMLxAdmkQ)

I tried this as well by removing it from `Omit` Type.
But didn't solve the type error we're getting while using `getURL` method for `/` path.

**Comment by aklinker1** [comment]
> Looks like this is still an issue, and as I can see, the `AugmentedBrowser` type explicitly omits `getURL`.
> 
> What's the reason of this? Or is it an issue?
> 
> ![CleanShot 2024-11-13 at 08 57 47@2x](https://github.com/user-attachments/assets/ddf7dfe1-b72a-4a48-81d9-9eeaa5a2535e)

Because the function's types are generated per-project when you run `wxt prepare`. In a WXT project, run the prepare command, then look at `.wxt/types/paths.d.ts`.

If you are missing this function in your project, make sure you've setup typescript properly and ran `wxt prepare`:

https://wxt.dev/guide/essentials/config/typescript.html

**Comment by aklinker1** [comment]
Released in https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.15
