### ISSUE TITLE
Show grayscale extension icon when in development (like Plasmo)

### ISSUE THREAD

**Issue by GorvGoyl** [wxt-dev/wxt#985]
Show greyscale extension icon when working on extension in dev mode (like Plasmo)

https://docs.plasmo.com/framework/icon#development-icon

![screenshot 2024-09-18 at 17 14 43@2x](https://github.com/user-attachments/assets/6d07ff06-1e42-4d6a-83bd-8128ab72c683)

**Comment by 1natsu172** [comment]
@GorvGoyl You can do it with auto-icons module. https://github.com/wxt-dev/wxt/tree/main/packages/auto-icons

**Comment by GorvGoyl** [comment]
Thanks. For some reason, the icon was still not showing in grayscale, probably because I passed "localhost" as the mode instead of "development." However, I resolved it manually by using a different icon set in the WXT config file.
```json
 manifest: ({ browser, command, manifestVersion, mode }) => {
   return {
icons: mode === 'localhost' ? devIcon : prodIcon,
            action: {
                default_icon: mode === 'localhost' ? devIcon : prodIcon,
            },
}
```
